
INSERT INTO DPRRI (nama,partai,tps,desa,kecamatan,kabupaten,total) VALUES 
('PARTAI KEBANGKITAN BANGSA','Partai Kebangkitan Bangsa','TPS 01','GunungKeling','Cigugur','Kuningan',5),
('PARTAI KEBANGKITAN BANGSA','Partai Kebangkitan Bangsa','TPS 02','GunungKeling','Cigugur','Kuningan',7),
('PARTAI KEBANGKITAN BANGSA','Partai Kebangkitan Bangsa','TPS 03','GunungKeling','Cigugur','Kuningan',10),
('PARTAI KEBANGKITAN BANGSA','Partai Kebangkitan Bangsa','TPS 04','GunungKeling','Cigugur','Kuningan',2),
('PARTAI KEBANGKITAN BANGSA','Partai Kebangkitan Bangsa','TPS 05','GunungKeling','Cigugur','Kuningan',7),
('JOHAN J. ANWARI, M.Si','Partai Kebangkitan Bangsa','TPS 01','GunungKeling','Cigugur','Kuningan',3),
('JOHAN J. ANWARI, M.Si','Partai Kebangkitan Bangsa','TPS 02','GunungKeling','Cigugur','Kuningan',3),
('JOHAN J. ANWARI, M.Si','Partai Kebangkitan Bangsa','TPS 03','GunungKeling','Cigugur','Kuningan',0),
('JOHAN J. ANWARI, M.Si','Partai Kebangkitan Bangsa','TPS 04','GunungKeling','Cigugur','Kuningan',4),
('JOHAN J. ANWARI, M.Si','Partai Kebangkitan Bangsa','TPS 05','GunungKeling','Cigugur','Kuningan',3),
('AZIZAH TALITA DEWI, S.Sos., M.M.','Partai Kebangkitan Bangsa','TPS 01','GunungKeling','Cigugur','Kuningan',2),
('AZIZAH TALITA DEWI, S.Sos., M.M.','Partai Kebangkitan Bangsa','TPS 02','GunungKeling','Cigugur','Kuningan',3),
('AZIZAH TALITA DEWI, S.Sos., M.M.','Partai Kebangkitan Bangsa','TPS 03','GunungKeling','Cigugur','Kuningan',0),
('AZIZAH TALITA DEWI, S.Sos., M.M.','Partai Kebangkitan Bangsa','TPS 04','GunungKeling','Cigugur','Kuningan',3),
('AZIZAH TALITA DEWI, S.Sos., M.M.','Partai Kebangkitan Bangsa','TPS 05','GunungKeling','Cigugur','Kuningan',8),
('DADAN SIHABUDIN, S.IP., M.M','Partai Kebangkitan Bangsa','TPS 01','GunungKeling','Cigugur','Kuningan',2),
('DADAN SIHABUDIN, S.IP., M.M','Partai Kebangkitan Bangsa','TPS 02','GunungKeling','Cigugur','Kuningan',0),
('DADAN SIHABUDIN, S.IP., M.M','Partai Kebangkitan Bangsa','TPS 03','GunungKeling','Cigugur','Kuningan',2),
('DADAN SIHABUDIN, S.IP., M.M','Partai Kebangkitan Bangsa','TPS 04','GunungKeling','Cigugur','Kuningan',1),
('DADAN SIHABUDIN, S.IP., M.M','Partai Kebangkitan Bangsa','TPS 05','GunungKeling','Cigugur','Kuningan',1),
('ARIFUDIN, SP','Partai Kebangkitan Bangsa','TPS 01','GunungKeling','Cigugur','Kuningan',4),
('ARIFUDIN, SP','Partai Kebangkitan Bangsa','TPS 02','GunungKeling','Cigugur','Kuningan',0),
('ARIFUDIN, SP','Partai Kebangkitan Bangsa','TPS 03','GunungKeling','Cigugur','Kuningan',1),
('ARIFUDIN, SP','Partai Kebangkitan Bangsa','TPS 04','GunungKeling','Cigugur','Kuningan',0),
('ARIFUDIN, SP','Partai Kebangkitan Bangsa','TPS 05','GunungKeling','Cigugur','Kuningan',1),
('TATANG SAMSU RAIS, S.IP','Partai Kebangkitan Bangsa','TPS 01','GunungKeling','Cigugur','Kuningan',2),
('TATANG SAMSU RAIS, S.IP','Partai Kebangkitan Bangsa','TPS 02','GunungKeling','Cigugur','Kuningan',0),
('TATANG SAMSU RAIS, S.IP','Partai Kebangkitan Bangsa','TPS 03','GunungKeling','Cigugur','Kuningan',0),
('TATANG SAMSU RAIS, S.IP','Partai Kebangkitan Bangsa','TPS 04','GunungKeling','Cigugur','Kuningan',3),
('TATANG SAMSU RAIS, S.IP','Partai Kebangkitan Bangsa','TPS 05','GunungKeling','Cigugur','Kuningan',1),
('SYAYIDAH NURIKAWATI','Partai Kebangkitan Bangsa','TPS 01','GunungKeling','Cigugur','Kuningan',0),
('SYAYIDAH NURIKAWATI','Partai Kebangkitan Bangsa','TPS 02','GunungKeling','Cigugur','Kuningan',0),
('SYAYIDAH NURIKAWATI','Partai Kebangkitan Bangsa','TPS 03','GunungKeling','Cigugur','Kuningan',1),
('SYAYIDAH NURIKAWATI','Partai Kebangkitan Bangsa','TPS 04','GunungKeling','Cigugur','Kuningan',0),
('SYAYIDAH NURIKAWATI','Partai Kebangkitan Bangsa','TPS 05','GunungKeling','Cigugur','Kuningan',0),
('RONI ILHAM SUBAGJA, S.H.I., M.S.M','Partai Kebangkitan Bangsa','TPS 01','GunungKeling','Cigugur','Kuningan',4),
('RONI ILHAM SUBAGJA, S.H.I., M.S.M','Partai Kebangkitan Bangsa','TPS 02','GunungKeling','Cigugur','Kuningan',2),
('RONI ILHAM SUBAGJA, S.H.I., M.S.M','Partai Kebangkitan Bangsa','TPS 03','GunungKeling','Cigugur','Kuningan',0),
('RONI ILHAM SUBAGJA, S.H.I., M.S.M','Partai Kebangkitan Bangsa','TPS 04','GunungKeling','Cigugur','Kuningan',3),
('RONI ILHAM SUBAGJA, S.H.I., M.S.M','Partai Kebangkitan Bangsa','TPS 05','GunungKeling','Cigugur','Kuningan',4),
('SITI NURLATIFAH','Partai Kebangkitan Bangsa','TPS 01','GunungKeling','Cigugur','Kuningan',2),
('SITI NURLATIFAH','Partai Kebangkitan Bangsa','TPS 02','GunungKeling','Cigugur','Kuningan',0),
('SITI NURLATIFAH','Partai Kebangkitan Bangsa','TPS 03','GunungKeling','Cigugur','Kuningan',0),
('SITI NURLATIFAH','Partai Kebangkitan Bangsa','TPS 04','GunungKeling','Cigugur','Kuningan',2),
('SITI NURLATIFAH','Partai Kebangkitan Bangsa','TPS 05','GunungKeling','Cigugur','Kuningan',0),
('PARTAI GERAKAN INDONESIA RAYA','Partai Gerakan Indonesia Raya','TPS 01','GunungKeling','Cigugur','Kuningan',13),
('PARTAI GERAKAN INDONESIA RAYA','Partai Gerakan Indonesia Raya','TPS 02','GunungKeling','Cigugur','Kuningan',23),
('PARTAI GERAKAN INDONESIA RAYA','Partai Gerakan Indonesia Raya','TPS 03','GunungKeling','Cigugur','Kuningan',23),
('PARTAI GERAKAN INDONESIA RAYA','Partai Gerakan Indonesia Raya','TPS 04','GunungKeling','Cigugur','Kuningan',19),
('PARTAI GERAKAN INDONESIA RAYA','Partai Gerakan Indonesia Raya','TPS 05','GunungKeling','Cigugur','Kuningan',22),
('Hj. TINA WIRYAWATI, S.H','Partai Gerakan Indonesia Raya','TPS 01','GunungKeling','Cigugur','Kuningan',4),
('Hj. TINA WIRYAWATI, S.H','Partai Gerakan Indonesia Raya','TPS 02','GunungKeling','Cigugur','Kuningan',3),
('Hj. TINA WIRYAWATI, S.H','Partai Gerakan Indonesia Raya','TPS 03','GunungKeling','Cigugur','Kuningan',5),
('Hj. TINA WIRYAWATI, S.H','Partai Gerakan Indonesia Raya','TPS 04','GunungKeling','Cigugur','Kuningan',10),
('Hj. TINA WIRYAWATI, S.H','Partai Gerakan Indonesia Raya','TPS 05','GunungKeling','Cigugur','Kuningan',4),
('Ir. CECEP PERMANADI','Partai Gerakan Indonesia Raya','TPS 01','GunungKeling','Cigugur','Kuningan',8),
('Ir. CECEP PERMANADI','Partai Gerakan Indonesia Raya','TPS 02','GunungKeling','Cigugur','Kuningan',2),
('Ir. CECEP PERMANADI','Partai Gerakan Indonesia Raya','TPS 03','GunungKeling','Cigugur','Kuningan',6),
('Ir. CECEP PERMANADI','Partai Gerakan Indonesia Raya','TPS 04','GunungKeling','Cigugur','Kuningan',6),
('Ir. CECEP PERMANADI','Partai Gerakan Indonesia Raya','TPS 05','GunungKeling','Cigugur','Kuningan',4),
('KOLONEL (PURN) H. SURYAMAN, S.IP','Partai Gerakan Indonesia Raya','TPS 01','GunungKeling','Cigugur','Kuningan',3),
('KOLONEL (PURN) H. SURYAMAN, S.IP','Partai Gerakan Indonesia Raya','TPS 02','GunungKeling','Cigugur','Kuningan',4),
('KOLONEL (PURN) H. SURYAMAN, S.IP','Partai Gerakan Indonesia Raya','TPS 03','GunungKeling','Cigugur','Kuningan',2),
('KOLONEL (PURN) H. SURYAMAN, S.IP','Partai Gerakan Indonesia Raya','TPS 04','GunungKeling','Cigugur','Kuningan',8),
('KOLONEL (PURN) H. SURYAMAN, S.IP','Partai Gerakan Indonesia Raya','TPS 05','GunungKeling','Cigugur','Kuningan',2),
('KRISTINA SUDRAJAT','Partai Gerakan Indonesia Raya','TPS 01','GunungKeling','Cigugur','Kuningan',1),
('KRISTINA SUDRAJAT','Partai Gerakan Indonesia Raya','TPS 02','GunungKeling','Cigugur','Kuningan',0),
('KRISTINA SUDRAJAT','Partai Gerakan Indonesia Raya','TPS 03','GunungKeling','Cigugur','Kuningan',1),
('KRISTINA SUDRAJAT','Partai Gerakan Indonesia Raya','TPS 04','GunungKeling','Cigugur','Kuningan',3),
('KRISTINA SUDRAJAT','Partai Gerakan Indonesia Raya','TPS 05','GunungKeling','Cigugur','Kuningan',1),
('Drs. HARIDIS PARTADIMADJA, M.M','Partai Gerakan Indonesia Raya','TPS 01','GunungKeling','Cigugur','Kuningan',0),
('Drs. HARIDIS PARTADIMADJA, M.M','Partai Gerakan Indonesia Raya','TPS 02','GunungKeling','Cigugur','Kuningan',0),
('Drs. HARIDIS PARTADIMADJA, M.M','Partai Gerakan Indonesia Raya','TPS 03','GunungKeling','Cigugur','Kuningan',1),
('Drs. HARIDIS PARTADIMADJA, M.M','Partai Gerakan Indonesia Raya','TPS 04','GunungKeling','Cigugur','Kuningan',1),
('Drs. HARIDIS PARTADIMADJA, M.M','Partai Gerakan Indonesia Raya','TPS 05','GunungKeling','Cigugur','Kuningan',3),
('ALI SANTOSA, S.Sy','Partai Gerakan Indonesia Raya','TPS 01','GunungKeling','Cigugur','Kuningan',0),
('ALI SANTOSA, S.Sy','Partai Gerakan Indonesia Raya','TPS 02','GunungKeling','Cigugur','Kuningan',2),
('ALI SANTOSA, S.Sy','Partai Gerakan Indonesia Raya','TPS 03','GunungKeling','Cigugur','Kuningan',1),
('ALI SANTOSA, S.Sy','Partai Gerakan Indonesia Raya','TPS 04','GunungKeling','Cigugur','Kuningan',0),
('ALI SANTOSA, S.Sy','Partai Gerakan Indonesia Raya','TPS 05','GunungKeling','Cigugur','Kuningan',0),
('NURFITRIYANI PADJRIAH, S.Sn','Partai Gerakan Indonesia Raya','TPS 01','GunungKeling','Cigugur','Kuningan',0),
('NURFITRIYANI PADJRIAH, S.Sn','Partai Gerakan Indonesia Raya','TPS 02','GunungKeling','Cigugur','Kuningan',0),
('NURFITRIYANI PADJRIAH, S.Sn','Partai Gerakan Indonesia Raya','TPS 03','GunungKeling','Cigugur','Kuningan',1),
('NURFITRIYANI PADJRIAH, S.Sn','Partai Gerakan Indonesia Raya','TPS 04','GunungKeling','Cigugur','Kuningan',1),
('NURFITRIYANI PADJRIAH, S.Sn','Partai Gerakan Indonesia Raya','TPS 05','GunungKeling','Cigugur','Kuningan',1),
('TALIM E.S','Partai Gerakan Indonesia Raya','TPS 01','GunungKeling','Cigugur','Kuningan',0),
('TALIM E.S','Partai Gerakan Indonesia Raya','TPS 02','GunungKeling','Cigugur','Kuningan',0),
('TALIM E.S','Partai Gerakan Indonesia Raya','TPS 03','GunungKeling','Cigugur','Kuningan',0),
('TALIM E.S','Partai Gerakan Indonesia Raya','TPS 04','GunungKeling','Cigugur','Kuningan',0),
('TALIM E.S','Partai Gerakan Indonesia Raya','TPS 05','GunungKeling','Cigugur','Kuningan',0),
('PARTAI DEMOKRASI INDONESIA PERJUANGAN','Partai Demokrasi Indonesia Perjuangan','TPS 01','GunungKeling','Cigugur','Kuningan',23),
('PARTAI DEMOKRASI INDONESIA PERJUANGAN','Partai Demokrasi Indonesia Perjuangan','TPS 02','GunungKeling','Cigugur','Kuningan',11),
('PARTAI DEMOKRASI INDONESIA PERJUANGAN','Partai Demokrasi Indonesia Perjuangan','TPS 03','GunungKeling','Cigugur','Kuningan',14),
('PARTAI DEMOKRASI INDONESIA PERJUANGAN','Partai Demokrasi Indonesia Perjuangan','TPS 04','GunungKeling','Cigugur','Kuningan',14),
('PARTAI DEMOKRASI INDONESIA PERJUANGAN','Partai Demokrasi Indonesia Perjuangan','TPS 05','GunungKeling','Cigugur','Kuningan',13),
('BEDI BUDIMAN, S.IP., M.Si','Partai Demokrasi Indonesia Perjuangan','TPS 01','GunungKeling','Cigugur','Kuningan',3),
('BEDI BUDIMAN, S.IP., M.Si','Partai Demokrasi Indonesia Perjuangan','TPS 02','GunungKeling','Cigugur','Kuningan',5),
('BEDI BUDIMAN, S.IP., M.Si','Partai Demokrasi Indonesia Perjuangan','TPS 03','GunungKeling','Cigugur','Kuningan',0),
('BEDI BUDIMAN, S.IP., M.Si','Partai Demokrasi Indonesia Perjuangan','TPS 04','GunungKeling','Cigugur','Kuningan',2),
('BEDI BUDIMAN, S.IP., M.Si','Partai Demokrasi Indonesia Perjuangan','TPS 05','GunungKeling','Cigugur','Kuningan',3),
('Dra. Hj. IJAH HARTINI','Partai Demokrasi Indonesia Perjuangan','TPS 01','GunungKeling','Cigugur','Kuningan',5),
('Dra. Hj. IJAH HARTINI','Partai Demokrasi Indonesia Perjuangan','TPS 02','GunungKeling','Cigugur','Kuningan',5),
('Dra. Hj. IJAH HARTINI','Partai Demokrasi Indonesia Perjuangan','TPS 03','GunungKeling','Cigugur','Kuningan',2),
('Dra. Hj. IJAH HARTINI','Partai Demokrasi Indonesia Perjuangan','TPS 04','GunungKeling','Cigugur','Kuningan',6),
('Dra. Hj. IJAH HARTINI','Partai Demokrasi Indonesia Perjuangan','TPS 05','GunungKeling','Cigugur','Kuningan',3),
('WAWAN SETIAWAN, A.Md','Partai Demokrasi Indonesia Perjuangan','TPS 01','GunungKeling','Cigugur','Kuningan',4),
('WAWAN SETIAWAN, A.Md','Partai Demokrasi Indonesia Perjuangan','TPS 02','GunungKeling','Cigugur','Kuningan',1),
('WAWAN SETIAWAN, A.Md','Partai Demokrasi Indonesia Perjuangan','TPS 03','GunungKeling','Cigugur','Kuningan',5),
('WAWAN SETIAWAN, A.Md','Partai Demokrasi Indonesia Perjuangan','TPS 04','GunungKeling','Cigugur','Kuningan',2),
('WAWAN SETIAWAN, A.Md','Partai Demokrasi Indonesia Perjuangan','TPS 05','GunungKeling','Cigugur','Kuningan',6),
('H. IWAN M. RIDWAN, S.Pd., M.Pd','Partai Demokrasi Indonesia Perjuangan','TPS 01','GunungKeling','Cigugur','Kuningan',3),
('H. IWAN M. RIDWAN, S.Pd., M.Pd','Partai Demokrasi Indonesia Perjuangan','TPS 02','GunungKeling','Cigugur','Kuningan',2),
('H. IWAN M. RIDWAN, S.Pd., M.Pd','Partai Demokrasi Indonesia Perjuangan','TPS 03','GunungKeling','Cigugur','Kuningan',6),
('H. IWAN M. RIDWAN, S.Pd., M.Pd','Partai Demokrasi Indonesia Perjuangan','TPS 04','GunungKeling','Cigugur','Kuningan',1),
('H. IWAN M. RIDWAN, S.Pd., M.Pd','Partai Demokrasi Indonesia Perjuangan','TPS 05','GunungKeling','Cigugur','Kuningan',2),
('DESY HANDAYANI','Partai Demokrasi Indonesia Perjuangan','TPS 01','GunungKeling','Cigugur','Kuningan',2),
('DESY HANDAYANI','Partai Demokrasi Indonesia Perjuangan','TPS 02','GunungKeling','Cigugur','Kuningan',2),
('DESY HANDAYANI','Partai Demokrasi Indonesia Perjuangan','TPS 03','GunungKeling','Cigugur','Kuningan',1),
('DESY HANDAYANI','Partai Demokrasi Indonesia Perjuangan','TPS 04','GunungKeling','Cigugur','Kuningan',0),
('DESY HANDAYANI','Partai Demokrasi Indonesia Perjuangan','TPS 05','GunungKeling','Cigugur','Kuningan',0),
('Drs. UTUY SUYAMAN','Partai Demokrasi Indonesia Perjuangan','TPS 01','GunungKeling','Cigugur','Kuningan',0),
('Drs. UTUY SUYAMAN','Partai Demokrasi Indonesia Perjuangan','TPS 02','GunungKeling','Cigugur','Kuningan',0),
('Drs. UTUY SUYAMAN','Partai Demokrasi Indonesia Perjuangan','TPS 03','GunungKeling','Cigugur','Kuningan',1),
('Drs. UTUY SUYAMAN','Partai Demokrasi Indonesia Perjuangan','TPS 04','GunungKeling','Cigugur','Kuningan',1),
('Drs. UTUY SUYAMAN','Partai Demokrasi Indonesia Perjuangan','TPS 05','GunungKeling','Cigugur','Kuningan',0),
('ANDANG, S.Pd.I','Partai Demokrasi Indonesia Perjuangan','TPS 01','GunungKeling','Cigugur','Kuningan',1),
('ANDANG, S.Pd.I','Partai Demokrasi Indonesia Perjuangan','TPS 02','GunungKeling','Cigugur','Kuningan',0),
('ANDANG, S.Pd.I','Partai Demokrasi Indonesia Perjuangan','TPS 03','GunungKeling','Cigugur','Kuningan',1),
('ANDANG, S.Pd.I','Partai Demokrasi Indonesia Perjuangan','TPS 04','GunungKeling','Cigugur','Kuningan',0),
('ANDANG, S.Pd.I','Partai Demokrasi Indonesia Perjuangan','TPS 05','GunungKeling','Cigugur','Kuningan',1),
('RUSTIYANINGSIH','Partai Demokrasi Indonesia Perjuangan','TPS 01','GunungKeling','Cigugur','Kuningan',0),
('RUSTIYANINGSIH','Partai Demokrasi Indonesia Perjuangan','TPS 02','GunungKeling','Cigugur','Kuningan',1),
('RUSTIYANINGSIH','Partai Demokrasi Indonesia Perjuangan','TPS 03','GunungKeling','Cigugur','Kuningan',0),
('RUSTIYANINGSIH','Partai Demokrasi Indonesia Perjuangan','TPS 04','GunungKeling','Cigugur','Kuningan',0),
('RUSTIYANINGSIH','Partai Demokrasi Indonesia Perjuangan','TPS 05','GunungKeling','Cigugur','Kuningan',0),
('PARTAI GOLONGAN KARYA','Partai Golongan Karya','TPS 01','GunungKeling','Cigugur','Kuningan',4),
('PARTAI GOLONGAN KARYA','Partai Golongan Karya','TPS 02','GunungKeling','Cigugur','Kuningan',0),
('PARTAI GOLONGAN KARYA','Partai Golongan Karya','TPS 03','GunungKeling','Cigugur','Kuningan',2),
('PARTAI GOLONGAN KARYA','Partai Golongan Karya','TPS 04','GunungKeling','Cigugur','Kuningan',3),
('PARTAI GOLONGAN KARYA','Partai Golongan Karya','TPS 05','GunungKeling','Cigugur','Kuningan',1),
('Dr. dr. H. HERMAN SUTRISNO, M.M','Partai Golongan Karya','TPS 01','GunungKeling','Cigugur','Kuningan',1),
('Dr. dr. H. HERMAN SUTRISNO, M.M','Partai Golongan Karya','TPS 02','GunungKeling','Cigugur','Kuningan',0),
('Dr. dr. H. HERMAN SUTRISNO, M.M','Partai Golongan Karya','TPS 03','GunungKeling','Cigugur','Kuningan',2),
('Dr. dr. H. HERMAN SUTRISNO, M.M','Partai Golongan Karya','TPS 04','GunungKeling','Cigugur','Kuningan',0),
('Dr. dr. H. HERMAN SUTRISNO, M.M','Partai Golongan Karya','TPS 05','GunungKeling','Cigugur','Kuningan',1),
('H. DUDY PAMUJI, S.E., M.Si','Partai Golongan Karya','TPS 01','GunungKeling','Cigugur','Kuningan',7),
('H. DUDY PAMUJI, S.E., M.Si','Partai Golongan Karya','TPS 02','GunungKeling','Cigugur','Kuningan',7),
('H. DUDY PAMUJI, S.E., M.Si','Partai Golongan Karya','TPS 03','GunungKeling','Cigugur','Kuningan',6),
('H. DUDY PAMUJI, S.E., M.Si','Partai Golongan Karya','TPS 04','GunungKeling','Cigugur','Kuningan',7),
('H. DUDY PAMUJI, S.E., M.Si','Partai Golongan Karya','TPS 05','GunungKeling','Cigugur','Kuningan',2),
('NENDEN NURHAYATI','Partai Golongan Karya','TPS 01','GunungKeling','Cigugur','Kuningan',0),
('NENDEN NURHAYATI','Partai Golongan Karya','TPS 02','GunungKeling','Cigugur','Kuningan',0),
('NENDEN NURHAYATI','Partai Golongan Karya','TPS 03','GunungKeling','Cigugur','Kuningan',0),
('NENDEN NURHAYATI','Partai Golongan Karya','TPS 04','GunungKeling','Cigugur','Kuningan',2),
('NENDEN NURHAYATI','Partai Golongan Karya','TPS 05','GunungKeling','Cigugur','Kuningan',0),
('YADI KUSMAYADI, S.E','Partai Golongan Karya','TPS 01','GunungKeling','Cigugur','Kuningan',0),
('YADI KUSMAYADI, S.E','Partai Golongan Karya','TPS 02','GunungKeling','Cigugur','Kuningan',1),
('YADI KUSMAYADI, S.E','Partai Golongan Karya','TPS 03','GunungKeling','Cigugur','Kuningan',0),
('YADI KUSMAYADI, S.E','Partai Golongan Karya','TPS 04','GunungKeling','Cigugur','Kuningan',0),
('YADI KUSMAYADI, S.E','Partai Golongan Karya','TPS 05','GunungKeling','Cigugur','Kuningan',0),
('H. ENGKON KOMARA','Partai Golongan Karya','TPS 01','GunungKeling','Cigugur','Kuningan',0),
('H. ENGKON KOMARA','Partai Golongan Karya','TPS 02','GunungKeling','Cigugur','Kuningan',0),
('H. ENGKON KOMARA','Partai Golongan Karya','TPS 03','GunungKeling','Cigugur','Kuningan',1),
('H. ENGKON KOMARA','Partai Golongan Karya','TPS 04','GunungKeling','Cigugur','Kuningan',0),
('H. ENGKON KOMARA','Partai Golongan Karya','TPS 05','GunungKeling','Cigugur','Kuningan',0),
('Hj. LINA TARLINA, S.H.I','Partai Golongan Karya','TPS 01','GunungKeling','Cigugur','Kuningan',2),
('Hj. LINA TARLINA, S.H.I','Partai Golongan Karya','TPS 02','GunungKeling','Cigugur','Kuningan',1),
('Hj. LINA TARLINA, S.H.I','Partai Golongan Karya','TPS 03','GunungKeling','Cigugur','Kuningan',1),
('Hj. LINA TARLINA, S.H.I','Partai Golongan Karya','TPS 04','GunungKeling','Cigugur','Kuningan',0),
('Hj. LINA TARLINA, S.H.I','Partai Golongan Karya','TPS 05','GunungKeling','Cigugur','Kuningan',0),
('dr. ERWIN MOCHAMAD THAMRIN','Partai Golongan Karya','TPS 01','GunungKeling','Cigugur','Kuningan',2),
('dr. ERWIN MOCHAMAD THAMRIN','Partai Golongan Karya','TPS 02','GunungKeling','Cigugur','Kuningan',2),
('dr. ERWIN MOCHAMAD THAMRIN','Partai Golongan Karya','TPS 03','GunungKeling','Cigugur','Kuningan',0),
('dr. ERWIN MOCHAMAD THAMRIN','Partai Golongan Karya','TPS 04','GunungKeling','Cigugur','Kuningan',0),
('dr. ERWIN MOCHAMAD THAMRIN','Partai Golongan Karya','TPS 05','GunungKeling','Cigugur','Kuningan',0),
('ANI OKTAVIANI, S.Pd','Partai Golongan Karya','TPS 01','GunungKeling','Cigugur','Kuningan',0),
('ANI OKTAVIANI, S.Pd','Partai Golongan Karya','TPS 02','GunungKeling','Cigugur','Kuningan',0),
('ANI OKTAVIANI, S.Pd','Partai Golongan Karya','TPS 03','GunungKeling','Cigugur','Kuningan',0),
('ANI OKTAVIANI, S.Pd','Partai Golongan Karya','TPS 04','GunungKeling','Cigugur','Kuningan',0),
('ANI OKTAVIANI, S.Pd','Partai Golongan Karya','TPS 05','GunungKeling','Cigugur','Kuningan',0),
('PARTAI NASDEM','Partai Nasdem','TPS 01','GunungKeling','Cigugur','Kuningan',2),
('PARTAI NASDEM','Partai Nasdem','TPS 02','GunungKeling','Cigugur','Kuningan',0),
('PARTAI NASDEM','Partai Nasdem','TPS 03','GunungKeling','Cigugur','Kuningan',2),
('PARTAI NASDEM','Partai Nasdem','TPS 04','GunungKeling','Cigugur','Kuningan',2),
('PARTAI NASDEM','Partai Nasdem','TPS 05','GunungKeling','Cigugur','Kuningan',2),
('Dra. SRI MULYATI, M.P.A','Partai Nasdem','TPS 01','GunungKeling','Cigugur','Kuningan',0),
('Dra. SRI MULYATI, M.P.A','Partai Nasdem','TPS 02','GunungKeling','Cigugur','Kuningan',0),
('Dra. SRI MULYATI, M.P.A','Partai Nasdem','TPS 03','GunungKeling','Cigugur','Kuningan',1),
('Dra. SRI MULYATI, M.P.A','Partai Nasdem','TPS 04','GunungKeling','Cigugur','Kuningan',0),
('Dra. SRI MULYATI, M.P.A','Partai Nasdem','TPS 05','GunungKeling','Cigugur','Kuningan',1),
('DAFID FIRDAUS','Partai Nasdem','TPS 01','GunungKeling','Cigugur','Kuningan',0),
('DAFID FIRDAUS','Partai Nasdem','TPS 02','GunungKeling','Cigugur','Kuningan',0),
('DAFID FIRDAUS','Partai Nasdem','TPS 03','GunungKeling','Cigugur','Kuningan',2),
('DAFID FIRDAUS','Partai Nasdem','TPS 04','GunungKeling','Cigugur','Kuningan',0),
('DAFID FIRDAUS','Partai Nasdem','TPS 05','GunungKeling','Cigugur','Kuningan',0),
('YOSEP YUSDIANA, S.Pd.I','Partai Nasdem','TPS 01','GunungKeling','Cigugur','Kuningan',0),
('YOSEP YUSDIANA, S.Pd.I','Partai Nasdem','TPS 02','GunungKeling','Cigugur','Kuningan',0),
('YOSEP YUSDIANA, S.Pd.I','Partai Nasdem','TPS 03','GunungKeling','Cigugur','Kuningan',3),
('YOSEP YUSDIANA, S.Pd.I','Partai Nasdem','TPS 04','GunungKeling','Cigugur','Kuningan',2),
('YOSEP YUSDIANA, S.Pd.I','Partai Nasdem','TPS 05','GunungKeling','Cigugur','Kuningan',1),
('IKIN ZAENAL MUTTAQIN, S.Pd.I','Partai Nasdem','TPS 01','GunungKeling','Cigugur','Kuningan',1),
('IKIN ZAENAL MUTTAQIN, S.Pd.I','Partai Nasdem','TPS 02','GunungKeling','Cigugur','Kuningan',0),
('IKIN ZAENAL MUTTAQIN, S.Pd.I','Partai Nasdem','TPS 03','GunungKeling','Cigugur','Kuningan',1),
('IKIN ZAENAL MUTTAQIN, S.Pd.I','Partai Nasdem','TPS 04','GunungKeling','Cigugur','Kuningan',0),
('IKIN ZAENAL MUTTAQIN, S.Pd.I','Partai Nasdem','TPS 05','GunungKeling','Cigugur','Kuningan',0),
('CANDRA NOVITA, S.H','Partai Nasdem','TPS 01','GunungKeling','Cigugur','Kuningan',0),
('CANDRA NOVITA, S.H','Partai Nasdem','TPS 02','GunungKeling','Cigugur','Kuningan',0),
('CANDRA NOVITA, S.H','Partai Nasdem','TPS 03','GunungKeling','Cigugur','Kuningan',0),
('CANDRA NOVITA, S.H','Partai Nasdem','TPS 04','GunungKeling','Cigugur','Kuningan',0),
('CANDRA NOVITA, S.H','Partai Nasdem','TPS 05','GunungKeling','Cigugur','Kuningan',0),
('ELIES SUCIATI SOEKANTO, A.Md','Partai Nasdem','TPS 01','GunungKeling','Cigugur','Kuningan',0),
('ELIES SUCIATI SOEKANTO, A.Md','Partai Nasdem','TPS 02','GunungKeling','Cigugur','Kuningan',0),
('ELIES SUCIATI SOEKANTO, A.Md','Partai Nasdem','TPS 03','GunungKeling','Cigugur','Kuningan',0),
('ELIES SUCIATI SOEKANTO, A.Md','Partai Nasdem','TPS 04','GunungKeling','Cigugur','Kuningan',0),
('ELIES SUCIATI SOEKANTO, A.Md','Partai Nasdem','TPS 05','GunungKeling','Cigugur','Kuningan',0),
('MOHAMAD SOEBAGJA, S.E., M.M','Partai Nasdem','TPS 01','GunungKeling','Cigugur','Kuningan',0),
('MOHAMAD SOEBAGJA, S.E., M.M','Partai Nasdem','TPS 02','GunungKeling','Cigugur','Kuningan',0),
('MOHAMAD SOEBAGJA, S.E., M.M','Partai Nasdem','TPS 03','GunungKeling','Cigugur','Kuningan',1),
('MOHAMAD SOEBAGJA, S.E., M.M','Partai Nasdem','TPS 04','GunungKeling','Cigugur','Kuningan',2),
('MOHAMAD SOEBAGJA, S.E., M.M','Partai Nasdem','TPS 05','GunungKeling','Cigugur','Kuningan',0),
('H. ZAINUL MUSTAFA AFFANDI, S.E','Partai Nasdem','TPS 01','GunungKeling','Cigugur','Kuningan',0),
('H. ZAINUL MUSTAFA AFFANDI, S.E','Partai Nasdem','TPS 02','GunungKeling','Cigugur','Kuningan',2),
('H. ZAINUL MUSTAFA AFFANDI, S.E','Partai Nasdem','TPS 03','GunungKeling','Cigugur','Kuningan',2),
('H. ZAINUL MUSTAFA AFFANDI, S.E','Partai Nasdem','TPS 04','GunungKeling','Cigugur','Kuningan',0),
('H. ZAINUL MUSTAFA AFFANDI, S.E','Partai Nasdem','TPS 05','GunungKeling','Cigugur','Kuningan',0),
('PARTAI GERAKAN PERUBAHAN INDONESIA','Partai Gerakan Perubahan Indonesia','TPS 01','GunungKeling','Cigugur','Kuningan',1),
('PARTAI GERAKAN PERUBAHAN INDONESIA','Partai Gerakan Perubahan Indonesia','TPS 02','GunungKeling','Cigugur','Kuningan',0),
('PARTAI GERAKAN PERUBAHAN INDONESIA','Partai Gerakan Perubahan Indonesia','TPS 03','GunungKeling','Cigugur','Kuningan',3),
('PARTAI GERAKAN PERUBAHAN INDONESIA','Partai Gerakan Perubahan Indonesia','TPS 04','GunungKeling','Cigugur','Kuningan',0),
('PARTAI GERAKAN PERUBAHAN INDONESIA','Partai Gerakan Perubahan Indonesia','TPS 05','GunungKeling','Cigugur','Kuningan',0),
('PARTAI BERKARYA','Partai Berkarya','TPS 01','GunungKeling','Cigugur','Kuningan',16),
('PARTAI BERKARYA','Partai Berkarya','TPS 02','GunungKeling','Cigugur','Kuningan',8),
('PARTAI BERKARYA','Partai Berkarya','TPS 03','GunungKeling','Cigugur','Kuningan',2),
('PARTAI BERKARYA','Partai Berkarya','TPS 04','GunungKeling','Cigugur','Kuningan',7),
('PARTAI BERKARYA','Partai Berkarya','TPS 05','GunungKeling','Cigugur','Kuningan',7),
('ENANG NURDIN, S.E','Partai Berkarya','TPS 01','GunungKeling','Cigugur','Kuningan',1),
('ENANG NURDIN, S.E','Partai Berkarya','TPS 02','GunungKeling','Cigugur','Kuningan',1),
('ENANG NURDIN, S.E','Partai Berkarya','TPS 03','GunungKeling','Cigugur','Kuningan',0),
('ENANG NURDIN, S.E','Partai Berkarya','TPS 04','GunungKeling','Cigugur','Kuningan',0),
('ENANG NURDIN, S.E','Partai Berkarya','TPS 05','GunungKeling','Cigugur','Kuningan',0),
('PURKONUDIN. S.Ag','Partai Berkarya','TPS 01','GunungKeling','Cigugur','Kuningan',1),
('PURKONUDIN. S.Ag','Partai Berkarya','TPS 02','GunungKeling','Cigugur','Kuningan',0),
('PURKONUDIN. S.Ag','Partai Berkarya','TPS 03','GunungKeling','Cigugur','Kuningan',0),
('PURKONUDIN. S.Ag','Partai Berkarya','TPS 04','GunungKeling','Cigugur','Kuningan',1),
('PURKONUDIN. S.Ag','Partai Berkarya','TPS 05','GunungKeling','Cigugur','Kuningan',0),
('drh. LIA HOLLIANTI','Partai Berkarya','TPS 01','GunungKeling','Cigugur','Kuningan',0),
('drh. LIA HOLLIANTI','Partai Berkarya','TPS 02','GunungKeling','Cigugur','Kuningan',0),
('drh. LIA HOLLIANTI','Partai Berkarya','TPS 03','GunungKeling','Cigugur','Kuningan',0),
('drh. LIA HOLLIANTI','Partai Berkarya','TPS 04','GunungKeling','Cigugur','Kuningan',1),
('drh. LIA HOLLIANTI','Partai Berkarya','TPS 05','GunungKeling','Cigugur','Kuningan',0),
('WELLY SURJONO. S.E., M.Si','Partai Berkarya','TPS 01','GunungKeling','Cigugur','Kuningan',1),
('WELLY SURJONO. S.E., M.Si','Partai Berkarya','TPS 02','GunungKeling','Cigugur','Kuningan',1),
('WELLY SURJONO. S.E., M.Si','Partai Berkarya','TPS 03','GunungKeling','Cigugur','Kuningan',0),
('WELLY SURJONO. S.E., M.Si','Partai Berkarya','TPS 04','GunungKeling','Cigugur','Kuningan',0),
('WELLY SURJONO. S.E., M.Si','Partai Berkarya','TPS 05','GunungKeling','Cigugur','Kuningan',0),
('ANY YUNIANY','Partai Berkarya','TPS 01','GunungKeling','Cigugur','Kuningan',0),
('ANY YUNIANY','Partai Berkarya','TPS 02','GunungKeling','Cigugur','Kuningan',0),
('ANY YUNIANY','Partai Berkarya','TPS 03','GunungKeling','Cigugur','Kuningan',0),
('ANY YUNIANY','Partai Berkarya','TPS 04','GunungKeling','Cigugur','Kuningan',0),
('ANY YUNIANY','Partai Berkarya','TPS 05','GunungKeling','Cigugur','Kuningan',0),
('RUDI NURAHMAT','Partai Berkarya','TPS 01','GunungKeling','Cigugur','Kuningan',0),
('RUDI NURAHMAT','Partai Berkarya','TPS 02','GunungKeling','Cigugur','Kuningan',0),
('RUDI NURAHMAT','Partai Berkarya','TPS 03','GunungKeling','Cigugur','Kuningan',0),
('RUDI NURAHMAT','Partai Berkarya','TPS 04','GunungKeling','Cigugur','Kuningan',1),
('RUDI NURAHMAT','Partai Berkarya','TPS 05','GunungKeling','Cigugur','Kuningan',0),
('INDRIE YERI TRISMAWATI','Partai Berkarya','TPS 01','GunungKeling','Cigugur','Kuningan',0),
('INDRIE YERI TRISMAWATI','Partai Berkarya','TPS 02','GunungKeling','Cigugur','Kuningan',0),
('INDRIE YERI TRISMAWATI','Partai Berkarya','TPS 03','GunungKeling','Cigugur','Kuningan',0),
('INDRIE YERI TRISMAWATI','Partai Berkarya','TPS 04','GunungKeling','Cigugur','Kuningan',0),
('INDRIE YERI TRISMAWATI','Partai Berkarya','TPS 05','GunungKeling','Cigugur','Kuningan',0),
('PARTAI KEADILAN SEJAHTERA','Partai Keadilan Sejahtera','TPS 01','GunungKeling','Cigugur','Kuningan',12),
('PARTAI KEADILAN SEJAHTERA','Partai Keadilan Sejahtera','TPS 02','GunungKeling','Cigugur','Kuningan',25),
('PARTAI KEADILAN SEJAHTERA','Partai Keadilan Sejahtera','TPS 03','GunungKeling','Cigugur','Kuningan',35),
('PARTAI KEADILAN SEJAHTERA','Partai Keadilan Sejahtera','TPS 04','GunungKeling','Cigugur','Kuningan',23),
('PARTAI KEADILAN SEJAHTERA','Partai Keadilan Sejahtera','TPS 05','GunungKeling','Cigugur','Kuningan',28),
('H. DIDI SUKARDI, S.E','Partai Keadilan Sejahtera','TPS 01','GunungKeling','Cigugur','Kuningan',5),
('H. DIDI SUKARDI, S.E','Partai Keadilan Sejahtera','TPS 02','GunungKeling','Cigugur','Kuningan',9),
('H. DIDI SUKARDI, S.E','Partai Keadilan Sejahtera','TPS 03','GunungKeling','Cigugur','Kuningan',7),
('H. DIDI SUKARDI, S.E','Partai Keadilan Sejahtera','TPS 04','GunungKeling','Cigugur','Kuningan',4),
('H. DIDI SUKARDI, S.E','Partai Keadilan Sejahtera','TPS 05','GunungKeling','Cigugur','Kuningan',17),
('H. RIJALLUDDIN. S.Pd','Partai Keadilan Sejahtera','TPS 01','GunungKeling','Cigugur','Kuningan',4),
('H. RIJALLUDDIN. S.Pd','Partai Keadilan Sejahtera','TPS 02','GunungKeling','Cigugur','Kuningan',9),
('H. RIJALLUDDIN. S.Pd','Partai Keadilan Sejahtera','TPS 03','GunungKeling','Cigugur','Kuningan',11),
('H. RIJALLUDDIN. S.Pd','Partai Keadilan Sejahtera','TPS 04','GunungKeling','Cigugur','Kuningan',3),
('H. RIJALLUDDIN. S.Pd','Partai Keadilan Sejahtera','TPS 05','GunungKeling','Cigugur','Kuningan',9),
('APRIANI, S.Sos.I','Partai Keadilan Sejahtera','TPS 01','GunungKeling','Cigugur','Kuningan',5),
('APRIANI, S.Sos.I','Partai Keadilan Sejahtera','TPS 02','GunungKeling','Cigugur','Kuningan',13),
('APRIANI, S.Sos.I','Partai Keadilan Sejahtera','TPS 03','GunungKeling','Cigugur','Kuningan',4),
('APRIANI, S.Sos.I','Partai Keadilan Sejahtera','TPS 04','GunungKeling','Cigugur','Kuningan',8),
('APRIANI, S.Sos.I','Partai Keadilan Sejahtera','TPS 05','GunungKeling','Cigugur','Kuningan',2),
('RUMESTI AYU RIYANDINI, S.P','Partai Keadilan Sejahtera','TPS 01','GunungKeling','Cigugur','Kuningan',1),
('RUMESTI AYU RIYANDINI, S.P','Partai Keadilan Sejahtera','TPS 02','GunungKeling','Cigugur','Kuningan',4),
('RUMESTI AYU RIYANDINI, S.P','Partai Keadilan Sejahtera','TPS 03','GunungKeling','Cigugur','Kuningan',1),
('RUMESTI AYU RIYANDINI, S.P','Partai Keadilan Sejahtera','TPS 04','GunungKeling','Cigugur','Kuningan',3),
('RUMESTI AYU RIYANDINI, S.P','Partai Keadilan Sejahtera','TPS 05','GunungKeling','Cigugur','Kuningan',3),
('Hj. YATI SURYATI','Partai Keadilan Sejahtera','TPS 01','GunungKeling','Cigugur','Kuningan',3),
('Hj. YATI SURYATI','Partai Keadilan Sejahtera','TPS 02','GunungKeling','Cigugur','Kuningan',2),
('Hj. YATI SURYATI','Partai Keadilan Sejahtera','TPS 03','GunungKeling','Cigugur','Kuningan',1),
('Hj. YATI SURYATI','Partai Keadilan Sejahtera','TPS 04','GunungKeling','Cigugur','Kuningan',10),
('Hj. YATI SURYATI','Partai Keadilan Sejahtera','TPS 05','GunungKeling','Cigugur','Kuningan',6),
('DADANG RUHIYANA, S.Sos., M.P','Partai Keadilan Sejahtera','TPS 01','GunungKeling','Cigugur','Kuningan',1),
('DADANG RUHIYANA, S.Sos., M.P','Partai Keadilan Sejahtera','TPS 02','GunungKeling','Cigugur','Kuningan',0),
('DADANG RUHIYANA, S.Sos., M.P','Partai Keadilan Sejahtera','TPS 03','GunungKeling','Cigugur','Kuningan',2),
('DADANG RUHIYANA, S.Sos., M.P','Partai Keadilan Sejahtera','TPS 04','GunungKeling','Cigugur','Kuningan',2),
('DADANG RUHIYANA, S.Sos., M.P','Partai Keadilan Sejahtera','TPS 05','GunungKeling','Cigugur','Kuningan',0),
('Drs. H. EDI KUSNADI','Partai Keadilan Sejahtera','TPS 01','GunungKeling','Cigugur','Kuningan',0),
('Drs. H. EDI KUSNADI','Partai Keadilan Sejahtera','TPS 02','GunungKeling','Cigugur','Kuningan',1),
('Drs. H. EDI KUSNADI','Partai Keadilan Sejahtera','TPS 03','GunungKeling','Cigugur','Kuningan',0),
('Drs. H. EDI KUSNADI','Partai Keadilan Sejahtera','TPS 04','GunungKeling','Cigugur','Kuningan',1),
('Drs. H. EDI KUSNADI','Partai Keadilan Sejahtera','TPS 05','GunungKeling','Cigugur','Kuningan',0),
('PARTAI PERSATUAN INDONESIA','Partai Persatuan Indonesia','TPS 01','GunungKeling','Cigugur','Kuningan',3),
('PARTAI PERSATUAN INDONESIA','Partai Persatuan Indonesia','TPS 02','GunungKeling','Cigugur','Kuningan',1),
('PARTAI PERSATUAN INDONESIA','Partai Persatuan Indonesia','TPS 03','GunungKeling','Cigugur','Kuningan',2),
('PARTAI PERSATUAN INDONESIA','Partai Persatuan Indonesia','TPS 04','GunungKeling','Cigugur','Kuningan',2),
('PARTAI PERSATUAN INDONESIA','Partai Persatuan Indonesia','TPS 05','GunungKeling','Cigugur','Kuningan',4),
('DEDE NURDIN SADAT, S.H','Partai Persatuan Indonesia','TPS 01','GunungKeling','Cigugur','Kuningan',3),
('DEDE NURDIN SADAT, S.H','Partai Persatuan Indonesia','TPS 02','GunungKeling','Cigugur','Kuningan',1),
('DEDE NURDIN SADAT, S.H','Partai Persatuan Indonesia','TPS 03','GunungKeling','Cigugur','Kuningan',1),
('DEDE NURDIN SADAT, S.H','Partai Persatuan Indonesia','TPS 04','GunungKeling','Cigugur','Kuningan',0),
('DEDE NURDIN SADAT, S.H','Partai Persatuan Indonesia','TPS 05','GunungKeling','Cigugur','Kuningan',0),
('IWAN SETIAWAN, S.E','Partai Persatuan Indonesia','TPS 01','GunungKeling','Cigugur','Kuningan',0),
('IWAN SETIAWAN, S.E','Partai Persatuan Indonesia','TPS 02','GunungKeling','Cigugur','Kuningan',0),
('IWAN SETIAWAN, S.E','Partai Persatuan Indonesia','TPS 03','GunungKeling','Cigugur','Kuningan',0),
('IWAN SETIAWAN, S.E','Partai Persatuan Indonesia','TPS 04','GunungKeling','Cigugur','Kuningan',0),
('IWAN SETIAWAN, S.E','Partai Persatuan Indonesia','TPS 05','GunungKeling','Cigugur','Kuningan',0),
('NENENG YUNENGSIH, S.Pd','Partai Persatuan Indonesia','TPS 01','GunungKeling','Cigugur','Kuningan',1),
('NENENG YUNENGSIH, S.Pd','Partai Persatuan Indonesia','TPS 02','GunungKeling','Cigugur','Kuningan',1),
('NENENG YUNENGSIH, S.Pd','Partai Persatuan Indonesia','TPS 03','GunungKeling','Cigugur','Kuningan',0),
('NENENG YUNENGSIH, S.Pd','Partai Persatuan Indonesia','TPS 04','GunungKeling','Cigugur','Kuningan',0),
('NENENG YUNENGSIH, S.Pd','Partai Persatuan Indonesia','TPS 05','GunungKeling','Cigugur','Kuningan',0),
('DENY IRWAN,S.E','Partai Persatuan Indonesia','TPS 01','GunungKeling','Cigugur','Kuningan',0),
('DENY IRWAN,S.E','Partai Persatuan Indonesia','TPS 02','GunungKeling','Cigugur','Kuningan',0),
('DENY IRWAN,S.E','Partai Persatuan Indonesia','TPS 03','GunungKeling','Cigugur','Kuningan',1),
('DENY IRWAN,S.E','Partai Persatuan Indonesia','TPS 04','GunungKeling','Cigugur','Kuningan',0),
('DENY IRWAN,S.E','Partai Persatuan Indonesia','TPS 05','GunungKeling','Cigugur','Kuningan',0),
('NENI HARYANI','Partai Persatuan Indonesia','TPS 01','GunungKeling','Cigugur','Kuningan',0),
('NENI HARYANI','Partai Persatuan Indonesia','TPS 02','GunungKeling','Cigugur','Kuningan',1),
('NENI HARYANI','Partai Persatuan Indonesia','TPS 03','GunungKeling','Cigugur','Kuningan',0),
('NENI HARYANI','Partai Persatuan Indonesia','TPS 04','GunungKeling','Cigugur','Kuningan',0),
('NENI HARYANI','Partai Persatuan Indonesia','TPS 05','GunungKeling','Cigugur','Kuningan',0),
('SURYAHADI, S.E., S.Ip., M.Si','Partai Persatuan Indonesia','TPS 01','GunungKeling','Cigugur','Kuningan',0),
('SURYAHADI, S.E., S.Ip., M.Si','Partai Persatuan Indonesia','TPS 02','GunungKeling','Cigugur','Kuningan',0),
('SURYAHADI, S.E., S.Ip., M.Si','Partai Persatuan Indonesia','TPS 03','GunungKeling','Cigugur','Kuningan',1),
('SURYAHADI, S.E., S.Ip., M.Si','Partai Persatuan Indonesia','TPS 04','GunungKeling','Cigugur','Kuningan',0),
('SURYAHADI, S.E., S.Ip., M.Si','Partai Persatuan Indonesia','TPS 05','GunungKeling','Cigugur','Kuningan',0),
('LIA DAHLIA','Partai Persatuan Indonesia','TPS 01','GunungKeling','Cigugur','Kuningan',0),
('LIA DAHLIA','Partai Persatuan Indonesia','TPS 02','GunungKeling','Cigugur','Kuningan',0),
('LIA DAHLIA','Partai Persatuan Indonesia','TPS 03','GunungKeling','Cigugur','Kuningan',0),
('LIA DAHLIA','Partai Persatuan Indonesia','TPS 04','GunungKeling','Cigugur','Kuningan',0),
('LIA DAHLIA','Partai Persatuan Indonesia','TPS 05','GunungKeling','Cigugur','Kuningan',0),
('BAGJA SETIA, S.P','Partai Persatuan Indonesia','TPS 01','GunungKeling','Cigugur','Kuningan',0),
('BAGJA SETIA, S.P','Partai Persatuan Indonesia','TPS 02','GunungKeling','Cigugur','Kuningan',0),
('BAGJA SETIA, S.P','Partai Persatuan Indonesia','TPS 03','GunungKeling','Cigugur','Kuningan',0),
('BAGJA SETIA, S.P','Partai Persatuan Indonesia','TPS 04','GunungKeling','Cigugur','Kuningan',0),
('BAGJA SETIA, S.P','Partai Persatuan Indonesia','TPS 05','GunungKeling','Cigugur','Kuningan',0),
('PARTAI PERSATUAN PEMBANGUNAN','Partai Persatuan Pembangunan','TPS 01','GunungKeling','Cigugur','Kuningan',0),
('PARTAI PERSATUAN PEMBANGUNAN','Partai Persatuan Pembangunan','TPS 02','GunungKeling','Cigugur','Kuningan',0),
('PARTAI PERSATUAN PEMBANGUNAN','Partai Persatuan Pembangunan','TPS 03','GunungKeling','Cigugur','Kuningan',0),
('PARTAI PERSATUAN PEMBANGUNAN','Partai Persatuan Pembangunan','TPS 04','GunungKeling','Cigugur','Kuningan',1),
('PARTAI PERSATUAN PEMBANGUNAN','Partai Persatuan Pembangunan','TPS 05','GunungKeling','Cigugur','Kuningan',2),
('OYAT NURAYAT, M.Ag','Partai Persatuan Pembangunan','TPS 01','GunungKeling','Cigugur','Kuningan',0),
('OYAT NURAYAT, M.Ag','Partai Persatuan Pembangunan','TPS 02','GunungKeling','Cigugur','Kuningan',0),
('OYAT NURAYAT, M.Ag','Partai Persatuan Pembangunan','TPS 03','GunungKeling','Cigugur','Kuningan',0),
('OYAT NURAYAT, M.Ag','Partai Persatuan Pembangunan','TPS 04','GunungKeling','Cigugur','Kuningan',0),
('OYAT NURAYAT, M.Ag','Partai Persatuan Pembangunan','TPS 05','GunungKeling','Cigugur','Kuningan',2),
('H. YUSRON KHOLID,S.Ag., M.Si','Partai Persatuan Pembangunan','TPS 01','GunungKeling','Cigugur','Kuningan',2),
('H. YUSRON KHOLID,S.Ag., M.Si','Partai Persatuan Pembangunan','TPS 02','GunungKeling','Cigugur','Kuningan',2),
('H. YUSRON KHOLID,S.Ag., M.Si','Partai Persatuan Pembangunan','TPS 03','GunungKeling','Cigugur','Kuningan',1),
('H. YUSRON KHOLID,S.Ag., M.Si','Partai Persatuan Pembangunan','TPS 04','GunungKeling','Cigugur','Kuningan',0),
('H. YUSRON KHOLID,S.Ag., M.Si','Partai Persatuan Pembangunan','TPS 05','GunungKeling','Cigugur','Kuningan',2),
('CUCU SURTIKAWATI','Partai Persatuan Pembangunan','TPS 01','GunungKeling','Cigugur','Kuningan',0),
('CUCU SURTIKAWATI','Partai Persatuan Pembangunan','TPS 02','GunungKeling','Cigugur','Kuningan',1),
('CUCU SURTIKAWATI','Partai Persatuan Pembangunan','TPS 03','GunungKeling','Cigugur','Kuningan',0),
('CUCU SURTIKAWATI','Partai Persatuan Pembangunan','TPS 04','GunungKeling','Cigugur','Kuningan',0),
('CUCU SURTIKAWATI','Partai Persatuan Pembangunan','TPS 05','GunungKeling','Cigugur','Kuningan',0),
('FARHAN','Partai Persatuan Pembangunan','TPS 01','GunungKeling','Cigugur','Kuningan',0),
('FARHAN','Partai Persatuan Pembangunan','TPS 02','GunungKeling','Cigugur','Kuningan',1),
('FARHAN','Partai Persatuan Pembangunan','TPS 03','GunungKeling','Cigugur','Kuningan',0),
('FARHAN','Partai Persatuan Pembangunan','TPS 04','GunungKeling','Cigugur','Kuningan',1),
('FARHAN','Partai Persatuan Pembangunan','TPS 05','GunungKeling','Cigugur','Kuningan',0),
('DANIAR RACHMANJANI, S.H','Partai Persatuan Pembangunan','TPS 01','GunungKeling','Cigugur','Kuningan',0),
('DANIAR RACHMANJANI, S.H','Partai Persatuan Pembangunan','TPS 02','GunungKeling','Cigugur','Kuningan',0),
('DANIAR RACHMANJANI, S.H','Partai Persatuan Pembangunan','TPS 03','GunungKeling','Cigugur','Kuningan',0),
('DANIAR RACHMANJANI, S.H','Partai Persatuan Pembangunan','TPS 04','GunungKeling','Cigugur','Kuningan',0),
('DANIAR RACHMANJANI, S.H','Partai Persatuan Pembangunan','TPS 05','GunungKeling','Cigugur','Kuningan',0),
('AI AAN HERMAYANI, S.Pd.I','Partai Persatuan Pembangunan','TPS 01','GunungKeling','Cigugur','Kuningan',0),
('AI AAN HERMAYANI, S.Pd.I','Partai Persatuan Pembangunan','TPS 02','GunungKeling','Cigugur','Kuningan',1),
('AI AAN HERMAYANI, S.Pd.I','Partai Persatuan Pembangunan','TPS 03','GunungKeling','Cigugur','Kuningan',0),
('AI AAN HERMAYANI, S.Pd.I','Partai Persatuan Pembangunan','TPS 04','GunungKeling','Cigugur','Kuningan',0),
('AI AAN HERMAYANI, S.Pd.I','Partai Persatuan Pembangunan','TPS 05','GunungKeling','Cigugur','Kuningan',0),
('LILIS INAYATI, S.Pd.I','Partai Persatuan Pembangunan','TPS 01','GunungKeling','Cigugur','Kuningan',1),
('LILIS INAYATI, S.Pd.I','Partai Persatuan Pembangunan','TPS 02','GunungKeling','Cigugur','Kuningan',0),
('LILIS INAYATI, S.Pd.I','Partai Persatuan Pembangunan','TPS 03','GunungKeling','Cigugur','Kuningan',0),
('LILIS INAYATI, S.Pd.I','Partai Persatuan Pembangunan','TPS 04','GunungKeling','Cigugur','Kuningan',0),
('LILIS INAYATI, S.Pd.I','Partai Persatuan Pembangunan','TPS 05','GunungKeling','Cigugur','Kuningan',0),
('RAHWAN SANUSI, S.Ag., M.Pd.I','Partai Persatuan Pembangunan','TPS 01','GunungKeling','Cigugur','Kuningan',0),
('RAHWAN SANUSI, S.Ag., M.Pd.I','Partai Persatuan Pembangunan','TPS 02','GunungKeling','Cigugur','Kuningan',0),
('RAHWAN SANUSI, S.Ag., M.Pd.I','Partai Persatuan Pembangunan','TPS 03','GunungKeling','Cigugur','Kuningan',0),
('RAHWAN SANUSI, S.Ag., M.Pd.I','Partai Persatuan Pembangunan','TPS 04','GunungKeling','Cigugur','Kuningan',0),
('RAHWAN SANUSI, S.Ag., M.Pd.I','Partai Persatuan Pembangunan','TPS 05','GunungKeling','Cigugur','Kuningan',0),
('PARTAI SOLIDARITAS INDONESIA','Partai Solidaritas Indonesia','TPS 01','GunungKeling','Cigugur','Kuningan',2),
('PARTAI SOLIDARITAS INDONESIA','Partai Solidaritas Indonesia','TPS 02','GunungKeling','Cigugur','Kuningan',0),
('PARTAI SOLIDARITAS INDONESIA','Partai Solidaritas Indonesia','TPS 03','GunungKeling','Cigugur','Kuningan',0),
('PARTAI SOLIDARITAS INDONESIA','Partai Solidaritas Indonesia','TPS 04','GunungKeling','Cigugur','Kuningan',1),
('PARTAI SOLIDARITAS INDONESIA','Partai Solidaritas Indonesia','TPS 05','GunungKeling','Cigugur','Kuningan',1),
('PARTAI AMANAT NASIONAL','Partai Amanat Nasional','TPS 01','GunungKeling','Cigugur','Kuningan',0),
('PARTAI AMANAT NASIONAL','Partai Amanat Nasional','TPS 02','GunungKeling','Cigugur','Kuningan',1),
('PARTAI AMANAT NASIONAL','Partai Amanat Nasional','TPS 03','GunungKeling','Cigugur','Kuningan',4),
('PARTAI AMANAT NASIONAL','Partai Amanat Nasional','TPS 04','GunungKeling','Cigugur','Kuningan',7),
('PARTAI AMANAT NASIONAL','Partai Amanat Nasional','TPS 05','GunungKeling','Cigugur','Kuningan',0),
('Ir. H. HERRY DERMAWAN','Partai Amanat Nasional','TPS 01','GunungKeling','Cigugur','Kuningan',0),
('Ir. H. HERRY DERMAWAN','Partai Amanat Nasional','TPS 02','GunungKeling','Cigugur','Kuningan',1),
('Ir. H. HERRY DERMAWAN','Partai Amanat Nasional','TPS 03','GunungKeling','Cigugur','Kuningan',3),
('Ir. H. HERRY DERMAWAN','Partai Amanat Nasional','TPS 04','GunungKeling','Cigugur','Kuningan',2),
('Ir. H. HERRY DERMAWAN','Partai Amanat Nasional','TPS 05','GunungKeling','Cigugur','Kuningan',0),
('SALIMUN SIREMA','Partai Amanat Nasional','TPS 01','GunungKeling','Cigugur','Kuningan',0),
('SALIMUN SIREMA','Partai Amanat Nasional','TPS 02','GunungKeling','Cigugur','Kuningan',0),
('SALIMUN SIREMA','Partai Amanat Nasional','TPS 03','GunungKeling','Cigugur','Kuningan',0),
('SALIMUN SIREMA','Partai Amanat Nasional','TPS 04','GunungKeling','Cigugur','Kuningan',0),
('SALIMUN SIREMA','Partai Amanat Nasional','TPS 05','GunungKeling','Cigugur','Kuningan',0),
('DEWI SITI NURJANAH, S.Pd','Partai Amanat Nasional','TPS 01','GunungKeling','Cigugur','Kuningan',0),
('DEWI SITI NURJANAH, S.Pd','Partai Amanat Nasional','TPS 02','GunungKeling','Cigugur','Kuningan',0),
('DEWI SITI NURJANAH, S.Pd','Partai Amanat Nasional','TPS 03','GunungKeling','Cigugur','Kuningan',0),
('DEWI SITI NURJANAH, S.Pd','Partai Amanat Nasional','TPS 04','GunungKeling','Cigugur','Kuningan',0),
('DEWI SITI NURJANAH, S.Pd','Partai Amanat Nasional','TPS 05','GunungKeling','Cigugur','Kuningan',0),
('H. MAMAN WIJAYA','Partai Amanat Nasional','TPS 01','GunungKeling','Cigugur','Kuningan',2),
('H. MAMAN WIJAYA','Partai Amanat Nasional','TPS 02','GunungKeling','Cigugur','Kuningan',0),
('H. MAMAN WIJAYA','Partai Amanat Nasional','TPS 03','GunungKeling','Cigugur','Kuningan',1),
('H. MAMAN WIJAYA','Partai Amanat Nasional','TPS 04','GunungKeling','Cigugur','Kuningan',0),
('H. MAMAN WIJAYA','Partai Amanat Nasional','TPS 05','GunungKeling','Cigugur','Kuningan',0),
('NENDEN DIANA. S.E','Partai Amanat Nasional','TPS 01','GunungKeling','Cigugur','Kuningan',0),
('NENDEN DIANA. S.E','Partai Amanat Nasional','TPS 02','GunungKeling','Cigugur','Kuningan',0),
('NENDEN DIANA. S.E','Partai Amanat Nasional','TPS 03','GunungKeling','Cigugur','Kuningan',1),
('NENDEN DIANA. S.E','Partai Amanat Nasional','TPS 04','GunungKeling','Cigugur','Kuningan',0),
('NENDEN DIANA. S.E','Partai Amanat Nasional','TPS 05','GunungKeling','Cigugur','Kuningan',0),
('IMAS ROHMAYANTI','Partai Amanat Nasional','TPS 01','GunungKeling','Cigugur','Kuningan',0),
('IMAS ROHMAYANTI','Partai Amanat Nasional','TPS 02','GunungKeling','Cigugur','Kuningan',0),
('IMAS ROHMAYANTI','Partai Amanat Nasional','TPS 03','GunungKeling','Cigugur','Kuningan',0),
('IMAS ROHMAYANTI','Partai Amanat Nasional','TPS 04','GunungKeling','Cigugur','Kuningan',0),
('IMAS ROHMAYANTI','Partai Amanat Nasional','TPS 05','GunungKeling','Cigugur','Kuningan',0),
('LINA APRIANI, S.S','Partai Amanat Nasional','TPS 01','GunungKeling','Cigugur','Kuningan',0),
('LINA APRIANI, S.S','Partai Amanat Nasional','TPS 02','GunungKeling','Cigugur','Kuningan',0),
('LINA APRIANI, S.S','Partai Amanat Nasional','TPS 03','GunungKeling','Cigugur','Kuningan',1),
('LINA APRIANI, S.S','Partai Amanat Nasional','TPS 04','GunungKeling','Cigugur','Kuningan',1),
('LINA APRIANI, S.S','Partai Amanat Nasional','TPS 05','GunungKeling','Cigugur','Kuningan',1),
('MUHAMAD AGUSTIANA','Partai Amanat Nasional','TPS 01','GunungKeling','Cigugur','Kuningan',0),
('MUHAMAD AGUSTIANA','Partai Amanat Nasional','TPS 02','GunungKeling','Cigugur','Kuningan',0),
('MUHAMAD AGUSTIANA','Partai Amanat Nasional','TPS 03','GunungKeling','Cigugur','Kuningan',0),
('MUHAMAD AGUSTIANA','Partai Amanat Nasional','TPS 04','GunungKeling','Cigugur','Kuningan',0),
('MUHAMAD AGUSTIANA','Partai Amanat Nasional','TPS 05','GunungKeling','Cigugur','Kuningan',0),
('PARTAI HATI NURANI RAKYAT','Partai Hati Nurani Rakyat','TPS 01','GunungKeling','Cigugur','Kuningan',0),
('PARTAI HATI NURANI RAKYAT','Partai Hati Nurani Rakyat','TPS 02','GunungKeling','Cigugur','Kuningan',0),
('PARTAI HATI NURANI RAKYAT','Partai Hati Nurani Rakyat','TPS 03','GunungKeling','Cigugur','Kuningan',0),
('PARTAI HATI NURANI RAKYAT','Partai Hati Nurani Rakyat','TPS 04','GunungKeling','Cigugur','Kuningan',1),
('PARTAI HATI NURANI RAKYAT','Partai Hati Nurani Rakyat','TPS 05','GunungKeling','Cigugur','Kuningan',0),
('H. TITO AHMAD SETRA','Partai Hati Nurani Rakyat','TPS 01','GunungKeling','Cigugur','Kuningan',0),
('H. TITO AHMAD SETRA','Partai Hati Nurani Rakyat','TPS 02','GunungKeling','Cigugur','Kuningan',0),
('H. TITO AHMAD SETRA','Partai Hati Nurani Rakyat','TPS 03','GunungKeling','Cigugur','Kuningan',0),
('H. TITO AHMAD SETRA','Partai Hati Nurani Rakyat','TPS 04','GunungKeling','Cigugur','Kuningan',0),
('H. TITO AHMAD SETRA','Partai Hati Nurani Rakyat','TPS 05','GunungKeling','Cigugur','Kuningan',0),
('Drs. EDI JUNAEDI','Partai Hati Nurani Rakyat','TPS 01','GunungKeling','Cigugur','Kuningan',0),
('Drs. EDI JUNAEDI','Partai Hati Nurani Rakyat','TPS 02','GunungKeling','Cigugur','Kuningan',0),
('Drs. EDI JUNAEDI','Partai Hati Nurani Rakyat','TPS 03','GunungKeling','Cigugur','Kuningan',0),
('Drs. EDI JUNAEDI','Partai Hati Nurani Rakyat','TPS 04','GunungKeling','Cigugur','Kuningan',0),
('Drs. EDI JUNAEDI','Partai Hati Nurani Rakyat','TPS 05','GunungKeling','Cigugur','Kuningan',1),
('SITI WARTINI','Partai Hati Nurani Rakyat','TPS 01','GunungKeling','Cigugur','Kuningan',0),
('SITI WARTINI','Partai Hati Nurani Rakyat','TPS 02','GunungKeling','Cigugur','Kuningan',0),
('SITI WARTINI','Partai Hati Nurani Rakyat','TPS 03','GunungKeling','Cigugur','Kuningan',0),
('SITI WARTINI','Partai Hati Nurani Rakyat','TPS 04','GunungKeling','Cigugur','Kuningan',0),
('SITI WARTINI','Partai Hati Nurani Rakyat','TPS 05','GunungKeling','Cigugur','Kuningan',0),
('YAYA HERYANA HANS','Partai Hati Nurani Rakyat','TPS 01','GunungKeling','Cigugur','Kuningan',0),
('YAYA HERYANA HANS','Partai Hati Nurani Rakyat','TPS 02','GunungKeling','Cigugur','Kuningan',0),
('YAYA HERYANA HANS','Partai Hati Nurani Rakyat','TPS 03','GunungKeling','Cigugur','Kuningan',0),
('YAYA HERYANA HANS','Partai Hati Nurani Rakyat','TPS 04','GunungKeling','Cigugur','Kuningan',0),
('YAYA HERYANA HANS','Partai Hati Nurani Rakyat','TPS 05','GunungKeling','Cigugur','Kuningan',0),
('GHINA NISRINA FIRDAUS KUSMAYADI','Partai Hati Nurani Rakyat','TPS 01','GunungKeling','Cigugur','Kuningan',0),
('GHINA NISRINA FIRDAUS KUSMAYADI','Partai Hati Nurani Rakyat','TPS 02','GunungKeling','Cigugur','Kuningan',0),
('GHINA NISRINA FIRDAUS KUSMAYADI','Partai Hati Nurani Rakyat','TPS 03','GunungKeling','Cigugur','Kuningan',0),
('GHINA NISRINA FIRDAUS KUSMAYADI','Partai Hati Nurani Rakyat','TPS 04','GunungKeling','Cigugur','Kuningan',0),
('GHINA NISRINA FIRDAUS KUSMAYADI','Partai Hati Nurani Rakyat','TPS 05','GunungKeling','Cigugur','Kuningan',0),
('PARTAI DEMOKRAT','Partai Demokrat','TPS 01','GunungKeling','Cigugur','Kuningan',0),
('PARTAI DEMOKRAT','Partai Demokrat','TPS 02','GunungKeling','Cigugur','Kuningan',5),
('PARTAI DEMOKRAT','Partai Demokrat','TPS 03','GunungKeling','Cigugur','Kuningan',5),
('PARTAI DEMOKRAT','Partai Demokrat','TPS 04','GunungKeling','Cigugur','Kuningan',10),
('PARTAI DEMOKRAT','Partai Demokrat','TPS 05','GunungKeling','Cigugur','Kuningan',4),
('IRWAN KUSANDIANTORO','Partai Demokrat','TPS 01','GunungKeling','Cigugur','Kuningan',0),
('IRWAN KUSANDIANTORO','Partai Demokrat','TPS 02','GunungKeling','Cigugur','Kuningan',1),
('IRWAN KUSANDIANTORO','Partai Demokrat','TPS 03','GunungKeling','Cigugur','Kuningan',1),
('IRWAN KUSANDIANTORO','Partai Demokrat','TPS 04','GunungKeling','Cigugur','Kuningan',0),
('IRWAN KUSANDIANTORO','Partai Demokrat','TPS 05','GunungKeling','Cigugur','Kuningan',0),
('BUDI SUTRISNO, S.E., M.Si','Partai Demokrat','TPS 01','GunungKeling','Cigugur','Kuningan',0),
('BUDI SUTRISNO, S.E., M.Si','Partai Demokrat','TPS 02','GunungKeling','Cigugur','Kuningan',0),
('BUDI SUTRISNO, S.E., M.Si','Partai Demokrat','TPS 03','GunungKeling','Cigugur','Kuningan',1),
('BUDI SUTRISNO, S.E., M.Si','Partai Demokrat','TPS 04','GunungKeling','Cigugur','Kuningan',3),
('BUDI SUTRISNO, S.E., M.Si','Partai Demokrat','TPS 05','GunungKeling','Cigugur','Kuningan',2),
('IMAS SURYATI','Partai Demokrat','TPS 01','GunungKeling','Cigugur','Kuningan',1),
('IMAS SURYATI','Partai Demokrat','TPS 02','GunungKeling','Cigugur','Kuningan',0),
('IMAS SURYATI','Partai Demokrat','TPS 03','GunungKeling','Cigugur','Kuningan',0),
('IMAS SURYATI','Partai Demokrat','TPS 04','GunungKeling','Cigugur','Kuningan',0),
('IMAS SURYATI','Partai Demokrat','TPS 05','GunungKeling','Cigugur','Kuningan',0),
('YOSA OCTORA SANTONO, S.Si., M.M','Partai Demokrat','TPS 01','GunungKeling','Cigugur','Kuningan',1),
('YOSA OCTORA SANTONO, S.Si., M.M','Partai Demokrat','TPS 02','GunungKeling','Cigugur','Kuningan',6),
('YOSA OCTORA SANTONO, S.Si., M.M','Partai Demokrat','TPS 03','GunungKeling','Cigugur','Kuningan',2),
('YOSA OCTORA SANTONO, S.Si., M.M','Partai Demokrat','TPS 04','GunungKeling','Cigugur','Kuningan',2),
('YOSA OCTORA SANTONO, S.Si., M.M','Partai Demokrat','TPS 05','GunungKeling','Cigugur','Kuningan',3),
('H. ANJAR ASMARA, S.H','Partai Demokrat','TPS 01','GunungKeling','Cigugur','Kuningan',0),
('H. ANJAR ASMARA, S.H','Partai Demokrat','TPS 02','GunungKeling','Cigugur','Kuningan',0),
('H. ANJAR ASMARA, S.H','Partai Demokrat','TPS 03','GunungKeling','Cigugur','Kuningan',0),
('H. ANJAR ASMARA, S.H','Partai Demokrat','TPS 04','GunungKeling','Cigugur','Kuningan',1),
('H. ANJAR ASMARA, S.H','Partai Demokrat','TPS 05','GunungKeling','Cigugur','Kuningan',0),
('IMAS SANTIKA','Partai Demokrat','TPS 01','GunungKeling','Cigugur','Kuningan',0),
('IMAS SANTIKA','Partai Demokrat','TPS 02','GunungKeling','Cigugur','Kuningan',0),
('IMAS SANTIKA','Partai Demokrat','TPS 03','GunungKeling','Cigugur','Kuningan',1),
('IMAS SANTIKA','Partai Demokrat','TPS 04','GunungKeling','Cigugur','Kuningan',0),
('IMAS SANTIKA','Partai Demokrat','TPS 05','GunungKeling','Cigugur','Kuningan',0),
('Ir. H. USWARNO, M.Si','Partai Demokrat','TPS 01','GunungKeling','Cigugur','Kuningan',0),
('Ir. H. USWARNO, M.Si','Partai Demokrat','TPS 02','GunungKeling','Cigugur','Kuningan',0),
('Ir. H. USWARNO, M.Si','Partai Demokrat','TPS 03','GunungKeling','Cigugur','Kuningan',0),
('Ir. H. USWARNO, M.Si','Partai Demokrat','TPS 04','GunungKeling','Cigugur','Kuningan',0),
('Ir. H. USWARNO, M.Si','Partai Demokrat','TPS 05','GunungKeling','Cigugur','Kuningan',0),
('NITA MASRIAH','Partai Demokrat','TPS 01','GunungKeling','Cigugur','Kuningan',1),
('NITA MASRIAH','Partai Demokrat','TPS 02','GunungKeling','Cigugur','Kuningan',0),
('NITA MASRIAH','Partai Demokrat','TPS 03','GunungKeling','Cigugur','Kuningan',0),
('NITA MASRIAH','Partai Demokrat','TPS 04','GunungKeling','Cigugur','Kuningan',0),
('NITA MASRIAH','Partai Demokrat','TPS 05','GunungKeling','Cigugur','Kuningan',0),
('PARTAI BULAN BINTANG','Partai Bulan Bintang','TPS 01','GunungKeling','Cigugur','Kuningan',0),
('PARTAI BULAN BINTANG','Partai Bulan Bintang','TPS 02','GunungKeling','Cigugur','Kuningan',0),
('PARTAI BULAN BINTANG','Partai Bulan Bintang','TPS 03','GunungKeling','Cigugur','Kuningan',0),
('PARTAI BULAN BINTANG','Partai Bulan Bintang','TPS 04','GunungKeling','Cigugur','Kuningan',0),
('PARTAI BULAN BINTANG','Partai Bulan Bintang','TPS 05','GunungKeling','Cigugur','Kuningan',1),
('SUPENA, S.E., Akt','Partai Bulan Bintang','TPS 01','GunungKeling','Cigugur','Kuningan',0),
('SUPENA, S.E., Akt','Partai Bulan Bintang','TPS 02','GunungKeling','Cigugur','Kuningan',1),
('SUPENA, S.E., Akt','Partai Bulan Bintang','TPS 03','GunungKeling','Cigugur','Kuningan',0),
('SUPENA, S.E., Akt','Partai Bulan Bintang','TPS 04','GunungKeling','Cigugur','Kuningan',0),
('SUPENA, S.E., Akt','Partai Bulan Bintang','TPS 05','GunungKeling','Cigugur','Kuningan',0),
('MOH. IKHSAN KURNIA, S.Sos','Partai Bulan Bintang','TPS 01','GunungKeling','Cigugur','Kuningan',0),
('MOH. IKHSAN KURNIA, S.Sos','Partai Bulan Bintang','TPS 02','GunungKeling','Cigugur','Kuningan',0),
('MOH. IKHSAN KURNIA, S.Sos','Partai Bulan Bintang','TPS 03','GunungKeling','Cigugur','Kuningan',0),
('MOH. IKHSAN KURNIA, S.Sos','Partai Bulan Bintang','TPS 04','GunungKeling','Cigugur','Kuningan',0),
('MOH. IKHSAN KURNIA, S.Sos','Partai Bulan Bintang','TPS 05','GunungKeling','Cigugur','Kuningan',0),
('NEUIS MARPUAH, M.M.Pd','Partai Bulan Bintang','TPS 01','GunungKeling','Cigugur','Kuningan',0),
('NEUIS MARPUAH, M.M.Pd','Partai Bulan Bintang','TPS 02','GunungKeling','Cigugur','Kuningan',0),
('NEUIS MARPUAH, M.M.Pd','Partai Bulan Bintang','TPS 03','GunungKeling','Cigugur','Kuningan',0),
('NEUIS MARPUAH, M.M.Pd','Partai Bulan Bintang','TPS 04','GunungKeling','Cigugur','Kuningan',0),
('NEUIS MARPUAH, M.M.Pd','Partai Bulan Bintang','TPS 05','GunungKeling','Cigugur','Kuningan',0),
('Drs. ABDUL BARI','Partai Bulan Bintang','TPS 01','GunungKeling','Cigugur','Kuningan',0),
('Drs. ABDUL BARI','Partai Bulan Bintang','TPS 02','GunungKeling','Cigugur','Kuningan',0),
('Drs. ABDUL BARI','Partai Bulan Bintang','TPS 03','GunungKeling','Cigugur','Kuningan',0),
('Drs. ABDUL BARI','Partai Bulan Bintang','TPS 04','GunungKeling','Cigugur','Kuningan',1),
('Drs. ABDUL BARI','Partai Bulan Bintang','TPS 05','GunungKeling','Cigugur','Kuningan',0),
('WAWANG HUSNAWATI','Partai Bulan Bintang','TPS 01','GunungKeling','Cigugur','Kuningan',0),
('WAWANG HUSNAWATI','Partai Bulan Bintang','TPS 02','GunungKeling','Cigugur','Kuningan',0),
('WAWANG HUSNAWATI','Partai Bulan Bintang','TPS 03','GunungKeling','Cigugur','Kuningan',0),
('WAWANG HUSNAWATI','Partai Bulan Bintang','TPS 04','GunungKeling','Cigugur','Kuningan',0),
('WAWANG HUSNAWATI','Partai Bulan Bintang','TPS 05','GunungKeling','Cigugur','Kuningan',0),
('PARTAI KEADILAN DAN PERSATUAN INDONESIA','Partai Keadilan dan Persatuan Indonesia','TPS 01','GunungKeling','Cigugur','Kuningan',0),
('PARTAI KEADILAN DAN PERSATUAN INDONESIA','Partai Keadilan dan Persatuan Indonesia','TPS 02','GunungKeling','Cigugur','Kuningan',0),
('PARTAI KEADILAN DAN PERSATUAN INDONESIA','Partai Keadilan dan Persatuan Indonesia','TPS 03','GunungKeling','Cigugur','Kuningan',0),
('PARTAI KEADILAN DAN PERSATUAN INDONESIA','Partai Keadilan dan Persatuan Indonesia','TPS 04','GunungKeling','Cigugur','Kuningan',0),
('PARTAI KEADILAN DAN PERSATUAN INDONESIA','Partai Keadilan dan Persatuan Indonesia','TPS 05','GunungKeling','Cigugur','Kuningan',0),
('Drs. H. TUBAGUS KUN MAULAWARMAN, S.H., M.Si','Partai Keadilan dan Persatuan Indonesia','TPS 01','GunungKeling','Cigugur','Kuningan',0),
('Drs. H. TUBAGUS KUN MAULAWARMAN, S.H., M.Si','Partai Keadilan dan Persatuan Indonesia','TPS 02','GunungKeling','Cigugur','Kuningan',0),
('Drs. H. TUBAGUS KUN MAULAWARMAN, S.H., M.Si','Partai Keadilan dan Persatuan Indonesia','TPS 03','GunungKeling','Cigugur','Kuningan',0),
('Drs. H. TUBAGUS KUN MAULAWARMAN, S.H., M.Si','Partai Keadilan dan Persatuan Indonesia','TPS 04','GunungKeling','Cigugur','Kuningan',0),
('Drs. H. TUBAGUS KUN MAULAWARMAN, S.H., M.Si','Partai Keadilan dan Persatuan Indonesia','TPS 05','GunungKeling','Cigugur','Kuningan',0),
('NOVIYANI','Partai Keadilan dan Persatuan Indonesia','TPS 01','GunungKeling','Cigugur','Kuningan',0),
('NOVIYANI','Partai Keadilan dan Persatuan Indonesia','TPS 02','GunungKeling','Cigugur','Kuningan',0),
('NOVIYANI','Partai Keadilan dan Persatuan Indonesia','TPS 03','GunungKeling','Cigugur','Kuningan',0),
('NOVIYANI','Partai Keadilan dan Persatuan Indonesia','TPS 04','GunungKeling','Cigugur','Kuningan',0),
('NOVIYANI','Partai Keadilan dan Persatuan Indonesia','TPS 05','GunungKeling','Cigugur','Kuningan',0);