INSERT INTO dprs (nama,partai,tps,desa,kecamatan,kabupaten,total) VALUES 
('Partai Kebangkitan Bangsa','Partai Kebangkitan Bangsa','TPS 01','Kedungarum','Kuningan','Kuningan',3),
('Partai Kebangkitan Bangsa','Partai Kebangkitan Bangsa','TPS 02','Kedungarum','Kuningan','Kuningan',5),
('Partai Kebangkitan Bangsa','Partai Kebangkitan Bangsa','TPS 03','Kedungarum','Kuningan','Kuningan',1),
('Partai Kebangkitan Bangsa','Partai Kebangkitan Bangsa','TPS 04','Kedungarum','Kuningan','Kuningan',2),
('Partai Kebangkitan Bangsa','Partai Kebangkitan Bangsa','TPS 05','Kedungarum','Kuningan','Kuningan',2),
('Partai Kebangkitan Bangsa','Partai Kebangkitan Bangsa','TPS 06','Kedungarum','Kuningan','Kuningan',1),
('Partai Kebangkitan Bangsa','Partai Kebangkitan Bangsa','TPS 07','Kedungarum','Kuningan','Kuningan',7),
('Partai Kebangkitan Bangsa','Partai Kebangkitan Bangsa','TPS 08','Kedungarum','Kuningan','Kuningan',1),
('H YANUAR PRIHATIN, MSI','Partai Kebangkitan Bangsa','TPS 01','Kedungarum','Kuningan','Kuningan',2),
('H YANUAR PRIHATIN, MSI','Partai Kebangkitan Bangsa','TPS 02','Kedungarum','Kuningan','Kuningan',2),
('H YANUAR PRIHATIN, MSI','Partai Kebangkitan Bangsa','TPS 03','Kedungarum','Kuningan','Kuningan',1),
('H YANUAR PRIHATIN, MSI','Partai Kebangkitan Bangsa','TPS 04','Kedungarum','Kuningan','Kuningan',1),
('H YANUAR PRIHATIN, MSI','Partai Kebangkitan Bangsa','TPS 05','Kedungarum','Kuningan','Kuningan',2),
('H YANUAR PRIHATIN, MSI','Partai Kebangkitan Bangsa','TPS 06','Kedungarum','Kuningan','Kuningan',2),
('H YANUAR PRIHATIN, MSI','Partai Kebangkitan Bangsa','TPS 07','Kedungarum','Kuningan','Kuningan',3),
('H YANUAR PRIHATIN, MSI','Partai Kebangkitan Bangsa','TPS 08','Kedungarum','Kuningan','Kuningan',1),
('RINA SAADAH, LC, MSI','Partai Kebangkitan Bangsa','TPS 01','Kedungarum','Kuningan','Kuningan',0),
('RINA SAADAH, LC, MSI','Partai Kebangkitan Bangsa','TPS 02','Kedungarum','Kuningan','Kuningan',1),
('RINA SAADAH, LC, MSI','Partai Kebangkitan Bangsa','TPS 03','Kedungarum','Kuningan','Kuningan',1),
('RINA SAADAH, LC, MSI','Partai Kebangkitan Bangsa','TPS 04','Kedungarum','Kuningan','Kuningan',0),
('RINA SAADAH, LC, MSI','Partai Kebangkitan Bangsa','TPS 05','Kedungarum','Kuningan','Kuningan',0),
('RINA SAADAH, LC, MSI','Partai Kebangkitan Bangsa','TPS 06','Kedungarum','Kuningan','Kuningan',0),
('RINA SAADAH, LC, MSI','Partai Kebangkitan Bangsa','TPS 07','Kedungarum','Kuningan','Kuningan',1),
('RINA SAADAH, LC, MSI','Partai Kebangkitan Bangsa','TPS 08','Kedungarum','Kuningan','Kuningan',1),
('AHMAD IRFAN ALAWI','Partai Kebangkitan Bangsa','TPS 01','Kedungarum','Kuningan','Kuningan',0),
('AHMAD IRFAN ALAWI','Partai Kebangkitan Bangsa','TPS 02','Kedungarum','Kuningan','Kuningan',1),
('AHMAD IRFAN ALAWI','Partai Kebangkitan Bangsa','TPS 03','Kedungarum','Kuningan','Kuningan',0),
('AHMAD IRFAN ALAWI','Partai Kebangkitan Bangsa','TPS 04','Kedungarum','Kuningan','Kuningan',0),
('AHMAD IRFAN ALAWI','Partai Kebangkitan Bangsa','TPS 05','Kedungarum','Kuningan','Kuningan',0),
('AHMAD IRFAN ALAWI','Partai Kebangkitan Bangsa','TPS 06','Kedungarum','Kuningan','Kuningan',0),
('AHMAD IRFAN ALAWI','Partai Kebangkitan Bangsa','TPS 07','Kedungarum','Kuningan','Kuningan',1),
('AHMAD IRFAN ALAWI','Partai Kebangkitan Bangsa','TPS 08','Kedungarum','Kuningan','Kuningan',0),
('DRG. ENDAH FUTIHATUL FAJRIYAH','Partai Kebangkitan Bangsa','TPS 01','Kedungarum','Kuningan','Kuningan',0),
('DRG. ENDAH FUTIHATUL FAJRIYAH','Partai Kebangkitan Bangsa','TPS 02','Kedungarum','Kuningan','Kuningan',0),
('DRG. ENDAH FUTIHATUL FAJRIYAH','Partai Kebangkitan Bangsa','TPS 03','Kedungarum','Kuningan','Kuningan',0),
('DRG. ENDAH FUTIHATUL FAJRIYAH','Partai Kebangkitan Bangsa','TPS 04','Kedungarum','Kuningan','Kuningan',0),
('DRG. ENDAH FUTIHATUL FAJRIYAH','Partai Kebangkitan Bangsa','TPS 05','Kedungarum','Kuningan','Kuningan',0),
('DRG. ENDAH FUTIHATUL FAJRIYAH','Partai Kebangkitan Bangsa','TPS 06','Kedungarum','Kuningan','Kuningan',0),
('DRG. ENDAH FUTIHATUL FAJRIYAH','Partai Kebangkitan Bangsa','TPS 07','Kedungarum','Kuningan','Kuningan',0),
('DRG. ENDAH FUTIHATUL FAJRIYAH','Partai Kebangkitan Bangsa','TPS 08','Kedungarum','Kuningan','Kuningan',0),
('DEDE IIN SOBIRIN, SH','Partai Kebangkitan Bangsa','TPS 01','Kedungarum','Kuningan','Kuningan',0),
('DEDE IIN SOBIRIN, SH','Partai Kebangkitan Bangsa','TPS 02','Kedungarum','Kuningan','Kuningan',0),
('DEDE IIN SOBIRIN, SH','Partai Kebangkitan Bangsa','TPS 03','Kedungarum','Kuningan','Kuningan',0),
('DEDE IIN SOBIRIN, SH','Partai Kebangkitan Bangsa','TPS 04','Kedungarum','Kuningan','Kuningan',0),
('DEDE IIN SOBIRIN, SH','Partai Kebangkitan Bangsa','TPS 05','Kedungarum','Kuningan','Kuningan',0),
('DEDE IIN SOBIRIN, SH','Partai Kebangkitan Bangsa','TPS 06','Kedungarum','Kuningan','Kuningan',0),
('DEDE IIN SOBIRIN, SH','Partai Kebangkitan Bangsa','TPS 07','Kedungarum','Kuningan','Kuningan',0),
('DEDE IIN SOBIRIN, SH','Partai Kebangkitan Bangsa','TPS 08','Kedungarum','Kuningan','Kuningan',0),
('ASEP IRFAN','Partai Kebangkitan Bangsa','TPS 01','Kedungarum','Kuningan','Kuningan',0),
('ASEP IRFAN','Partai Kebangkitan Bangsa','TPS 02','Kedungarum','Kuningan','Kuningan',0),
('ASEP IRFAN','Partai Kebangkitan Bangsa','TPS 03','Kedungarum','Kuningan','Kuningan',1),
('ASEP IRFAN','Partai Kebangkitan Bangsa','TPS 04','Kedungarum','Kuningan','Kuningan',0),
('ASEP IRFAN','Partai Kebangkitan Bangsa','TPS 05','Kedungarum','Kuningan','Kuningan',0),
('ASEP IRFAN','Partai Kebangkitan Bangsa','TPS 06','Kedungarum','Kuningan','Kuningan',0),
('ASEP IRFAN','Partai Kebangkitan Bangsa','TPS 07','Kedungarum','Kuningan','Kuningan',0),
('ASEP IRFAN','Partai Kebangkitan Bangsa','TPS 08','Kedungarum','Kuningan','Kuningan',0),
('EVA FITRIAH','Partai Kebangkitan Bangsa','TPS 01','Kedungarum','Kuningan','Kuningan',0),
('EVA FITRIAH','Partai Kebangkitan Bangsa','TPS 02','Kedungarum','Kuningan','Kuningan',0),
('EVA FITRIAH','Partai Kebangkitan Bangsa','TPS 03','Kedungarum','Kuningan','Kuningan',0),
('EVA FITRIAH','Partai Kebangkitan Bangsa','TPS 04','Kedungarum','Kuningan','Kuningan',0),
('EVA FITRIAH','Partai Kebangkitan Bangsa','TPS 05','Kedungarum','Kuningan','Kuningan',0),
('EVA FITRIAH','Partai Kebangkitan Bangsa','TPS 06','Kedungarum','Kuningan','Kuningan',1),
('EVA FITRIAH','Partai Kebangkitan Bangsa','TPS 07','Kedungarum','Kuningan','Kuningan',0),
('EVA FITRIAH','Partai Kebangkitan Bangsa','TPS 08','Kedungarum','Kuningan','Kuningan',0),
('Partai Gerakan Indonesia Raya','Partai Gerakan Indonesia Raya','TPS 01','Kedungarum','Kuningan','Kuningan',6),
('Partai Gerakan Indonesia Raya','Partai Gerakan Indonesia Raya','TPS 02','Kedungarum','Kuningan','Kuningan',9),
('Partai Gerakan Indonesia Raya','Partai Gerakan Indonesia Raya','TPS 03','Kedungarum','Kuningan','Kuningan',11),
('Partai Gerakan Indonesia Raya','Partai Gerakan Indonesia Raya','TPS 04','Kedungarum','Kuningan','Kuningan',19),
('Partai Gerakan Indonesia Raya','Partai Gerakan Indonesia Raya','TPS 05','Kedungarum','Kuningan','Kuningan',24),
('Partai Gerakan Indonesia Raya','Partai Gerakan Indonesia Raya','TPS 06','Kedungarum','Kuningan','Kuningan',10),
('Partai Gerakan Indonesia Raya','Partai Gerakan Indonesia Raya','TPS 07','Kedungarum','Kuningan','Kuningan',14),
('Partai Gerakan Indonesia Raya','Partai Gerakan Indonesia Raya','TPS 08','Kedungarum','Kuningan','Kuningan',7),
('ARDHYA PRATIWI S, SE','Partai Gerakan Indonesia Raya','TPS 01','Kedungarum','Kuningan','Kuningan',10),
('ARDHYA PRATIWI S, SE','Partai Gerakan Indonesia Raya','TPS 02','Kedungarum','Kuningan','Kuningan',8),
('ARDHYA PRATIWI S, SE','Partai Gerakan Indonesia Raya','TPS 03','Kedungarum','Kuningan','Kuningan',11),
('ARDHYA PRATIWI S, SE','Partai Gerakan Indonesia Raya','TPS 04','Kedungarum','Kuningan','Kuningan',12),
('ARDHYA PRATIWI S, SE','Partai Gerakan Indonesia Raya','TPS 05','Kedungarum','Kuningan','Kuningan',7),
('ARDHYA PRATIWI S, SE','Partai Gerakan Indonesia Raya','TPS 06','Kedungarum','Kuningan','Kuningan',3),
('ARDHYA PRATIWI S, SE','Partai Gerakan Indonesia Raya','TPS 07','Kedungarum','Kuningan','Kuningan',4),
('ARDHYA PRATIWI S, SE','Partai Gerakan Indonesia Raya','TPS 08','Kedungarum','Kuningan','Kuningan',6),
('DADAY HUDAYA, SH., MH','Partai Gerakan Indonesia Raya','TPS 01','Kedungarum','Kuningan','Kuningan',3),
('DADAY HUDAYA, SH., MH','Partai Gerakan Indonesia Raya','TPS 02','Kedungarum','Kuningan','Kuningan',3),
('DADAY HUDAYA, SH., MH','Partai Gerakan Indonesia Raya','TPS 03','Kedungarum','Kuningan','Kuningan',3),
('DADAY HUDAYA, SH., MH','Partai Gerakan Indonesia Raya','TPS 04','Kedungarum','Kuningan','Kuningan',4),
('DADAY HUDAYA, SH., MH','Partai Gerakan Indonesia Raya','TPS 05','Kedungarum','Kuningan','Kuningan',2),
('DADAY HUDAYA, SH., MH','Partai Gerakan Indonesia Raya','TPS 06','Kedungarum','Kuningan','Kuningan',3),
('DADAY HUDAYA, SH., MH','Partai Gerakan Indonesia Raya','TPS 07','Kedungarum','Kuningan','Kuningan',1),
('DADAY HUDAYA, SH., MH','Partai Gerakan Indonesia Raya','TPS 08','Kedungarum','Kuningan','Kuningan',2),
('AHMAD BAHTIAR SEBAYANG, SE','Partai Gerakan Indonesia Raya','TPS 01','Kedungarum','Kuningan','Kuningan',2),
('AHMAD BAHTIAR SEBAYANG, SE','Partai Gerakan Indonesia Raya','TPS 02','Kedungarum','Kuningan','Kuningan',0),
('AHMAD BAHTIAR SEBAYANG, SE','Partai Gerakan Indonesia Raya','TPS 03','Kedungarum','Kuningan','Kuningan',3),
('AHMAD BAHTIAR SEBAYANG, SE','Partai Gerakan Indonesia Raya','TPS 04','Kedungarum','Kuningan','Kuningan',1),
('AHMAD BAHTIAR SEBAYANG, SE','Partai Gerakan Indonesia Raya','TPS 05','Kedungarum','Kuningan','Kuningan',4),
('AHMAD BAHTIAR SEBAYANG, SE','Partai Gerakan Indonesia Raya','TPS 06','Kedungarum','Kuningan','Kuningan',2),
('AHMAD BAHTIAR SEBAYANG, SE','Partai Gerakan Indonesia Raya','TPS 07','Kedungarum','Kuningan','Kuningan',0),
('AHMAD BAHTIAR SEBAYANG, SE','Partai Gerakan Indonesia Raya','TPS 08','Kedungarum','Kuningan','Kuningan',0),
('RUSMIN EFFENDY, SH, MH','Partai Gerakan Indonesia Raya','TPS 01','Kedungarum','Kuningan','Kuningan',0),
('RUSMIN EFFENDY, SH, MH','Partai Gerakan Indonesia Raya','TPS 02','Kedungarum','Kuningan','Kuningan',2),
('RUSMIN EFFENDY, SH, MH','Partai Gerakan Indonesia Raya','TPS 03','Kedungarum','Kuningan','Kuningan',1),
('RUSMIN EFFENDY, SH, MH','Partai Gerakan Indonesia Raya','TPS 04','Kedungarum','Kuningan','Kuningan',1),
('RUSMIN EFFENDY, SH, MH','Partai Gerakan Indonesia Raya','TPS 05','Kedungarum','Kuningan','Kuningan',0),
('RUSMIN EFFENDY, SH, MH','Partai Gerakan Indonesia Raya','TPS 06','Kedungarum','Kuningan','Kuningan',0),
('RUSMIN EFFENDY, SH, MH','Partai Gerakan Indonesia Raya','TPS 07','Kedungarum','Kuningan','Kuningan',1),
('RUSMIN EFFENDY, SH, MH','Partai Gerakan Indonesia Raya','TPS 08','Kedungarum','Kuningan','Kuningan',0),
('SHEILA AYU SAYIDAH, S.I.Kom','Partai Gerakan Indonesia Raya','TPS 01','Kedungarum','Kuningan','Kuningan',0),
('SHEILA AYU SAYIDAH, S.I.Kom','Partai Gerakan Indonesia Raya','TPS 02','Kedungarum','Kuningan','Kuningan',2),
('SHEILA AYU SAYIDAH, S.I.Kom','Partai Gerakan Indonesia Raya','TPS 03','Kedungarum','Kuningan','Kuningan',3),
('SHEILA AYU SAYIDAH, S.I.Kom','Partai Gerakan Indonesia Raya','TPS 04','Kedungarum','Kuningan','Kuningan',0),
('SHEILA AYU SAYIDAH, S.I.Kom','Partai Gerakan Indonesia Raya','TPS 05','Kedungarum','Kuningan','Kuningan',1),
('SHEILA AYU SAYIDAH, S.I.Kom','Partai Gerakan Indonesia Raya','TPS 06','Kedungarum','Kuningan','Kuningan',0),
('SHEILA AYU SAYIDAH, S.I.Kom','Partai Gerakan Indonesia Raya','TPS 07','Kedungarum','Kuningan','Kuningan',1),
('SHEILA AYU SAYIDAH, S.I.Kom','Partai Gerakan Indonesia Raya','TPS 08','Kedungarum','Kuningan','Kuningan',2),
('TUTI ROSINTA HUTAGALUNG, SH','Partai Gerakan Indonesia Raya','TPS 01','Kedungarum','Kuningan','Kuningan',0),
('TUTI ROSINTA HUTAGALUNG, SH','Partai Gerakan Indonesia Raya','TPS 02','Kedungarum','Kuningan','Kuningan',0),
('TUTI ROSINTA HUTAGALUNG, SH','Partai Gerakan Indonesia Raya','TPS 03','Kedungarum','Kuningan','Kuningan',0),
('TUTI ROSINTA HUTAGALUNG, SH','Partai Gerakan Indonesia Raya','TPS 04','Kedungarum','Kuningan','Kuningan',1),
('TUTI ROSINTA HUTAGALUNG, SH','Partai Gerakan Indonesia Raya','TPS 05','Kedungarum','Kuningan','Kuningan',0),
('TUTI ROSINTA HUTAGALUNG, SH','Partai Gerakan Indonesia Raya','TPS 06','Kedungarum','Kuningan','Kuningan',0),
('TUTI ROSINTA HUTAGALUNG, SH','Partai Gerakan Indonesia Raya','TPS 07','Kedungarum','Kuningan','Kuningan',0),
('TUTI ROSINTA HUTAGALUNG, SH','Partai Gerakan Indonesia Raya','TPS 08','Kedungarum','Kuningan','Kuningan',1),
('BAMBANG SUDIYONO','Partai Gerakan Indonesia Raya','TPS 01','Kedungarum','Kuningan','Kuningan',0),
('BAMBANG SUDIYONO','Partai Gerakan Indonesia Raya','TPS 02','Kedungarum','Kuningan','Kuningan',2),
('BAMBANG SUDIYONO','Partai Gerakan Indonesia Raya','TPS 03','Kedungarum','Kuningan','Kuningan',1),
('BAMBANG SUDIYONO','Partai Gerakan Indonesia Raya','TPS 04','Kedungarum','Kuningan','Kuningan',1),
('BAMBANG SUDIYONO','Partai Gerakan Indonesia Raya','TPS 05','Kedungarum','Kuningan','Kuningan',3),
('BAMBANG SUDIYONO','Partai Gerakan Indonesia Raya','TPS 06','Kedungarum','Kuningan','Kuningan',2),
('BAMBANG SUDIYONO','Partai Gerakan Indonesia Raya','TPS 07','Kedungarum','Kuningan','Kuningan',0),
('BAMBANG SUDIYONO','Partai Gerakan Indonesia Raya','TPS 08','Kedungarum','Kuningan','Kuningan',1),
('Partai Demokrasi Indonesia Perjuangan','Partai Demokrasi Indonesia Perjuangan','TPS 01','Kedungarum','Kuningan','Kuningan',5),
('Partai Demokrasi Indonesia Perjuangan','Partai Demokrasi Indonesia Perjuangan','TPS 02','Kedungarum','Kuningan','Kuningan',11),
('Partai Demokrasi Indonesia Perjuangan','Partai Demokrasi Indonesia Perjuangan','TPS 03','Kedungarum','Kuningan','Kuningan',20),
('Partai Demokrasi Indonesia Perjuangan','Partai Demokrasi Indonesia Perjuangan','TPS 04','Kedungarum','Kuningan','Kuningan',7),
('Partai Demokrasi Indonesia Perjuangan','Partai Demokrasi Indonesia Perjuangan','TPS 05','Kedungarum','Kuningan','Kuningan',6),
('Partai Demokrasi Indonesia Perjuangan','Partai Demokrasi Indonesia Perjuangan','TPS 06','Kedungarum','Kuningan','Kuningan',17),
('Partai Demokrasi Indonesia Perjuangan','Partai Demokrasi Indonesia Perjuangan','TPS 07','Kedungarum','Kuningan','Kuningan',33),
('Partai Demokrasi Indonesia Perjuangan','Partai Demokrasi Indonesia Perjuangan','TPS 08','Kedungarum','Kuningan','Kuningan',4),
('Drs. MUHAMAD NURDIN, M.M.','Partai Demokrasi Indonesia Perjuangan','TPS 01','Kedungarum','Kuningan','Kuningan',4),
('Drs. MUHAMAD NURDIN, M.M.','Partai Demokrasi Indonesia Perjuangan','TPS 02','Kedungarum','Kuningan','Kuningan',15),
('Drs. MUHAMAD NURDIN, M.M.','Partai Demokrasi Indonesia Perjuangan','TPS 03','Kedungarum','Kuningan','Kuningan',12),
('Drs. MUHAMAD NURDIN, M.M.','Partai Demokrasi Indonesia Perjuangan','TPS 04','Kedungarum','Kuningan','Kuningan',11),
('Drs. MUHAMAD NURDIN, M.M.','Partai Demokrasi Indonesia Perjuangan','TPS 05','Kedungarum','Kuningan','Kuningan',6),
('Drs. MUHAMAD NURDIN, M.M.','Partai Demokrasi Indonesia Perjuangan','TPS 06','Kedungarum','Kuningan','Kuningan',4),
('Drs. MUHAMAD NURDIN, M.M.','Partai Demokrasi Indonesia Perjuangan','TPS 07','Kedungarum','Kuningan','Kuningan',30),
('Drs. MUHAMAD NURDIN, M.M.','Partai Demokrasi Indonesia Perjuangan','TPS 08','Kedungarum','Kuningan','Kuningan',6),
('Ir. H. GATOT TJAHYONO, M.M.','Partai Demokrasi Indonesia Perjuangan','TPS 01','Kedungarum','Kuningan','Kuningan',0),
('Ir. H. GATOT TJAHYONO, M.M.','Partai Demokrasi Indonesia Perjuangan','TPS 02','Kedungarum','Kuningan','Kuningan',3),
('Ir. H. GATOT TJAHYONO, M.M.','Partai Demokrasi Indonesia Perjuangan','TPS 03','Kedungarum','Kuningan','Kuningan',1),
('Ir. H. GATOT TJAHYONO, M.M.','Partai Demokrasi Indonesia Perjuangan','TPS 04','Kedungarum','Kuningan','Kuningan',0),
('Ir. H. GATOT TJAHYONO, M.M.','Partai Demokrasi Indonesia Perjuangan','TPS 05','Kedungarum','Kuningan','Kuningan',1),
('Ir. H. GATOT TJAHYONO, M.M.','Partai Demokrasi Indonesia Perjuangan','TPS 06','Kedungarum','Kuningan','Kuningan',1),
('Ir. H. GATOT TJAHYONO, M.M.','Partai Demokrasi Indonesia Perjuangan','TPS 07','Kedungarum','Kuningan','Kuningan',2),
('Ir. H. GATOT TJAHYONO, M.M.','Partai Demokrasi Indonesia Perjuangan','TPS 08','Kedungarum','Kuningan','Kuningan',0),
('AUGUSTINA CONNIE','Partai Demokrasi Indonesia Perjuangan','TPS 01','Kedungarum','Kuningan','Kuningan',2),
('AUGUSTINA CONNIE','Partai Demokrasi Indonesia Perjuangan','TPS 02','Kedungarum','Kuningan','Kuningan',0),
('AUGUSTINA CONNIE','Partai Demokrasi Indonesia Perjuangan','TPS 03','Kedungarum','Kuningan','Kuningan',0),
('AUGUSTINA CONNIE','Partai Demokrasi Indonesia Perjuangan','TPS 04','Kedungarum','Kuningan','Kuningan',0),
('AUGUSTINA CONNIE','Partai Demokrasi Indonesia Perjuangan','TPS 05','Kedungarum','Kuningan','Kuningan',0),
('AUGUSTINA CONNIE','Partai Demokrasi Indonesia Perjuangan','TPS 06','Kedungarum','Kuningan','Kuningan',2),
('AUGUSTINA CONNIE','Partai Demokrasi Indonesia Perjuangan','TPS 07','Kedungarum','Kuningan','Kuningan',3),
('AUGUSTINA CONNIE','Partai Demokrasi Indonesia Perjuangan','TPS 08','Kedungarum','Kuningan','Kuningan',0),
('YAYAN SOPYANI','Partai Demokrasi Indonesia Perjuangan','TPS 01','Kedungarum','Kuningan','Kuningan',1),
('YAYAN SOPYANI','Partai Demokrasi Indonesia Perjuangan','TPS 02','Kedungarum','Kuningan','Kuningan',1),
('YAYAN SOPYANI','Partai Demokrasi Indonesia Perjuangan','TPS 03','Kedungarum','Kuningan','Kuningan',2),
('YAYAN SOPYANI','Partai Demokrasi Indonesia Perjuangan','TPS 04','Kedungarum','Kuningan','Kuningan',0),
('YAYAN SOPYANI','Partai Demokrasi Indonesia Perjuangan','TPS 05','Kedungarum','Kuningan','Kuningan',0),
('YAYAN SOPYANI','Partai Demokrasi Indonesia Perjuangan','TPS 06','Kedungarum','Kuningan','Kuningan',0),
('YAYAN SOPYANI','Partai Demokrasi Indonesia Perjuangan','TPS 07','Kedungarum','Kuningan','Kuningan',3),
('YAYAN SOPYANI','Partai Demokrasi Indonesia Perjuangan','TPS 08','Kedungarum','Kuningan','Kuningan',0),
('LUTHFI FAUZI, S.HI., M.M.','Partai Demokrasi Indonesia Perjuangan','TPS 01','Kedungarum','Kuningan','Kuningan',0),
('LUTHFI FAUZI, S.HI., M.M.','Partai Demokrasi Indonesia Perjuangan','TPS 02','Kedungarum','Kuningan','Kuningan',0),
('LUTHFI FAUZI, S.HI., M.M.','Partai Demokrasi Indonesia Perjuangan','TPS 03','Kedungarum','Kuningan','Kuningan',0),
('LUTHFI FAUZI, S.HI., M.M.','Partai Demokrasi Indonesia Perjuangan','TPS 04','Kedungarum','Kuningan','Kuningan',0),
('LUTHFI FAUZI, S.HI., M.M.','Partai Demokrasi Indonesia Perjuangan','TPS 05','Kedungarum','Kuningan','Kuningan',0),
('LUTHFI FAUZI, S.HI., M.M.','Partai Demokrasi Indonesia Perjuangan','TPS 06','Kedungarum','Kuningan','Kuningan',1),
('LUTHFI FAUZI, S.HI., M.M.','Partai Demokrasi Indonesia Perjuangan','TPS 07','Kedungarum','Kuningan','Kuningan',1),
('LUTHFI FAUZI, S.HI., M.M.','Partai Demokrasi Indonesia Perjuangan','TPS 08','Kedungarum','Kuningan','Kuningan',0),
('Dr. ETIN NURHAETIN NINGRUM, S.Ag., M.M., M.Si','Partai Demokrasi Indonesia Perjuangan','TPS 01','Kedungarum','Kuningan','Kuningan',0),
('Dr. ETIN NURHAETIN NINGRUM, S.Ag., M.M., M.Si','Partai Demokrasi Indonesia Perjuangan','TPS 02','Kedungarum','Kuningan','Kuningan',0),
('Dr. ETIN NURHAETIN NINGRUM, S.Ag., M.M., M.Si','Partai Demokrasi Indonesia Perjuangan','TPS 03','Kedungarum','Kuningan','Kuningan',4),
('Dr. ETIN NURHAETIN NINGRUM, S.Ag., M.M., M.Si','Partai Demokrasi Indonesia Perjuangan','TPS 04','Kedungarum','Kuningan','Kuningan',0),
('Dr. ETIN NURHAETIN NINGRUM, S.Ag., M.M., M.Si','Partai Demokrasi Indonesia Perjuangan','TPS 05','Kedungarum','Kuningan','Kuningan',2),
('Dr. ETIN NURHAETIN NINGRUM, S.Ag., M.M., M.Si','Partai Demokrasi Indonesia Perjuangan','TPS 06','Kedungarum','Kuningan','Kuningan',1),
('Dr. ETIN NURHAETIN NINGRUM, S.Ag., M.M., M.Si','Partai Demokrasi Indonesia Perjuangan','TPS 07','Kedungarum','Kuningan','Kuningan',1),
('Dr. ETIN NURHAETIN NINGRUM, S.Ag., M.M., M.Si','Partai Demokrasi Indonesia Perjuangan','TPS 08','Kedungarum','Kuningan','Kuningan',1),
('YESSY DIYANTARI, S.TP., M.M.','Partai Demokrasi Indonesia Perjuangan','TPS 01','Kedungarum','Kuningan','Kuningan',0),
('YESSY DIYANTARI, S.TP., M.M.','Partai Demokrasi Indonesia Perjuangan','TPS 02','Kedungarum','Kuningan','Kuningan',1),
('YESSY DIYANTARI, S.TP., M.M.','Partai Demokrasi Indonesia Perjuangan','TPS 03','Kedungarum','Kuningan','Kuningan',1),
('YESSY DIYANTARI, S.TP., M.M.','Partai Demokrasi Indonesia Perjuangan','TPS 04','Kedungarum','Kuningan','Kuningan',0),
('YESSY DIYANTARI, S.TP., M.M.','Partai Demokrasi Indonesia Perjuangan','TPS 05','Kedungarum','Kuningan','Kuningan',0),
('YESSY DIYANTARI, S.TP., M.M.','Partai Demokrasi Indonesia Perjuangan','TPS 06','Kedungarum','Kuningan','Kuningan',0),
('YESSY DIYANTARI, S.TP., M.M.','Partai Demokrasi Indonesia Perjuangan','TPS 07','Kedungarum','Kuningan','Kuningan',1),
('YESSY DIYANTARI, S.TP., M.M.','Partai Demokrasi Indonesia Perjuangan','TPS 08','Kedungarum','Kuningan','Kuningan',0),
('Partai Golongan Karya','Partai Golongan Karya','TPS 01','Kedungarum','Kuningan','Kuningan',9),
('Partai Golongan Karya','Partai Golongan Karya','TPS 02','Kedungarum','Kuningan','Kuningan',3),
('Partai Golongan Karya','Partai Golongan Karya','TPS 03','Kedungarum','Kuningan','Kuningan',2),
('Partai Golongan Karya','Partai Golongan Karya','TPS 04','Kedungarum','Kuningan','Kuningan',3),
('Partai Golongan Karya','Partai Golongan Karya','TPS 05','Kedungarum','Kuningan','Kuningan',2),
('Partai Golongan Karya','Partai Golongan Karya','TPS 06','Kedungarum','Kuningan','Kuningan',3),
('Partai Golongan Karya','Partai Golongan Karya','TPS 07','Kedungarum','Kuningan','Kuningan',7),
('Partai Golongan Karya','Partai Golongan Karya','TPS 08','Kedungarum','Kuningan','Kuningan',3),
('Drs. AGUN GUNANDJAR SUDARSA, Bc.IP., M.Si.','Partai Golongan Karya','TPS 01','Kedungarum','Kuningan','Kuningan',4),
('Drs. AGUN GUNANDJAR SUDARSA, Bc.IP., M.Si.','Partai Golongan Karya','TPS 02','Kedungarum','Kuningan','Kuningan',4),
('Drs. AGUN GUNANDJAR SUDARSA, Bc.IP., M.Si.','Partai Golongan Karya','TPS 03','Kedungarum','Kuningan','Kuningan',0),
('Drs. AGUN GUNANDJAR SUDARSA, Bc.IP., M.Si.','Partai Golongan Karya','TPS 04','Kedungarum','Kuningan','Kuningan',0),
('Drs. AGUN GUNANDJAR SUDARSA, Bc.IP., M.Si.','Partai Golongan Karya','TPS 05','Kedungarum','Kuningan','Kuningan',1),
('Drs. AGUN GUNANDJAR SUDARSA, Bc.IP., M.Si.','Partai Golongan Karya','TPS 06','Kedungarum','Kuningan','Kuningan',2),
('Drs. AGUN GUNANDJAR SUDARSA, Bc.IP., M.Si.','Partai Golongan Karya','TPS 07','Kedungarum','Kuningan','Kuningan',2),
('Drs. AGUN GUNANDJAR SUDARSA, Bc.IP., M.Si.','Partai Golongan Karya','TPS 08','Kedungarum','Kuningan','Kuningan',5),
('KHOLIS MALIK','Partai Golongan Karya','TPS 01','Kedungarum','Kuningan','Kuningan',4),
('KHOLIS MALIK','Partai Golongan Karya','TPS 02','Kedungarum','Kuningan','Kuningan',3),
('KHOLIS MALIK','Partai Golongan Karya','TPS 03','Kedungarum','Kuningan','Kuningan',2),
('KHOLIS MALIK','Partai Golongan Karya','TPS 04','Kedungarum','Kuningan','Kuningan',1),
('KHOLIS MALIK','Partai Golongan Karya','TPS 05','Kedungarum','Kuningan','Kuningan',0),
('KHOLIS MALIK','Partai Golongan Karya','TPS 06','Kedungarum','Kuningan','Kuningan',1),
('KHOLIS MALIK','Partai Golongan Karya','TPS 07','Kedungarum','Kuningan','Kuningan',0),
('KHOLIS MALIK','Partai Golongan Karya','TPS 08','Kedungarum','Kuningan','Kuningan',2),
('HJ. RENNY SOEDIRO','Partai Golongan Karya','TPS 01','Kedungarum','Kuningan','Kuningan',5),
('HJ. RENNY SOEDIRO','Partai Golongan Karya','TPS 02','Kedungarum','Kuningan','Kuningan',5),
('HJ. RENNY SOEDIRO','Partai Golongan Karya','TPS 03','Kedungarum','Kuningan','Kuningan',0),
('HJ. RENNY SOEDIRO','Partai Golongan Karya','TPS 04','Kedungarum','Kuningan','Kuningan',0),
('HJ. RENNY SOEDIRO','Partai Golongan Karya','TPS 05','Kedungarum','Kuningan','Kuningan',0),
('HJ. RENNY SOEDIRO','Partai Golongan Karya','TPS 06','Kedungarum','Kuningan','Kuningan',1),
('HJ. RENNY SOEDIRO','Partai Golongan Karya','TPS 07','Kedungarum','Kuningan','Kuningan',0),
('HJ. RENNY SOEDIRO','Partai Golongan Karya','TPS 08','Kedungarum','Kuningan','Kuningan',0),
('ENGKUS KUSNADI, S.H','Partai Golongan Karya','TPS 01','Kedungarum','Kuningan','Kuningan',0),
('ENGKUS KUSNADI, S.H','Partai Golongan Karya','TPS 02','Kedungarum','Kuningan','Kuningan',2),
('ENGKUS KUSNADI, S.H','Partai Golongan Karya','TPS 03','Kedungarum','Kuningan','Kuningan',0),
('ENGKUS KUSNADI, S.H','Partai Golongan Karya','TPS 04','Kedungarum','Kuningan','Kuningan',1),
('ENGKUS KUSNADI, S.H','Partai Golongan Karya','TPS 05','Kedungarum','Kuningan','Kuningan',0),
('ENGKUS KUSNADI, S.H','Partai Golongan Karya','TPS 06','Kedungarum','Kuningan','Kuningan',1),
('ENGKUS KUSNADI, S.H','Partai Golongan Karya','TPS 07','Kedungarum','Kuningan','Kuningan',0),
('ENGKUS KUSNADI, S.H','Partai Golongan Karya','TPS 08','Kedungarum','Kuningan','Kuningan',0),
('AYUNINGTYAS WIDARI RAMDHANIAR, S.I.A.','Partai Golongan Karya','TPS 01','Kedungarum','Kuningan','Kuningan',1),
('AYUNINGTYAS WIDARI RAMDHANIAR, S.I.A.','Partai Golongan Karya','TPS 02','Kedungarum','Kuningan','Kuningan',1),
('AYUNINGTYAS WIDARI RAMDHANIAR, S.I.A.','Partai Golongan Karya','TPS 03','Kedungarum','Kuningan','Kuningan',1),
('AYUNINGTYAS WIDARI RAMDHANIAR, S.I.A.','Partai Golongan Karya','TPS 04','Kedungarum','Kuningan','Kuningan',0),
('AYUNINGTYAS WIDARI RAMDHANIAR, S.I.A.','Partai Golongan Karya','TPS 05','Kedungarum','Kuningan','Kuningan',0),
('AYUNINGTYAS WIDARI RAMDHANIAR, S.I.A.','Partai Golongan Karya','TPS 06','Kedungarum','Kuningan','Kuningan',0),
('AYUNINGTYAS WIDARI RAMDHANIAR, S.I.A.','Partai Golongan Karya','TPS 07','Kedungarum','Kuningan','Kuningan',1),
('AYUNINGTYAS WIDARI RAMDHANIAR, S.I.A.','Partai Golongan Karya','TPS 08','Kedungarum','Kuningan','Kuningan',1),
('DENI YUSUP, S.Ag., M.Si','Partai Golongan Karya','TPS 01','Kedungarum','Kuningan','Kuningan',1),
('DENI YUSUP, S.Ag., M.Si','Partai Golongan Karya','TPS 02','Kedungarum','Kuningan','Kuningan',1),
('DENI YUSUP, S.Ag., M.Si','Partai Golongan Karya','TPS 03','Kedungarum','Kuningan','Kuningan',0),
('DENI YUSUP, S.Ag., M.Si','Partai Golongan Karya','TPS 04','Kedungarum','Kuningan','Kuningan',0),
('DENI YUSUP, S.Ag., M.Si','Partai Golongan Karya','TPS 05','Kedungarum','Kuningan','Kuningan',0),
('DENI YUSUP, S.Ag., M.Si','Partai Golongan Karya','TPS 06','Kedungarum','Kuningan','Kuningan',0),
('DENI YUSUP, S.Ag., M.Si','Partai Golongan Karya','TPS 07','Kedungarum','Kuningan','Kuningan',0),
('DENI YUSUP, S.Ag., M.Si','Partai Golongan Karya','TPS 08','Kedungarum','Kuningan','Kuningan',0),
('ETTY ROBIAH AFDHAL, M.A','Partai Golongan Karya','TPS 01','Kedungarum','Kuningan','Kuningan',1),
('ETTY ROBIAH AFDHAL, M.A','Partai Golongan Karya','TPS 02','Kedungarum','Kuningan','Kuningan',0),
('ETTY ROBIAH AFDHAL, M.A','Partai Golongan Karya','TPS 03','Kedungarum','Kuningan','Kuningan',0),
('ETTY ROBIAH AFDHAL, M.A','Partai Golongan Karya','TPS 04','Kedungarum','Kuningan','Kuningan',0),
('ETTY ROBIAH AFDHAL, M.A','Partai Golongan Karya','TPS 05','Kedungarum','Kuningan','Kuningan',0),
('ETTY ROBIAH AFDHAL, M.A','Partai Golongan Karya','TPS 06','Kedungarum','Kuningan','Kuningan',0),
('ETTY ROBIAH AFDHAL, M.A','Partai Golongan Karya','TPS 07','Kedungarum','Kuningan','Kuningan',0),
('ETTY ROBIAH AFDHAL, M.A','Partai Golongan Karya','TPS 08','Kedungarum','Kuningan','Kuningan',0),
('Partai Nasdem','Partai Nasdem','TPS 01','Kedungarum','Kuningan','Kuningan',1),
('Partai Nasdem','Partai Nasdem','TPS 02','Kedungarum','Kuningan','Kuningan',1),
('Partai Nasdem','Partai Nasdem','TPS 03','Kedungarum','Kuningan','Kuningan',1),
('Partai Nasdem','Partai Nasdem','TPS 04','Kedungarum','Kuningan','Kuningan',2),
('Partai Nasdem','Partai Nasdem','TPS 05','Kedungarum','Kuningan','Kuningan',3),
('Partai Nasdem','Partai Nasdem','TPS 06','Kedungarum','Kuningan','Kuningan',2),
('Partai Nasdem','Partai Nasdem','TPS 07','Kedungarum','Kuningan','Kuningan',1),
('Partai Nasdem','Partai Nasdem','TPS 08','Kedungarum','Kuningan','Kuningan',2),
('Dr. Ir. MUSTOHA ISKANDAR, SH, MDM','Partai Nasdem','TPS 01','Kedungarum','Kuningan','Kuningan',1),
('Dr. Ir. MUSTOHA ISKANDAR, SH, MDM','Partai Nasdem','TPS 02','Kedungarum','Kuningan','Kuningan',0),
('Dr. Ir. MUSTOHA ISKANDAR, SH, MDM','Partai Nasdem','TPS 03','Kedungarum','Kuningan','Kuningan',1),
('Dr. Ir. MUSTOHA ISKANDAR, SH, MDM','Partai Nasdem','TPS 04','Kedungarum','Kuningan','Kuningan',1),
('Dr. Ir. MUSTOHA ISKANDAR, SH, MDM','Partai Nasdem','TPS 05','Kedungarum','Kuningan','Kuningan',0),
('Dr. Ir. MUSTOHA ISKANDAR, SH, MDM','Partai Nasdem','TPS 06','Kedungarum','Kuningan','Kuningan',0),
('Dr. Ir. MUSTOHA ISKANDAR, SH, MDM','Partai Nasdem','TPS 07','Kedungarum','Kuningan','Kuningan',1),
('Dr. Ir. MUSTOHA ISKANDAR, SH, MDM','Partai Nasdem','TPS 08','Kedungarum','Kuningan','Kuningan',2),
('DR. H. AGUS SUPARMAN, MM.','Partai Nasdem','TPS 01','Kedungarum','Kuningan','Kuningan',2),
('DR. H. AGUS SUPARMAN, MM.','Partai Nasdem','TPS 02','Kedungarum','Kuningan','Kuningan',4),
('DR. H. AGUS SUPARMAN, MM.','Partai Nasdem','TPS 03','Kedungarum','Kuningan','Kuningan',10),
('DR. H. AGUS SUPARMAN, MM.','Partai Nasdem','TPS 04','Kedungarum','Kuningan','Kuningan',5),
('DR. H. AGUS SUPARMAN, MM.','Partai Nasdem','TPS 05','Kedungarum','Kuningan','Kuningan',0),
('DR. H. AGUS SUPARMAN, MM.','Partai Nasdem','TPS 06','Kedungarum','Kuningan','Kuningan',6),
('DR. H. AGUS SUPARMAN, MM.','Partai Nasdem','TPS 07','Kedungarum','Kuningan','Kuningan',4),
('DR. H. AGUS SUPARMAN, MM.','Partai Nasdem','TPS 08','Kedungarum','Kuningan','Kuningan',14),
('ERNA M. MOCHTAR, S.H, M.Si','Partai Nasdem','TPS 01','Kedungarum','Kuningan','Kuningan',0),
('ERNA M. MOCHTAR, S.H, M.Si','Partai Nasdem','TPS 02','Kedungarum','Kuningan','Kuningan',0),
('ERNA M. MOCHTAR, S.H, M.Si','Partai Nasdem','TPS 03','Kedungarum','Kuningan','Kuningan',0),
('ERNA M. MOCHTAR, S.H, M.Si','Partai Nasdem','TPS 04','Kedungarum','Kuningan','Kuningan',0),
('ERNA M. MOCHTAR, S.H, M.Si','Partai Nasdem','TPS 05','Kedungarum','Kuningan','Kuningan',0),
('ERNA M. MOCHTAR, S.H, M.Si','Partai Nasdem','TPS 06','Kedungarum','Kuningan','Kuningan',0),
('ERNA M. MOCHTAR, S.H, M.Si','Partai Nasdem','TPS 07','Kedungarum','Kuningan','Kuningan',1),
('ERNA M. MOCHTAR, S.H, M.Si','Partai Nasdem','TPS 08','Kedungarum','Kuningan','Kuningan',0),
('TUBAGUS FERI RELASYAH, S.S0S','Partai Nasdem','TPS 01','Kedungarum','Kuningan','Kuningan',0),
('TUBAGUS FERI RELASYAH, S.S0S','Partai Nasdem','TPS 02','Kedungarum','Kuningan','Kuningan',0),
('TUBAGUS FERI RELASYAH, S.S0S','Partai Nasdem','TPS 03','Kedungarum','Kuningan','Kuningan',0),
('TUBAGUS FERI RELASYAH, S.S0S','Partai Nasdem','TPS 04','Kedungarum','Kuningan','Kuningan',0),
('TUBAGUS FERI RELASYAH, S.S0S','Partai Nasdem','TPS 05','Kedungarum','Kuningan','Kuningan',0),
('TUBAGUS FERI RELASYAH, S.S0S','Partai Nasdem','TPS 06','Kedungarum','Kuningan','Kuningan',0),
('TUBAGUS FERI RELASYAH, S.S0S','Partai Nasdem','TPS 07','Kedungarum','Kuningan','Kuningan',1),
('TUBAGUS FERI RELASYAH, S.S0S','Partai Nasdem','TPS 08','Kedungarum','Kuningan','Kuningan',0),
('KRISNA MUKTI','Partai Nasdem','TPS 01','Kedungarum','Kuningan','Kuningan',0),
('KRISNA MUKTI','Partai Nasdem','TPS 02','Kedungarum','Kuningan','Kuningan',0),
('KRISNA MUKTI','Partai Nasdem','TPS 03','Kedungarum','Kuningan','Kuningan',1),
('KRISNA MUKTI','Partai Nasdem','TPS 04','Kedungarum','Kuningan','Kuningan',1),
('KRISNA MUKTI','Partai Nasdem','TPS 05','Kedungarum','Kuningan','Kuningan',0),
('KRISNA MUKTI','Partai Nasdem','TPS 06','Kedungarum','Kuningan','Kuningan',0),
('KRISNA MUKTI','Partai Nasdem','TPS 07','Kedungarum','Kuningan','Kuningan',0),
('KRISNA MUKTI','Partai Nasdem','TPS 08','Kedungarum','Kuningan','Kuningan',1),
('SELFI NAFILAH','Partai Nasdem','TPS 01','Kedungarum','Kuningan','Kuningan',0),
('SELFI NAFILAH','Partai Nasdem','TPS 02','Kedungarum','Kuningan','Kuningan',0),
('SELFI NAFILAH','Partai Nasdem','TPS 03','Kedungarum','Kuningan','Kuningan',0),
('SELFI NAFILAH','Partai Nasdem','TPS 04','Kedungarum','Kuningan','Kuningan',0),
('SELFI NAFILAH','Partai Nasdem','TPS 05','Kedungarum','Kuningan','Kuningan',0),
('SELFI NAFILAH','Partai Nasdem','TPS 06','Kedungarum','Kuningan','Kuningan',0),
('SELFI NAFILAH','Partai Nasdem','TPS 07','Kedungarum','Kuningan','Kuningan',0),
('SELFI NAFILAH','Partai Nasdem','TPS 08','Kedungarum','Kuningan','Kuningan',0),
('LISDA OKTAVIANTI','Partai Nasdem','TPS 01','Kedungarum','Kuningan','Kuningan',0),
('LISDA OKTAVIANTI','Partai Nasdem','TPS 02','Kedungarum','Kuningan','Kuningan',0),
('LISDA OKTAVIANTI','Partai Nasdem','TPS 03','Kedungarum','Kuningan','Kuningan',0),
('LISDA OKTAVIANTI','Partai Nasdem','TPS 04','Kedungarum','Kuningan','Kuningan',0),
('LISDA OKTAVIANTI','Partai Nasdem','TPS 05','Kedungarum','Kuningan','Kuningan',0),
('LISDA OKTAVIANTI','Partai Nasdem','TPS 06','Kedungarum','Kuningan','Kuningan',0),
('LISDA OKTAVIANTI','Partai Nasdem','TPS 07','Kedungarum','Kuningan','Kuningan',0),
('LISDA OKTAVIANTI','Partai Nasdem','TPS 08','Kedungarum','Kuningan','Kuningan',0),
('Partai Gerakan Perubahan Indonesia','Partai Gerakan Perubahan Indonesia','TPS 01','Kedungarum','Kuningan','Kuningan',0),
('Partai Gerakan Perubahan Indonesia','Partai Gerakan Perubahan Indonesia','TPS 02','Kedungarum','Kuningan','Kuningan',0),
('Partai Gerakan Perubahan Indonesia','Partai Gerakan Perubahan Indonesia','TPS 03','Kedungarum','Kuningan','Kuningan',0),
('Partai Gerakan Perubahan Indonesia','Partai Gerakan Perubahan Indonesia','TPS 04','Kedungarum','Kuningan','Kuningan',1),
('Partai Gerakan Perubahan Indonesia','Partai Gerakan Perubahan Indonesia','TPS 05','Kedungarum','Kuningan','Kuningan',1),
('Partai Gerakan Perubahan Indonesia','Partai Gerakan Perubahan Indonesia','TPS 06','Kedungarum','Kuningan','Kuningan',1),
('Partai Gerakan Perubahan Indonesia','Partai Gerakan Perubahan Indonesia','TPS 07','Kedungarum','Kuningan','Kuningan',0),
('Partai Gerakan Perubahan Indonesia','Partai Gerakan Perubahan Indonesia','TPS 08','Kedungarum','Kuningan','Kuningan',0),
('Laksma TNI (Purn) H. DIDIN ZAINAL ABIDIN, M.M','Partai Gerakan Perubahan Indonesia','TPS 01','Kedungarum','Kuningan','Kuningan',0),
('Laksma TNI (Purn) H. DIDIN ZAINAL ABIDIN, M.M','Partai Gerakan Perubahan Indonesia','TPS 02','Kedungarum','Kuningan','Kuningan',0),
('Laksma TNI (Purn) H. DIDIN ZAINAL ABIDIN, M.M','Partai Gerakan Perubahan Indonesia','TPS 03','Kedungarum','Kuningan','Kuningan',1),
('Laksma TNI (Purn) H. DIDIN ZAINAL ABIDIN, M.M','Partai Gerakan Perubahan Indonesia','TPS 04','Kedungarum','Kuningan','Kuningan',2),
('Laksma TNI (Purn) H. DIDIN ZAINAL ABIDIN, M.M','Partai Gerakan Perubahan Indonesia','TPS 05','Kedungarum','Kuningan','Kuningan',0),
('Laksma TNI (Purn) H. DIDIN ZAINAL ABIDIN, M.M','Partai Gerakan Perubahan Indonesia','TPS 06','Kedungarum','Kuningan','Kuningan',1),
('Laksma TNI (Purn) H. DIDIN ZAINAL ABIDIN, M.M','Partai Gerakan Perubahan Indonesia','TPS 07','Kedungarum','Kuningan','Kuningan',0),
('Laksma TNI (Purn) H. DIDIN ZAINAL ABIDIN, M.M','Partai Gerakan Perubahan Indonesia','TPS 08','Kedungarum','Kuningan','Kuningan',5),
('Dra. NITA SAFTINA','Partai Gerakan Perubahan Indonesia','TPS 01','Kedungarum','Kuningan','Kuningan',0),
('Dra. NITA SAFTINA','Partai Gerakan Perubahan Indonesia','TPS 02','Kedungarum','Kuningan','Kuningan',0),
('Dra. NITA SAFTINA','Partai Gerakan Perubahan Indonesia','TPS 03','Kedungarum','Kuningan','Kuningan',0),
('Dra. NITA SAFTINA','Partai Gerakan Perubahan Indonesia','TPS 04','Kedungarum','Kuningan','Kuningan',0),
('Dra. NITA SAFTINA','Partai Gerakan Perubahan Indonesia','TPS 05','Kedungarum','Kuningan','Kuningan',0),
('Dra. NITA SAFTINA','Partai Gerakan Perubahan Indonesia','TPS 06','Kedungarum','Kuningan','Kuningan',0),
('Dra. NITA SAFTINA','Partai Gerakan Perubahan Indonesia','TPS 07','Kedungarum','Kuningan','Kuningan',0),
('Dra. NITA SAFTINA','Partai Gerakan Perubahan Indonesia','TPS 08','Kedungarum','Kuningan','Kuningan',0),
('Partai Berkarya','Partai Berkarya','TPS 01','Kedungarum','Kuningan','Kuningan',2),
('Partai Berkarya','Partai Berkarya','TPS 02','Kedungarum','Kuningan','Kuningan',2),
('Partai Berkarya','Partai Berkarya','TPS 03','Kedungarum','Kuningan','Kuningan',4),
('Partai Berkarya','Partai Berkarya','TPS 04','Kedungarum','Kuningan','Kuningan',2),
('Partai Berkarya','Partai Berkarya','TPS 05','Kedungarum','Kuningan','Kuningan',1),
('Partai Berkarya','Partai Berkarya','TPS 06','Kedungarum','Kuningan','Kuningan',3),
('Partai Berkarya','Partai Berkarya','TPS 07','Kedungarum','Kuningan','Kuningan',2),
('Partai Berkarya','Partai Berkarya','TPS 08','Kedungarum','Kuningan','Kuningan',2),
('Drs. H. EKA SANTOSA','Partai Berkarya','TPS 01','Kedungarum','Kuningan','Kuningan',1),
('Drs. H. EKA SANTOSA','Partai Berkarya','TPS 02','Kedungarum','Kuningan','Kuningan',0),
('Drs. H. EKA SANTOSA','Partai Berkarya','TPS 03','Kedungarum','Kuningan','Kuningan',0),
('Drs. H. EKA SANTOSA','Partai Berkarya','TPS 04','Kedungarum','Kuningan','Kuningan',1),
('Drs. H. EKA SANTOSA','Partai Berkarya','TPS 05','Kedungarum','Kuningan','Kuningan',0),
('Drs. H. EKA SANTOSA','Partai Berkarya','TPS 06','Kedungarum','Kuningan','Kuningan',1),
('Drs. H. EKA SANTOSA','Partai Berkarya','TPS 07','Kedungarum','Kuningan','Kuningan',0),
('Drs. H. EKA SANTOSA','Partai Berkarya','TPS 08','Kedungarum','Kuningan','Kuningan',0),
('Hj. LESTARI YUSENO, SH','Partai Berkarya','TPS 01','Kedungarum','Kuningan','Kuningan',4),
('Hj. LESTARI YUSENO, SH','Partai Berkarya','TPS 02','Kedungarum','Kuningan','Kuningan',1),
('Hj. LESTARI YUSENO, SH','Partai Berkarya','TPS 03','Kedungarum','Kuningan','Kuningan',0),
('Hj. LESTARI YUSENO, SH','Partai Berkarya','TPS 04','Kedungarum','Kuningan','Kuningan',0),
('Hj. LESTARI YUSENO, SH','Partai Berkarya','TPS 05','Kedungarum','Kuningan','Kuningan',0),
('Hj. LESTARI YUSENO, SH','Partai Berkarya','TPS 06','Kedungarum','Kuningan','Kuningan',2),
('Hj. LESTARI YUSENO, SH','Partai Berkarya','TPS 07','Kedungarum','Kuningan','Kuningan',0),
('Hj. LESTARI YUSENO, SH','Partai Berkarya','TPS 08','Kedungarum','Kuningan','Kuningan',0),
('SIR JOHN','Partai Berkarya','TPS 01','Kedungarum','Kuningan','Kuningan',0),
('SIR JOHN','Partai Berkarya','TPS 02','Kedungarum','Kuningan','Kuningan',0),
('SIR JOHN','Partai Berkarya','TPS 03','Kedungarum','Kuningan','Kuningan',0),
('SIR JOHN','Partai Berkarya','TPS 04','Kedungarum','Kuningan','Kuningan',0),
('SIR JOHN','Partai Berkarya','TPS 05','Kedungarum','Kuningan','Kuningan',0),
('SIR JOHN','Partai Berkarya','TPS 06','Kedungarum','Kuningan','Kuningan',0),
('SIR JOHN','Partai Berkarya','TPS 07','Kedungarum','Kuningan','Kuningan',0),
('SIR JOHN','Partai Berkarya','TPS 08','Kedungarum','Kuningan','Kuningan',0),
('AHMAD JAYA ADIGUNA','Partai Berkarya','TPS 01','Kedungarum','Kuningan','Kuningan',0),
('AHMAD JAYA ADIGUNA','Partai Berkarya','TPS 02','Kedungarum','Kuningan','Kuningan',0),
('AHMAD JAYA ADIGUNA','Partai Berkarya','TPS 03','Kedungarum','Kuningan','Kuningan',0),
('AHMAD JAYA ADIGUNA','Partai Berkarya','TPS 04','Kedungarum','Kuningan','Kuningan',0),
('AHMAD JAYA ADIGUNA','Partai Berkarya','TPS 05','Kedungarum','Kuningan','Kuningan',0),
('AHMAD JAYA ADIGUNA','Partai Berkarya','TPS 06','Kedungarum','Kuningan','Kuningan',1),
('AHMAD JAYA ADIGUNA','Partai Berkarya','TPS 07','Kedungarum','Kuningan','Kuningan',1),
('AHMAD JAYA ADIGUNA','Partai Berkarya','TPS 08','Kedungarum','Kuningan','Kuningan',0),
('MULYADI ELHAN ZAKARIA','Partai Berkarya','TPS 01','Kedungarum','Kuningan','Kuningan',0),
('MULYADI ELHAN ZAKARIA','Partai Berkarya','TPS 02','Kedungarum','Kuningan','Kuningan',0),
('MULYADI ELHAN ZAKARIA','Partai Berkarya','TPS 03','Kedungarum','Kuningan','Kuningan',1),
('MULYADI ELHAN ZAKARIA','Partai Berkarya','TPS 04','Kedungarum','Kuningan','Kuningan',0),
('MULYADI ELHAN ZAKARIA','Partai Berkarya','TPS 05','Kedungarum','Kuningan','Kuningan',0),
('MULYADI ELHAN ZAKARIA','Partai Berkarya','TPS 06','Kedungarum','Kuningan','Kuningan',0),
('MULYADI ELHAN ZAKARIA','Partai Berkarya','TPS 07','Kedungarum','Kuningan','Kuningan',0),
('MULYADI ELHAN ZAKARIA','Partai Berkarya','TPS 08','Kedungarum','Kuningan','Kuningan',0),
('NUNI HARMAYANTI','Partai Berkarya','TPS 01','Kedungarum','Kuningan','Kuningan',0),
('NUNI HARMAYANTI','Partai Berkarya','TPS 02','Kedungarum','Kuningan','Kuningan',0),
('NUNI HARMAYANTI','Partai Berkarya','TPS 03','Kedungarum','Kuningan','Kuningan',0),
('NUNI HARMAYANTI','Partai Berkarya','TPS 04','Kedungarum','Kuningan','Kuningan',0),
('NUNI HARMAYANTI','Partai Berkarya','TPS 05','Kedungarum','Kuningan','Kuningan',0),
('NUNI HARMAYANTI','Partai Berkarya','TPS 06','Kedungarum','Kuningan','Kuningan',1),
('NUNI HARMAYANTI','Partai Berkarya','TPS 07','Kedungarum','Kuningan','Kuningan',0),
('NUNI HARMAYANTI','Partai Berkarya','TPS 08','Kedungarum','Kuningan','Kuningan',0),
('AVERINA OKTAVIA MENGKO','Partai Berkarya','TPS 01','Kedungarum','Kuningan','Kuningan',0),
('AVERINA OKTAVIA MENGKO','Partai Berkarya','TPS 02','Kedungarum','Kuningan','Kuningan',0),
('AVERINA OKTAVIA MENGKO','Partai Berkarya','TPS 03','Kedungarum','Kuningan','Kuningan',0),
('AVERINA OKTAVIA MENGKO','Partai Berkarya','TPS 04','Kedungarum','Kuningan','Kuningan',0),
('AVERINA OKTAVIA MENGKO','Partai Berkarya','TPS 05','Kedungarum','Kuningan','Kuningan',0),
('AVERINA OKTAVIA MENGKO','Partai Berkarya','TPS 06','Kedungarum','Kuningan','Kuningan',0),
('AVERINA OKTAVIA MENGKO','Partai Berkarya','TPS 07','Kedungarum','Kuningan','Kuningan',0),
('AVERINA OKTAVIA MENGKO','Partai Berkarya','TPS 08','Kedungarum','Kuningan','Kuningan',0),
('Partai Keadilan Sejahtera','Partai Keadilan Sejahtera','TPS 01','Kedungarum','Kuningan','Kuningan',26),
('Partai Keadilan Sejahtera','Partai Keadilan Sejahtera','TPS 02','Kedungarum','Kuningan','Kuningan',16),
('Partai Keadilan Sejahtera','Partai Keadilan Sejahtera','TPS 03','Kedungarum','Kuningan','Kuningan',16),
('Partai Keadilan Sejahtera','Partai Keadilan Sejahtera','TPS 04','Kedungarum','Kuningan','Kuningan',15),
('Partai Keadilan Sejahtera','Partai Keadilan Sejahtera','TPS 05','Kedungarum','Kuningan','Kuningan',10),
('Partai Keadilan Sejahtera','Partai Keadilan Sejahtera','TPS 06','Kedungarum','Kuningan','Kuningan',3),
('Partai Keadilan Sejahtera','Partai Keadilan Sejahtera','TPS 07','Kedungarum','Kuningan','Kuningan',6),
('Partai Keadilan Sejahtera','Partai Keadilan Sejahtera','TPS 08','Kedungarum','Kuningan','Kuningan',29),
('DR. KH. SURAHMAN HIDAYAT, MA.','Partai Keadilan Sejahtera','TPS 01','Kedungarum','Kuningan','Kuningan',28),
('DR. KH. SURAHMAN HIDAYAT, MA.','Partai Keadilan Sejahtera','TPS 02','Kedungarum','Kuningan','Kuningan',10),
('DR. KH. SURAHMAN HIDAYAT, MA.','Partai Keadilan Sejahtera','TPS 03','Kedungarum','Kuningan','Kuningan',7),
('DR. KH. SURAHMAN HIDAYAT, MA.','Partai Keadilan Sejahtera','TPS 04','Kedungarum','Kuningan','Kuningan',14),
('DR. KH. SURAHMAN HIDAYAT, MA.','Partai Keadilan Sejahtera','TPS 05','Kedungarum','Kuningan','Kuningan',7),
('DR. KH. SURAHMAN HIDAYAT, MA.','Partai Keadilan Sejahtera','TPS 06','Kedungarum','Kuningan','Kuningan',5),
('DR. KH. SURAHMAN HIDAYAT, MA.','Partai Keadilan Sejahtera','TPS 07','Kedungarum','Kuningan','Kuningan',7),
('DR. KH. SURAHMAN HIDAYAT, MA.','Partai Keadilan Sejahtera','TPS 08','Kedungarum','Kuningan','Kuningan',18),
('KH. ACHIDIN NOOR, MA.','Partai Keadilan Sejahtera','TPS 01','Kedungarum','Kuningan','Kuningan',20),
('KH. ACHIDIN NOOR, MA.','Partai Keadilan Sejahtera','TPS 02','Kedungarum','Kuningan','Kuningan',12),
('KH. ACHIDIN NOOR, MA.','Partai Keadilan Sejahtera','TPS 03','Kedungarum','Kuningan','Kuningan',5),
('KH. ACHIDIN NOOR, MA.','Partai Keadilan Sejahtera','TPS 04','Kedungarum','Kuningan','Kuningan',5),
('KH. ACHIDIN NOOR, MA.','Partai Keadilan Sejahtera','TPS 05','Kedungarum','Kuningan','Kuningan',4),
('KH. ACHIDIN NOOR, MA.','Partai Keadilan Sejahtera','TPS 06','Kedungarum','Kuningan','Kuningan',1),
('KH. ACHIDIN NOOR, MA.','Partai Keadilan Sejahtera','TPS 07','Kedungarum','Kuningan','Kuningan',2),
('KH. ACHIDIN NOOR, MA.','Partai Keadilan Sejahtera','TPS 08','Kedungarum','Kuningan','Kuningan',7),
('ANITA SETIYOWATI, S.Pd.','Partai Keadilan Sejahtera','TPS 01','Kedungarum','Kuningan','Kuningan',0),
('ANITA SETIYOWATI, S.Pd.','Partai Keadilan Sejahtera','TPS 02','Kedungarum','Kuningan','Kuningan',1),
('ANITA SETIYOWATI, S.Pd.','Partai Keadilan Sejahtera','TPS 03','Kedungarum','Kuningan','Kuningan',0),
('ANITA SETIYOWATI, S.Pd.','Partai Keadilan Sejahtera','TPS 04','Kedungarum','Kuningan','Kuningan',0),
('ANITA SETIYOWATI, S.Pd.','Partai Keadilan Sejahtera','TPS 05','Kedungarum','Kuningan','Kuningan',0),
('ANITA SETIYOWATI, S.Pd.','Partai Keadilan Sejahtera','TPS 06','Kedungarum','Kuningan','Kuningan',0),
('ANITA SETIYOWATI, S.Pd.','Partai Keadilan Sejahtera','TPS 07','Kedungarum','Kuningan','Kuningan',1),
('ANITA SETIYOWATI, S.Pd.','Partai Keadilan Sejahtera','TPS 08','Kedungarum','Kuningan','Kuningan',2),
('Ir. H. ADE BARKAH','Partai Keadilan Sejahtera','TPS 01','Kedungarum','Kuningan','Kuningan',1),
('Ir. H. ADE BARKAH','Partai Keadilan Sejahtera','TPS 02','Kedungarum','Kuningan','Kuningan',1),
('Ir. H. ADE BARKAH','Partai Keadilan Sejahtera','TPS 03','Kedungarum','Kuningan','Kuningan',1),
('Ir. H. ADE BARKAH','Partai Keadilan Sejahtera','TPS 04','Kedungarum','Kuningan','Kuningan',0),
('Ir. H. ADE BARKAH','Partai Keadilan Sejahtera','TPS 05','Kedungarum','Kuningan','Kuningan',0),
('Ir. H. ADE BARKAH','Partai Keadilan Sejahtera','TPS 06','Kedungarum','Kuningan','Kuningan',0),
('Ir. H. ADE BARKAH','Partai Keadilan Sejahtera','TPS 07','Kedungarum','Kuningan','Kuningan',1),
('Ir. H. ADE BARKAH','Partai Keadilan Sejahtera','TPS 08','Kedungarum','Kuningan','Kuningan',2),
('ICIH MINTARSIH, S.Pd','Partai Keadilan Sejahtera','TPS 01','Kedungarum','Kuningan','Kuningan',3),
('ICIH MINTARSIH, S.Pd','Partai Keadilan Sejahtera','TPS 02','Kedungarum','Kuningan','Kuningan',1),
('ICIH MINTARSIH, S.Pd','Partai Keadilan Sejahtera','TPS 03','Kedungarum','Kuningan','Kuningan',0),
('ICIH MINTARSIH, S.Pd','Partai Keadilan Sejahtera','TPS 04','Kedungarum','Kuningan','Kuningan',0),
('ICIH MINTARSIH, S.Pd','Partai Keadilan Sejahtera','TPS 05','Kedungarum','Kuningan','Kuningan',2),
('ICIH MINTARSIH, S.Pd','Partai Keadilan Sejahtera','TPS 06','Kedungarum','Kuningan','Kuningan',0),
('ICIH MINTARSIH, S.Pd','Partai Keadilan Sejahtera','TPS 07','Kedungarum','Kuningan','Kuningan',1),
('ICIH MINTARSIH, S.Pd','Partai Keadilan Sejahtera','TPS 08','Kedungarum','Kuningan','Kuningan',2),
('HJ ETY NURHADIYATI','Partai Keadilan Sejahtera','TPS 01','Kedungarum','Kuningan','Kuningan',0),
('HJ ETY NURHADIYATI','Partai Keadilan Sejahtera','TPS 02','Kedungarum','Kuningan','Kuningan',0),
('HJ ETY NURHADIYATI','Partai Keadilan Sejahtera','TPS 03','Kedungarum','Kuningan','Kuningan',0),
('HJ ETY NURHADIYATI','Partai Keadilan Sejahtera','TPS 04','Kedungarum','Kuningan','Kuningan',1),
('HJ ETY NURHADIYATI','Partai Keadilan Sejahtera','TPS 05','Kedungarum','Kuningan','Kuningan',0),
('HJ ETY NURHADIYATI','Partai Keadilan Sejahtera','TPS 06','Kedungarum','Kuningan','Kuningan',0),
('HJ ETY NURHADIYATI','Partai Keadilan Sejahtera','TPS 07','Kedungarum','Kuningan','Kuningan',0),
('HJ ETY NURHADIYATI','Partai Keadilan Sejahtera','TPS 08','Kedungarum','Kuningan','Kuningan',1),
('H. ISMAIL ELYAS','Partai Keadilan Sejahtera','TPS 01','Kedungarum','Kuningan','Kuningan',0),
('H. ISMAIL ELYAS','Partai Keadilan Sejahtera','TPS 02','Kedungarum','Kuningan','Kuningan',0),
('H. ISMAIL ELYAS','Partai Keadilan Sejahtera','TPS 03','Kedungarum','Kuningan','Kuningan',0),
('H. ISMAIL ELYAS','Partai Keadilan Sejahtera','TPS 04','Kedungarum','Kuningan','Kuningan',0),
('H. ISMAIL ELYAS','Partai Keadilan Sejahtera','TPS 05','Kedungarum','Kuningan','Kuningan',1),
('H. ISMAIL ELYAS','Partai Keadilan Sejahtera','TPS 06','Kedungarum','Kuningan','Kuningan',0),
('H. ISMAIL ELYAS','Partai Keadilan Sejahtera','TPS 07','Kedungarum','Kuningan','Kuningan',0),
('H. ISMAIL ELYAS','Partai Keadilan Sejahtera','TPS 08','Kedungarum','Kuningan','Kuningan',1),
('Partai Persatuan Indonesia','Partai Persatuan Indonesia','TPS 01','Kedungarum','Kuningan','Kuningan',1),
('Partai Persatuan Indonesia','Partai Persatuan Indonesia','TPS 02','Kedungarum','Kuningan','Kuningan',1),
('Partai Persatuan Indonesia','Partai Persatuan Indonesia','TPS 03','Kedungarum','Kuningan','Kuningan',6),
('Partai Persatuan Indonesia','Partai Persatuan Indonesia','TPS 04','Kedungarum','Kuningan','Kuningan',0),
('Partai Persatuan Indonesia','Partai Persatuan Indonesia','TPS 05','Kedungarum','Kuningan','Kuningan',0),
('Partai Persatuan Indonesia','Partai Persatuan Indonesia','TPS 06','Kedungarum','Kuningan','Kuningan',4),
('Partai Persatuan Indonesia','Partai Persatuan Indonesia','TPS 07','Kedungarum','Kuningan','Kuningan',3),
('Partai Persatuan Indonesia','Partai Persatuan Indonesia','TPS 08','Kedungarum','Kuningan','Kuningan',1),
('LINDA KARTIKA DEWI','Partai Persatuan Indonesia','TPS 01','Kedungarum','Kuningan','Kuningan',0),
('LINDA KARTIKA DEWI','Partai Persatuan Indonesia','TPS 02','Kedungarum','Kuningan','Kuningan',1),
('LINDA KARTIKA DEWI','Partai Persatuan Indonesia','TPS 03','Kedungarum','Kuningan','Kuningan',0),
('LINDA KARTIKA DEWI','Partai Persatuan Indonesia','TPS 04','Kedungarum','Kuningan','Kuningan',2),
('LINDA KARTIKA DEWI','Partai Persatuan Indonesia','TPS 05','Kedungarum','Kuningan','Kuningan',1),
('LINDA KARTIKA DEWI','Partai Persatuan Indonesia','TPS 06','Kedungarum','Kuningan','Kuningan',0),
('LINDA KARTIKA DEWI','Partai Persatuan Indonesia','TPS 07','Kedungarum','Kuningan','Kuningan',2),
('LINDA KARTIKA DEWI','Partai Persatuan Indonesia','TPS 08','Kedungarum','Kuningan','Kuningan',0),
('UUS ALI HUSNI, S.Kom','Partai Persatuan Indonesia','TPS 01','Kedungarum','Kuningan','Kuningan',0),
('UUS ALI HUSNI, S.Kom','Partai Persatuan Indonesia','TPS 02','Kedungarum','Kuningan','Kuningan',0),
('UUS ALI HUSNI, S.Kom','Partai Persatuan Indonesia','TPS 03','Kedungarum','Kuningan','Kuningan',0),
('UUS ALI HUSNI, S.Kom','Partai Persatuan Indonesia','TPS 04','Kedungarum','Kuningan','Kuningan',1),
('UUS ALI HUSNI, S.Kom','Partai Persatuan Indonesia','TPS 05','Kedungarum','Kuningan','Kuningan',0),
('UUS ALI HUSNI, S.Kom','Partai Persatuan Indonesia','TPS 06','Kedungarum','Kuningan','Kuningan',1),
('UUS ALI HUSNI, S.Kom','Partai Persatuan Indonesia','TPS 07','Kedungarum','Kuningan','Kuningan',0),
('UUS ALI HUSNI, S.Kom','Partai Persatuan Indonesia','TPS 08','Kedungarum','Kuningan','Kuningan',0),
('A. DARSONO, SH, MH','Partai Persatuan Indonesia','TPS 01','Kedungarum','Kuningan','Kuningan',0),
('A. DARSONO, SH, MH','Partai Persatuan Indonesia','TPS 02','Kedungarum','Kuningan','Kuningan',0),
('A. DARSONO, SH, MH','Partai Persatuan Indonesia','TPS 03','Kedungarum','Kuningan','Kuningan',0),
('A. DARSONO, SH, MH','Partai Persatuan Indonesia','TPS 04','Kedungarum','Kuningan','Kuningan',0),
('A. DARSONO, SH, MH','Partai Persatuan Indonesia','TPS 05','Kedungarum','Kuningan','Kuningan',0),
('A. DARSONO, SH, MH','Partai Persatuan Indonesia','TPS 06','Kedungarum','Kuningan','Kuningan',1),
('A. DARSONO, SH, MH','Partai Persatuan Indonesia','TPS 07','Kedungarum','Kuningan','Kuningan',0),
('A. DARSONO, SH, MH','Partai Persatuan Indonesia','TPS 08','Kedungarum','Kuningan','Kuningan',0),
('AMINUDDIN, S.Sos, MM','Partai Persatuan Indonesia','TPS 01','Kedungarum','Kuningan','Kuningan',0),
('AMINUDDIN, S.Sos, MM','Partai Persatuan Indonesia','TPS 02','Kedungarum','Kuningan','Kuningan',0),
('AMINUDDIN, S.Sos, MM','Partai Persatuan Indonesia','TPS 03','Kedungarum','Kuningan','Kuningan',0),
('AMINUDDIN, S.Sos, MM','Partai Persatuan Indonesia','TPS 04','Kedungarum','Kuningan','Kuningan',0),
('AMINUDDIN, S.Sos, MM','Partai Persatuan Indonesia','TPS 05','Kedungarum','Kuningan','Kuningan',0),
('AMINUDDIN, S.Sos, MM','Partai Persatuan Indonesia','TPS 06','Kedungarum','Kuningan','Kuningan',1),
('AMINUDDIN, S.Sos, MM','Partai Persatuan Indonesia','TPS 07','Kedungarum','Kuningan','Kuningan',0),
('AMINUDDIN, S.Sos, MM','Partai Persatuan Indonesia','TPS 08','Kedungarum','Kuningan','Kuningan',0),
('THIYA LATIFFAH SYAEFFUDIN FUTRI, S.Farm','Partai Persatuan Indonesia','TPS 01','Kedungarum','Kuningan','Kuningan',0),
('THIYA LATIFFAH SYAEFFUDIN FUTRI, S.Farm','Partai Persatuan Indonesia','TPS 02','Kedungarum','Kuningan','Kuningan',0),
('THIYA LATIFFAH SYAEFFUDIN FUTRI, S.Farm','Partai Persatuan Indonesia','TPS 03','Kedungarum','Kuningan','Kuningan',0),
('THIYA LATIFFAH SYAEFFUDIN FUTRI, S.Farm','Partai Persatuan Indonesia','TPS 04','Kedungarum','Kuningan','Kuningan',0),
('THIYA LATIFFAH SYAEFFUDIN FUTRI, S.Farm','Partai Persatuan Indonesia','TPS 05','Kedungarum','Kuningan','Kuningan',0),
('THIYA LATIFFAH SYAEFFUDIN FUTRI, S.Farm','Partai Persatuan Indonesia','TPS 06','Kedungarum','Kuningan','Kuningan',1),
('THIYA LATIFFAH SYAEFFUDIN FUTRI, S.Farm','Partai Persatuan Indonesia','TPS 07','Kedungarum','Kuningan','Kuningan',0),
('THIYA LATIFFAH SYAEFFUDIN FUTRI, S.Farm','Partai Persatuan Indonesia','TPS 08','Kedungarum','Kuningan','Kuningan',1),
('ARISTOKRA L.J TOMASOA','Partai Persatuan Indonesia','TPS 01','Kedungarum','Kuningan','Kuningan',0),
('ARISTOKRA L.J TOMASOA','Partai Persatuan Indonesia','TPS 02','Kedungarum','Kuningan','Kuningan',0),
('ARISTOKRA L.J TOMASOA','Partai Persatuan Indonesia','TPS 03','Kedungarum','Kuningan','Kuningan',0),
('ARISTOKRA L.J TOMASOA','Partai Persatuan Indonesia','TPS 04','Kedungarum','Kuningan','Kuningan',0),
('ARISTOKRA L.J TOMASOA','Partai Persatuan Indonesia','TPS 05','Kedungarum','Kuningan','Kuningan',0),
('ARISTOKRA L.J TOMASOA','Partai Persatuan Indonesia','TPS 06','Kedungarum','Kuningan','Kuningan',1),
('ARISTOKRA L.J TOMASOA','Partai Persatuan Indonesia','TPS 07','Kedungarum','Kuningan','Kuningan',0),
('ARISTOKRA L.J TOMASOA','Partai Persatuan Indonesia','TPS 08','Kedungarum','Kuningan','Kuningan',0),
('BETY PUSPITASARI, AK','Partai Persatuan Indonesia','TPS 01','Kedungarum','Kuningan','Kuningan',1),
('BETY PUSPITASARI, AK','Partai Persatuan Indonesia','TPS 02','Kedungarum','Kuningan','Kuningan',0),
('BETY PUSPITASARI, AK','Partai Persatuan Indonesia','TPS 03','Kedungarum','Kuningan','Kuningan',0),
('BETY PUSPITASARI, AK','Partai Persatuan Indonesia','TPS 04','Kedungarum','Kuningan','Kuningan',0),
('BETY PUSPITASARI, AK','Partai Persatuan Indonesia','TPS 05','Kedungarum','Kuningan','Kuningan',0),
('BETY PUSPITASARI, AK','Partai Persatuan Indonesia','TPS 06','Kedungarum','Kuningan','Kuningan',0),
('BETY PUSPITASARI, AK','Partai Persatuan Indonesia','TPS 07','Kedungarum','Kuningan','Kuningan',0),
('BETY PUSPITASARI, AK','Partai Persatuan Indonesia','TPS 08','Kedungarum','Kuningan','Kuningan',0),
('Partai Persatuan Pembangunan','Partai Persatuan Pembangunan','TPS 01','Kedungarum','Kuningan','Kuningan',2),
('Partai Persatuan Pembangunan','Partai Persatuan Pembangunan','TPS 02','Kedungarum','Kuningan','Kuningan',0),
('Partai Persatuan Pembangunan','Partai Persatuan Pembangunan','TPS 03','Kedungarum','Kuningan','Kuningan',7),
('Partai Persatuan Pembangunan','Partai Persatuan Pembangunan','TPS 04','Kedungarum','Kuningan','Kuningan',2),
('Partai Persatuan Pembangunan','Partai Persatuan Pembangunan','TPS 05','Kedungarum','Kuningan','Kuningan',5),
('Partai Persatuan Pembangunan','Partai Persatuan Pembangunan','TPS 06','Kedungarum','Kuningan','Kuningan',11),
('Partai Persatuan Pembangunan','Partai Persatuan Pembangunan','TPS 07','Kedungarum','Kuningan','Kuningan',7),
('Partai Persatuan Pembangunan','Partai Persatuan Pembangunan','TPS 08','Kedungarum','Kuningan','Kuningan',0),
('ASEP A MAOSHUL AFFANDY','Partai Persatuan Pembangunan','TPS 01','Kedungarum','Kuningan','Kuningan',3),
('ASEP A MAOSHUL AFFANDY','Partai Persatuan Pembangunan','TPS 02','Kedungarum','Kuningan','Kuningan',1),
('ASEP A MAOSHUL AFFANDY','Partai Persatuan Pembangunan','TPS 03','Kedungarum','Kuningan','Kuningan',2),
('ASEP A MAOSHUL AFFANDY','Partai Persatuan Pembangunan','TPS 04','Kedungarum','Kuningan','Kuningan',8),
('ASEP A MAOSHUL AFFANDY','Partai Persatuan Pembangunan','TPS 05','Kedungarum','Kuningan','Kuningan',10),
('ASEP A MAOSHUL AFFANDY','Partai Persatuan Pembangunan','TPS 06','Kedungarum','Kuningan','Kuningan',7),
('ASEP A MAOSHUL AFFANDY','Partai Persatuan Pembangunan','TPS 07','Kedungarum','Kuningan','Kuningan',3),
('ASEP A MAOSHUL AFFANDY','Partai Persatuan Pembangunan','TPS 08','Kedungarum','Kuningan','Kuningan',1),
('ARYA PERMANA GRAHA','Partai Persatuan Pembangunan','TPS 01','Kedungarum','Kuningan','Kuningan',1),
('ARYA PERMANA GRAHA','Partai Persatuan Pembangunan','TPS 02','Kedungarum','Kuningan','Kuningan',2),
('ARYA PERMANA GRAHA','Partai Persatuan Pembangunan','TPS 03','Kedungarum','Kuningan','Kuningan',2),
('ARYA PERMANA GRAHA','Partai Persatuan Pembangunan','TPS 04','Kedungarum','Kuningan','Kuningan',6),
('ARYA PERMANA GRAHA','Partai Persatuan Pembangunan','TPS 05','Kedungarum','Kuningan','Kuningan',9),
('ARYA PERMANA GRAHA','Partai Persatuan Pembangunan','TPS 06','Kedungarum','Kuningan','Kuningan',5),
('ARYA PERMANA GRAHA','Partai Persatuan Pembangunan','TPS 07','Kedungarum','Kuningan','Kuningan',1),
('ARYA PERMANA GRAHA','Partai Persatuan Pembangunan','TPS 08','Kedungarum','Kuningan','Kuningan',2),
('DRA. HJ. WARDATUN NA IM','Partai Persatuan Pembangunan','TPS 01','Kedungarum','Kuningan','Kuningan',0),
('DRA. HJ. WARDATUN NA IM','Partai Persatuan Pembangunan','TPS 02','Kedungarum','Kuningan','Kuningan',1),
('DRA. HJ. WARDATUN NA IM','Partai Persatuan Pembangunan','TPS 03','Kedungarum','Kuningan','Kuningan',0),
('DRA. HJ. WARDATUN NA IM','Partai Persatuan Pembangunan','TPS 04','Kedungarum','Kuningan','Kuningan',1),
('DRA. HJ. WARDATUN NA IM','Partai Persatuan Pembangunan','TPS 05','Kedungarum','Kuningan','Kuningan',1),
('DRA. HJ. WARDATUN NA IM','Partai Persatuan Pembangunan','TPS 06','Kedungarum','Kuningan','Kuningan',0),
('DRA. HJ. WARDATUN NA IM','Partai Persatuan Pembangunan','TPS 07','Kedungarum','Kuningan','Kuningan',1),
('DRA. HJ. WARDATUN NA IM','Partai Persatuan Pembangunan','TPS 08','Kedungarum','Kuningan','Kuningan',0),
('DR. H. HERI SOLEHUDIN ATMAWIDJAJA, MM','Partai Persatuan Pembangunan','TPS 01','Kedungarum','Kuningan','Kuningan',0),
('DR. H. HERI SOLEHUDIN ATMAWIDJAJA, MM','Partai Persatuan Pembangunan','TPS 02','Kedungarum','Kuningan','Kuningan',0),
('DR. H. HERI SOLEHUDIN ATMAWIDJAJA, MM','Partai Persatuan Pembangunan','TPS 03','Kedungarum','Kuningan','Kuningan',2),
('DR. H. HERI SOLEHUDIN ATMAWIDJAJA, MM','Partai Persatuan Pembangunan','TPS 04','Kedungarum','Kuningan','Kuningan',1),
('DR. H. HERI SOLEHUDIN ATMAWIDJAJA, MM','Partai Persatuan Pembangunan','TPS 05','Kedungarum','Kuningan','Kuningan',0),
('DR. H. HERI SOLEHUDIN ATMAWIDJAJA, MM','Partai Persatuan Pembangunan','TPS 06','Kedungarum','Kuningan','Kuningan',2),
('DR. H. HERI SOLEHUDIN ATMAWIDJAJA, MM','Partai Persatuan Pembangunan','TPS 07','Kedungarum','Kuningan','Kuningan',0),
('DR. H. HERI SOLEHUDIN ATMAWIDJAJA, MM','Partai Persatuan Pembangunan','TPS 08','Kedungarum','Kuningan','Kuningan',0),
('IDA NURHAIDAH','Partai Persatuan Pembangunan','TPS 01','Kedungarum','Kuningan','Kuningan',0),
('IDA NURHAIDAH','Partai Persatuan Pembangunan','TPS 02','Kedungarum','Kuningan','Kuningan',0),
('IDA NURHAIDAH','Partai Persatuan Pembangunan','TPS 03','Kedungarum','Kuningan','Kuningan',0),
('IDA NURHAIDAH','Partai Persatuan Pembangunan','TPS 04','Kedungarum','Kuningan','Kuningan',1),
('IDA NURHAIDAH','Partai Persatuan Pembangunan','TPS 05','Kedungarum','Kuningan','Kuningan',0),
('IDA NURHAIDAH','Partai Persatuan Pembangunan','TPS 06','Kedungarum','Kuningan','Kuningan',0),
('IDA NURHAIDAH','Partai Persatuan Pembangunan','TPS 07','Kedungarum','Kuningan','Kuningan',0),
('IDA NURHAIDAH','Partai Persatuan Pembangunan','TPS 08','Kedungarum','Kuningan','Kuningan',0),
('SITI HABSYAH MAYAWATI, S.E.','Partai Persatuan Pembangunan','TPS 01','Kedungarum','Kuningan','Kuningan',0),
('SITI HABSYAH MAYAWATI, S.E.','Partai Persatuan Pembangunan','TPS 02','Kedungarum','Kuningan','Kuningan',1),
('SITI HABSYAH MAYAWATI, S.E.','Partai Persatuan Pembangunan','TPS 03','Kedungarum','Kuningan','Kuningan',0),
('SITI HABSYAH MAYAWATI, S.E.','Partai Persatuan Pembangunan','TPS 04','Kedungarum','Kuningan','Kuningan',0),
('SITI HABSYAH MAYAWATI, S.E.','Partai Persatuan Pembangunan','TPS 05','Kedungarum','Kuningan','Kuningan',0),
('SITI HABSYAH MAYAWATI, S.E.','Partai Persatuan Pembangunan','TPS 06','Kedungarum','Kuningan','Kuningan',0),
('SITI HABSYAH MAYAWATI, S.E.','Partai Persatuan Pembangunan','TPS 07','Kedungarum','Kuningan','Kuningan',0),
('SITI HABSYAH MAYAWATI, S.E.','Partai Persatuan Pembangunan','TPS 08','Kedungarum','Kuningan','Kuningan',0),
('ALI SA RONI, S.IP','Partai Persatuan Pembangunan','TPS 01','Kedungarum','Kuningan','Kuningan',0),
('ALI SA RONI, S.IP','Partai Persatuan Pembangunan','TPS 02','Kedungarum','Kuningan','Kuningan',0),
('ALI SA RONI, S.IP','Partai Persatuan Pembangunan','TPS 03','Kedungarum','Kuningan','Kuningan',0),
('ALI SA RONI, S.IP','Partai Persatuan Pembangunan','TPS 04','Kedungarum','Kuningan','Kuningan',0),
('ALI SA RONI, S.IP','Partai Persatuan Pembangunan','TPS 05','Kedungarum','Kuningan','Kuningan',0),
('ALI SA RONI, S.IP','Partai Persatuan Pembangunan','TPS 06','Kedungarum','Kuningan','Kuningan',0),
('ALI SA RONI, S.IP','Partai Persatuan Pembangunan','TPS 07','Kedungarum','Kuningan','Kuningan',2),
('ALI SA RONI, S.IP','Partai Persatuan Pembangunan','TPS 08','Kedungarum','Kuningan','Kuningan',0),
('Partai Solidaritas Indonesia','Partai Solidaritas Indonesia','TPS 01','Kedungarum','Kuningan','Kuningan',0),
('Partai Solidaritas Indonesia','Partai Solidaritas Indonesia','TPS 02','Kedungarum','Kuningan','Kuningan',0),
('Partai Solidaritas Indonesia','Partai Solidaritas Indonesia','TPS 03','Kedungarum','Kuningan','Kuningan',1),
('Partai Solidaritas Indonesia','Partai Solidaritas Indonesia','TPS 04','Kedungarum','Kuningan','Kuningan',0),
('Partai Solidaritas Indonesia','Partai Solidaritas Indonesia','TPS 05','Kedungarum','Kuningan','Kuningan',3),
('Partai Solidaritas Indonesia','Partai Solidaritas Indonesia','TPS 06','Kedungarum','Kuningan','Kuningan',1),
('Partai Solidaritas Indonesia','Partai Solidaritas Indonesia','TPS 07','Kedungarum','Kuningan','Kuningan',1),
('Partai Solidaritas Indonesia','Partai Solidaritas Indonesia','TPS 08','Kedungarum','Kuningan','Kuningan',2),
('NUNU NUGRAHA','Partai Solidaritas Indonesia','TPS 01','Kedungarum','Kuningan','Kuningan',0),
('NUNU NUGRAHA','Partai Solidaritas Indonesia','TPS 02','Kedungarum','Kuningan','Kuningan',0),
('NUNU NUGRAHA','Partai Solidaritas Indonesia','TPS 03','Kedungarum','Kuningan','Kuningan',0),
('NUNU NUGRAHA','Partai Solidaritas Indonesia','TPS 04','Kedungarum','Kuningan','Kuningan',0),
('NUNU NUGRAHA','Partai Solidaritas Indonesia','TPS 05','Kedungarum','Kuningan','Kuningan',0),
('NUNU NUGRAHA','Partai Solidaritas Indonesia','TPS 06','Kedungarum','Kuningan','Kuningan',0),
('NUNU NUGRAHA','Partai Solidaritas Indonesia','TPS 07','Kedungarum','Kuningan','Kuningan',0),
('NUNU NUGRAHA','Partai Solidaritas Indonesia','TPS 08','Kedungarum','Kuningan','Kuningan',0),
('KURNIASARI AMBAR, S.Pd','Partai Solidaritas Indonesia','TPS 01','Kedungarum','Kuningan','Kuningan',1),
('KURNIASARI AMBAR, S.Pd','Partai Solidaritas Indonesia','TPS 02','Kedungarum','Kuningan','Kuningan',0),
('KURNIASARI AMBAR, S.Pd','Partai Solidaritas Indonesia','TPS 03','Kedungarum','Kuningan','Kuningan',0),
('KURNIASARI AMBAR, S.Pd','Partai Solidaritas Indonesia','TPS 04','Kedungarum','Kuningan','Kuningan',0),
('KURNIASARI AMBAR, S.Pd','Partai Solidaritas Indonesia','TPS 05','Kedungarum','Kuningan','Kuningan',0),
('KURNIASARI AMBAR, S.Pd','Partai Solidaritas Indonesia','TPS 06','Kedungarum','Kuningan','Kuningan',0),
('KURNIASARI AMBAR, S.Pd','Partai Solidaritas Indonesia','TPS 07','Kedungarum','Kuningan','Kuningan',0),
('KURNIASARI AMBAR, S.Pd','Partai Solidaritas Indonesia','TPS 08','Kedungarum','Kuningan','Kuningan',0),
('ANDRIANSYAH, S.Si, M.S.E','Partai Solidaritas Indonesia','TPS 01','Kedungarum','Kuningan','Kuningan',0),
('ANDRIANSYAH, S.Si, M.S.E','Partai Solidaritas Indonesia','TPS 02','Kedungarum','Kuningan','Kuningan',0),
('ANDRIANSYAH, S.Si, M.S.E','Partai Solidaritas Indonesia','TPS 03','Kedungarum','Kuningan','Kuningan',0),
('ANDRIANSYAH, S.Si, M.S.E','Partai Solidaritas Indonesia','TPS 04','Kedungarum','Kuningan','Kuningan',1),
('ANDRIANSYAH, S.Si, M.S.E','Partai Solidaritas Indonesia','TPS 05','Kedungarum','Kuningan','Kuningan',0),
('ANDRIANSYAH, S.Si, M.S.E','Partai Solidaritas Indonesia','TPS 06','Kedungarum','Kuningan','Kuningan',1),
('ANDRIANSYAH, S.Si, M.S.E','Partai Solidaritas Indonesia','TPS 07','Kedungarum','Kuningan','Kuningan',0),
('ANDRIANSYAH, S.Si, M.S.E','Partai Solidaritas Indonesia','TPS 08','Kedungarum','Kuningan','Kuningan',1),
('BAMBANG PRAKUSO, BA','Partai Solidaritas Indonesia','TPS 01','Kedungarum','Kuningan','Kuningan',0),
('BAMBANG PRAKUSO, BA','Partai Solidaritas Indonesia','TPS 02','Kedungarum','Kuningan','Kuningan',0),
('BAMBANG PRAKUSO, BA','Partai Solidaritas Indonesia','TPS 03','Kedungarum','Kuningan','Kuningan',0),
('BAMBANG PRAKUSO, BA','Partai Solidaritas Indonesia','TPS 04','Kedungarum','Kuningan','Kuningan',0),
('BAMBANG PRAKUSO, BA','Partai Solidaritas Indonesia','TPS 05','Kedungarum','Kuningan','Kuningan',0),
('BAMBANG PRAKUSO, BA','Partai Solidaritas Indonesia','TPS 06','Kedungarum','Kuningan','Kuningan',1),
('BAMBANG PRAKUSO, BA','Partai Solidaritas Indonesia','TPS 07','Kedungarum','Kuningan','Kuningan',0),
('BAMBANG PRAKUSO, BA','Partai Solidaritas Indonesia','TPS 08','Kedungarum','Kuningan','Kuningan',0),
('Drs. DADANG SETIAWAN, M.Si','Partai Solidaritas Indonesia','TPS 01','Kedungarum','Kuningan','Kuningan',0),
('Drs. DADANG SETIAWAN, M.Si','Partai Solidaritas Indonesia','TPS 02','Kedungarum','Kuningan','Kuningan',0),
('Drs. DADANG SETIAWAN, M.Si','Partai Solidaritas Indonesia','TPS 03','Kedungarum','Kuningan','Kuningan',0),
('Drs. DADANG SETIAWAN, M.Si','Partai Solidaritas Indonesia','TPS 04','Kedungarum','Kuningan','Kuningan',0),
('Drs. DADANG SETIAWAN, M.Si','Partai Solidaritas Indonesia','TPS 05','Kedungarum','Kuningan','Kuningan',0),
('Drs. DADANG SETIAWAN, M.Si','Partai Solidaritas Indonesia','TPS 06','Kedungarum','Kuningan','Kuningan',0),
('Drs. DADANG SETIAWAN, M.Si','Partai Solidaritas Indonesia','TPS 07','Kedungarum','Kuningan','Kuningan',0),
('Drs. DADANG SETIAWAN, M.Si','Partai Solidaritas Indonesia','TPS 08','Kedungarum','Kuningan','Kuningan',0),
('ISMI DIANG MEILAN','Partai Solidaritas Indonesia','TPS 01','Kedungarum','Kuningan','Kuningan',0),
('ISMI DIANG MEILAN','Partai Solidaritas Indonesia','TPS 02','Kedungarum','Kuningan','Kuningan',0),
('ISMI DIANG MEILAN','Partai Solidaritas Indonesia','TPS 03','Kedungarum','Kuningan','Kuningan',1),
('ISMI DIANG MEILAN','Partai Solidaritas Indonesia','TPS 04','Kedungarum','Kuningan','Kuningan',0),
('ISMI DIANG MEILAN','Partai Solidaritas Indonesia','TPS 05','Kedungarum','Kuningan','Kuningan',0),
('ISMI DIANG MEILAN','Partai Solidaritas Indonesia','TPS 06','Kedungarum','Kuningan','Kuningan',0),
('ISMI DIANG MEILAN','Partai Solidaritas Indonesia','TPS 07','Kedungarum','Kuningan','Kuningan',0),
('ISMI DIANG MEILAN','Partai Solidaritas Indonesia','TPS 08','Kedungarum','Kuningan','Kuningan',0),
('NURUL GEOVANI','Partai Solidaritas Indonesia','TPS 01','Kedungarum','Kuningan','Kuningan',0),
('NURUL GEOVANI','Partai Solidaritas Indonesia','TPS 02','Kedungarum','Kuningan','Kuningan',0),
('NURUL GEOVANI','Partai Solidaritas Indonesia','TPS 03','Kedungarum','Kuningan','Kuningan',0),
('NURUL GEOVANI','Partai Solidaritas Indonesia','TPS 04','Kedungarum','Kuningan','Kuningan',0),
('NURUL GEOVANI','Partai Solidaritas Indonesia','TPS 05','Kedungarum','Kuningan','Kuningan',0),
('NURUL GEOVANI','Partai Solidaritas Indonesia','TPS 06','Kedungarum','Kuningan','Kuningan',1),
('NURUL GEOVANI','Partai Solidaritas Indonesia','TPS 07','Kedungarum','Kuningan','Kuningan',0),
('NURUL GEOVANI','Partai Solidaritas Indonesia','TPS 08','Kedungarum','Kuningan','Kuningan',1),
('Partai Amanat Nasional','Partai Amanat Nasional','TPS 01','Kedungarum','Kuningan','Kuningan',3),
('Partai Amanat Nasional','Partai Amanat Nasional','TPS 02','Kedungarum','Kuningan','Kuningan',5),
('Partai Amanat Nasional','Partai Amanat Nasional','TPS 03','Kedungarum','Kuningan','Kuningan',2),
('Partai Amanat Nasional','Partai Amanat Nasional','TPS 04','Kedungarum','Kuningan','Kuningan',5),
('Partai Amanat Nasional','Partai Amanat Nasional','TPS 05','Kedungarum','Kuningan','Kuningan',2),
('Partai Amanat Nasional','Partai Amanat Nasional','TPS 06','Kedungarum','Kuningan','Kuningan',1),
('Partai Amanat Nasional','Partai Amanat Nasional','TPS 07','Kedungarum','Kuningan','Kuningan',3),
('Partai Amanat Nasional','Partai Amanat Nasional','TPS 08','Kedungarum','Kuningan','Kuningan',1),
('BUDI YOUYASTRI','Partai Amanat Nasional','TPS 01','Kedungarum','Kuningan','Kuningan',0),
('BUDI YOUYASTRI','Partai Amanat Nasional','TPS 02','Kedungarum','Kuningan','Kuningan',0),
('BUDI YOUYASTRI','Partai Amanat Nasional','TPS 03','Kedungarum','Kuningan','Kuningan',1),
('BUDI YOUYASTRI','Partai Amanat Nasional','TPS 04','Kedungarum','Kuningan','Kuningan',1),
('BUDI YOUYASTRI','Partai Amanat Nasional','TPS 05','Kedungarum','Kuningan','Kuningan',0),
('BUDI YOUYASTRI','Partai Amanat Nasional','TPS 06','Kedungarum','Kuningan','Kuningan',1),
('BUDI YOUYASTRI','Partai Amanat Nasional','TPS 07','Kedungarum','Kuningan','Kuningan',1),
('BUDI YOUYASTRI','Partai Amanat Nasional','TPS 08','Kedungarum','Kuningan','Kuningan',0),
('Ir. H. CHANDRA TIRTAWIJAYA','Partai Amanat Nasional','TPS 01','Kedungarum','Kuningan','Kuningan',2),
('Ir. H. CHANDRA TIRTAWIJAYA','Partai Amanat Nasional','TPS 02','Kedungarum','Kuningan','Kuningan',1),
('Ir. H. CHANDRA TIRTAWIJAYA','Partai Amanat Nasional','TPS 03','Kedungarum','Kuningan','Kuningan',1),
('Ir. H. CHANDRA TIRTAWIJAYA','Partai Amanat Nasional','TPS 04','Kedungarum','Kuningan','Kuningan',0),
('Ir. H. CHANDRA TIRTAWIJAYA','Partai Amanat Nasional','TPS 05','Kedungarum','Kuningan','Kuningan',1),
('Ir. H. CHANDRA TIRTAWIJAYA','Partai Amanat Nasional','TPS 06','Kedungarum','Kuningan','Kuningan',1),
('Ir. H. CHANDRA TIRTAWIJAYA','Partai Amanat Nasional','TPS 07','Kedungarum','Kuningan','Kuningan',0),
('Ir. H. CHANDRA TIRTAWIJAYA','Partai Amanat Nasional','TPS 08','Kedungarum','Kuningan','Kuningan',3),
('Dra. Hj. VETRINA SUTINGAH, M.Pd','Partai Amanat Nasional','TPS 01','Kedungarum','Kuningan','Kuningan',0),
('Dra. Hj. VETRINA SUTINGAH, M.Pd','Partai Amanat Nasional','TPS 02','Kedungarum','Kuningan','Kuningan',1),
('Dra. Hj. VETRINA SUTINGAH, M.Pd','Partai Amanat Nasional','TPS 03','Kedungarum','Kuningan','Kuningan',1),
('Dra. Hj. VETRINA SUTINGAH, M.Pd','Partai Amanat Nasional','TPS 04','Kedungarum','Kuningan','Kuningan',1),
('Dra. Hj. VETRINA SUTINGAH, M.Pd','Partai Amanat Nasional','TPS 05','Kedungarum','Kuningan','Kuningan',1),
('Dra. Hj. VETRINA SUTINGAH, M.Pd','Partai Amanat Nasional','TPS 06','Kedungarum','Kuningan','Kuningan',0),
('Dra. Hj. VETRINA SUTINGAH, M.Pd','Partai Amanat Nasional','TPS 07','Kedungarum','Kuningan','Kuningan',0),
('Dra. Hj. VETRINA SUTINGAH, M.Pd','Partai Amanat Nasional','TPS 08','Kedungarum','Kuningan','Kuningan',0),
('AAN HANAFI','Partai Amanat Nasional','TPS 01','Kedungarum','Kuningan','Kuningan',0),
('AAN HANAFI','Partai Amanat Nasional','TPS 02','Kedungarum','Kuningan','Kuningan',1),
('AAN HANAFI','Partai Amanat Nasional','TPS 03','Kedungarum','Kuningan','Kuningan',0),
('AAN HANAFI','Partai Amanat Nasional','TPS 04','Kedungarum','Kuningan','Kuningan',0),
('AAN HANAFI','Partai Amanat Nasional','TPS 05','Kedungarum','Kuningan','Kuningan',2),
('AAN HANAFI','Partai Amanat Nasional','TPS 06','Kedungarum','Kuningan','Kuningan',0),
('AAN HANAFI','Partai Amanat Nasional','TPS 07','Kedungarum','Kuningan','Kuningan',0),
('AAN HANAFI','Partai Amanat Nasional','TPS 08','Kedungarum','Kuningan','Kuningan',1),
('H. KUSWARA SASTRA PERMANA','Partai Amanat Nasional','TPS 01','Kedungarum','Kuningan','Kuningan',3),
('H. KUSWARA SASTRA PERMANA','Partai Amanat Nasional','TPS 02','Kedungarum','Kuningan','Kuningan',0),
('H. KUSWARA SASTRA PERMANA','Partai Amanat Nasional','TPS 03','Kedungarum','Kuningan','Kuningan',0),
('H. KUSWARA SASTRA PERMANA','Partai Amanat Nasional','TPS 04','Kedungarum','Kuningan','Kuningan',1),
('H. KUSWARA SASTRA PERMANA','Partai Amanat Nasional','TPS 05','Kedungarum','Kuningan','Kuningan',0),
('H. KUSWARA SASTRA PERMANA','Partai Amanat Nasional','TPS 06','Kedungarum','Kuningan','Kuningan',0),
('H. KUSWARA SASTRA PERMANA','Partai Amanat Nasional','TPS 07','Kedungarum','Kuningan','Kuningan',1),
('H. KUSWARA SASTRA PERMANA','Partai Amanat Nasional','TPS 08','Kedungarum','Kuningan','Kuningan',0),
('YUMAIZA, SE','Partai Amanat Nasional','TPS 01','Kedungarum','Kuningan','Kuningan',0),
('YUMAIZA, SE','Partai Amanat Nasional','TPS 02','Kedungarum','Kuningan','Kuningan',0),
('YUMAIZA, SE','Partai Amanat Nasional','TPS 03','Kedungarum','Kuningan','Kuningan',0),
('YUMAIZA, SE','Partai Amanat Nasional','TPS 04','Kedungarum','Kuningan','Kuningan',1),
('YUMAIZA, SE','Partai Amanat Nasional','TPS 05','Kedungarum','Kuningan','Kuningan',0),
('YUMAIZA, SE','Partai Amanat Nasional','TPS 06','Kedungarum','Kuningan','Kuningan',0),
('YUMAIZA, SE','Partai Amanat Nasional','TPS 07','Kedungarum','Kuningan','Kuningan',0),
('YUMAIZA, SE','Partai Amanat Nasional','TPS 08','Kedungarum','Kuningan','Kuningan',0),
('MARINA OKTAVIA, A.Md','Partai Amanat Nasional','TPS 01','Kedungarum','Kuningan','Kuningan',1),
('MARINA OKTAVIA, A.Md','Partai Amanat Nasional','TPS 02','Kedungarum','Kuningan','Kuningan',0),
('MARINA OKTAVIA, A.Md','Partai Amanat Nasional','TPS 03','Kedungarum','Kuningan','Kuningan',0),
('MARINA OKTAVIA, A.Md','Partai Amanat Nasional','TPS 04','Kedungarum','Kuningan','Kuningan',0),
('MARINA OKTAVIA, A.Md','Partai Amanat Nasional','TPS 05','Kedungarum','Kuningan','Kuningan',0),
('MARINA OKTAVIA, A.Md','Partai Amanat Nasional','TPS 06','Kedungarum','Kuningan','Kuningan',0),
('MARINA OKTAVIA, A.Md','Partai Amanat Nasional','TPS 07','Kedungarum','Kuningan','Kuningan',0),
('MARINA OKTAVIA, A.Md','Partai Amanat Nasional','TPS 08','Kedungarum','Kuningan','Kuningan',0),
('Partai Hati Nurani Rakyat','Partai Hati Nurani Rakyat','TPS 01','Kedungarum','Kuningan','Kuningan',0),
('Partai Hati Nurani Rakyat','Partai Hati Nurani Rakyat','TPS 02','Kedungarum','Kuningan','Kuningan',0),
('Partai Hati Nurani Rakyat','Partai Hati Nurani Rakyat','TPS 03','Kedungarum','Kuningan','Kuningan',0),
('Partai Hati Nurani Rakyat','Partai Hati Nurani Rakyat','TPS 04','Kedungarum','Kuningan','Kuningan',0),
('Partai Hati Nurani Rakyat','Partai Hati Nurani Rakyat','TPS 05','Kedungarum','Kuningan','Kuningan',0),
('Partai Hati Nurani Rakyat','Partai Hati Nurani Rakyat','TPS 06','Kedungarum','Kuningan','Kuningan',0),
('Partai Hati Nurani Rakyat','Partai Hati Nurani Rakyat','TPS 07','Kedungarum','Kuningan','Kuningan',1),
('Partai Hati Nurani Rakyat','Partai Hati Nurani Rakyat','TPS 08','Kedungarum','Kuningan','Kuningan',0),
('AZRAL HARDY','Partai Hati Nurani Rakyat','TPS 01','Kedungarum','Kuningan','Kuningan',0),
('AZRAL HARDY','Partai Hati Nurani Rakyat','TPS 02','Kedungarum','Kuningan','Kuningan',0),
('AZRAL HARDY','Partai Hati Nurani Rakyat','TPS 03','Kedungarum','Kuningan','Kuningan',0),
('AZRAL HARDY','Partai Hati Nurani Rakyat','TPS 04','Kedungarum','Kuningan','Kuningan',0),
('AZRAL HARDY','Partai Hati Nurani Rakyat','TPS 05','Kedungarum','Kuningan','Kuningan',1),
('AZRAL HARDY','Partai Hati Nurani Rakyat','TPS 06','Kedungarum','Kuningan','Kuningan',0),
('AZRAL HARDY','Partai Hati Nurani Rakyat','TPS 07','Kedungarum','Kuningan','Kuningan',0),
('AZRAL HARDY','Partai Hati Nurani Rakyat','TPS 08','Kedungarum','Kuningan','Kuningan',0),
('BUDI WARSITO','Partai Hati Nurani Rakyat','TPS 01','Kedungarum','Kuningan','Kuningan',0),
('BUDI WARSITO','Partai Hati Nurani Rakyat','TPS 02','Kedungarum','Kuningan','Kuningan',0),
('BUDI WARSITO','Partai Hati Nurani Rakyat','TPS 03','Kedungarum','Kuningan','Kuningan',0),
('BUDI WARSITO','Partai Hati Nurani Rakyat','TPS 04','Kedungarum','Kuningan','Kuningan',0),
('BUDI WARSITO','Partai Hati Nurani Rakyat','TPS 05','Kedungarum','Kuningan','Kuningan',0),
('BUDI WARSITO','Partai Hati Nurani Rakyat','TPS 06','Kedungarum','Kuningan','Kuningan',0),
('BUDI WARSITO','Partai Hati Nurani Rakyat','TPS 07','Kedungarum','Kuningan','Kuningan',0),
('BUDI WARSITO','Partai Hati Nurani Rakyat','TPS 08','Kedungarum','Kuningan','Kuningan',0),
('ARIENA JUNISA','Partai Hati Nurani Rakyat','TPS 01','Kedungarum','Kuningan','Kuningan',0),
('ARIENA JUNISA','Partai Hati Nurani Rakyat','TPS 02','Kedungarum','Kuningan','Kuningan',0),
('ARIENA JUNISA','Partai Hati Nurani Rakyat','TPS 03','Kedungarum','Kuningan','Kuningan',0),
('ARIENA JUNISA','Partai Hati Nurani Rakyat','TPS 04','Kedungarum','Kuningan','Kuningan',0),
('ARIENA JUNISA','Partai Hati Nurani Rakyat','TPS 05','Kedungarum','Kuningan','Kuningan',0),
('ARIENA JUNISA','Partai Hati Nurani Rakyat','TPS 06','Kedungarum','Kuningan','Kuningan',0),
('ARIENA JUNISA','Partai Hati Nurani Rakyat','TPS 07','Kedungarum','Kuningan','Kuningan',0),
('ARIENA JUNISA','Partai Hati Nurani Rakyat','TPS 08','Kedungarum','Kuningan','Kuningan',0),
('Partai Demokrat','Partai Demokrat','TPS 01','Kedungarum','Kuningan','Kuningan',4),
('Partai Demokrat','Partai Demokrat','TPS 02','Kedungarum','Kuningan','Kuningan',4),
('Partai Demokrat','Partai Demokrat','TPS 03','Kedungarum','Kuningan','Kuningan',8),
('Partai Demokrat','Partai Demokrat','TPS 04','Kedungarum','Kuningan','Kuningan',10),
('Partai Demokrat','Partai Demokrat','TPS 05','Kedungarum','Kuningan','Kuningan',6),
('Partai Demokrat','Partai Demokrat','TPS 06','Kedungarum','Kuningan','Kuningan',9),
('Partai Demokrat','Partai Demokrat','TPS 07','Kedungarum','Kuningan','Kuningan',11),
('Partai Demokrat','Partai Demokrat','TPS 08','Kedungarum','Kuningan','Kuningan',9),
('H.DIDI IRAWADI SYAMSUDDIN, SH','Partai Demokrat','TPS 01','Kedungarum','Kuningan','Kuningan',2),
('H.DIDI IRAWADI SYAMSUDDIN, SH','Partai Demokrat','TPS 02','Kedungarum','Kuningan','Kuningan',1),
('H.DIDI IRAWADI SYAMSUDDIN, SH','Partai Demokrat','TPS 03','Kedungarum','Kuningan','Kuningan',4),
('H.DIDI IRAWADI SYAMSUDDIN, SH','Partai Demokrat','TPS 04','Kedungarum','Kuningan','Kuningan',0),
('H.DIDI IRAWADI SYAMSUDDIN, SH','Partai Demokrat','TPS 05','Kedungarum','Kuningan','Kuningan',3),
('H.DIDI IRAWADI SYAMSUDDIN, SH','Partai Demokrat','TPS 06','Kedungarum','Kuningan','Kuningan',5),
('H.DIDI IRAWADI SYAMSUDDIN, SH','Partai Demokrat','TPS 07','Kedungarum','Kuningan','Kuningan',4),
('H.DIDI IRAWADI SYAMSUDDIN, SH','Partai Demokrat','TPS 08','Kedungarum','Kuningan','Kuningan',3),
('H.T.MAMAT ROBBY SUGANDA, M.AP','Partai Demokrat','TPS 01','Kedungarum','Kuningan','Kuningan',8),
('H.T.MAMAT ROBBY SUGANDA, M.AP','Partai Demokrat','TPS 02','Kedungarum','Kuningan','Kuningan',4),
('H.T.MAMAT ROBBY SUGANDA, M.AP','Partai Demokrat','TPS 03','Kedungarum','Kuningan','Kuningan',9),
('H.T.MAMAT ROBBY SUGANDA, M.AP','Partai Demokrat','TPS 04','Kedungarum','Kuningan','Kuningan',8),
('H.T.MAMAT ROBBY SUGANDA, M.AP','Partai Demokrat','TPS 05','Kedungarum','Kuningan','Kuningan',7),
('H.T.MAMAT ROBBY SUGANDA, M.AP','Partai Demokrat','TPS 06','Kedungarum','Kuningan','Kuningan',10),
('H.T.MAMAT ROBBY SUGANDA, M.AP','Partai Demokrat','TPS 07','Kedungarum','Kuningan','Kuningan',3),
('H.T.MAMAT ROBBY SUGANDA, M.AP','Partai Demokrat','TPS 08','Kedungarum','Kuningan','Kuningan',21),
('HJ. YOYOH RUKIJAH, S.TR. KEB','Partai Demokrat','TPS 01','Kedungarum','Kuningan','Kuningan',0),
('HJ. YOYOH RUKIJAH, S.TR. KEB','Partai Demokrat','TPS 02','Kedungarum','Kuningan','Kuningan',2),
('HJ. YOYOH RUKIJAH, S.TR. KEB','Partai Demokrat','TPS 03','Kedungarum','Kuningan','Kuningan',2),
('HJ. YOYOH RUKIJAH, S.TR. KEB','Partai Demokrat','TPS 04','Kedungarum','Kuningan','Kuningan',0),
('HJ. YOYOH RUKIJAH, S.TR. KEB','Partai Demokrat','TPS 05','Kedungarum','Kuningan','Kuningan',3),
('HJ. YOYOH RUKIJAH, S.TR. KEB','Partai Demokrat','TPS 06','Kedungarum','Kuningan','Kuningan',3),
('HJ. YOYOH RUKIJAH, S.TR. KEB','Partai Demokrat','TPS 07','Kedungarum','Kuningan','Kuningan',4),
('HJ. YOYOH RUKIJAH, S.TR. KEB','Partai Demokrat','TPS 08','Kedungarum','Kuningan','Kuningan',2),
('TB CEPPY SUBHAN SOLICHIN, SE','Partai Demokrat','TPS 01','Kedungarum','Kuningan','Kuningan',0),
('TB CEPPY SUBHAN SOLICHIN, SE','Partai Demokrat','TPS 02','Kedungarum','Kuningan','Kuningan',0),
('TB CEPPY SUBHAN SOLICHIN, SE','Partai Demokrat','TPS 03','Kedungarum','Kuningan','Kuningan',0),
('TB CEPPY SUBHAN SOLICHIN, SE','Partai Demokrat','TPS 04','Kedungarum','Kuningan','Kuningan',0),
('TB CEPPY SUBHAN SOLICHIN, SE','Partai Demokrat','TPS 05','Kedungarum','Kuningan','Kuningan',0),
('TB CEPPY SUBHAN SOLICHIN, SE','Partai Demokrat','TPS 06','Kedungarum','Kuningan','Kuningan',1),
('TB CEPPY SUBHAN SOLICHIN, SE','Partai Demokrat','TPS 07','Kedungarum','Kuningan','Kuningan',0),
('TB CEPPY SUBHAN SOLICHIN, SE','Partai Demokrat','TPS 08','Kedungarum','Kuningan','Kuningan',0),
('Dr. Hj. IRMA BASTAMAN HARIS','Partai Demokrat','TPS 01','Kedungarum','Kuningan','Kuningan',0),
('Dr. Hj. IRMA BASTAMAN HARIS','Partai Demokrat','TPS 02','Kedungarum','Kuningan','Kuningan',0),
('Dr. Hj. IRMA BASTAMAN HARIS','Partai Demokrat','TPS 03','Kedungarum','Kuningan','Kuningan',0),
('Dr. Hj. IRMA BASTAMAN HARIS','Partai Demokrat','TPS 04','Kedungarum','Kuningan','Kuningan',1),
('Dr. Hj. IRMA BASTAMAN HARIS','Partai Demokrat','TPS 05','Kedungarum','Kuningan','Kuningan',0),
('Dr. Hj. IRMA BASTAMAN HARIS','Partai Demokrat','TPS 06','Kedungarum','Kuningan','Kuningan',0),
('Dr. Hj. IRMA BASTAMAN HARIS','Partai Demokrat','TPS 07','Kedungarum','Kuningan','Kuningan',0),
('Dr. Hj. IRMA BASTAMAN HARIS','Partai Demokrat','TPS 08','Kedungarum','Kuningan','Kuningan',1),
('YETI HERYATI, SH','Partai Demokrat','TPS 01','Kedungarum','Kuningan','Kuningan',4),
('YETI HERYATI, SH','Partai Demokrat','TPS 02','Kedungarum','Kuningan','Kuningan',1),
('YETI HERYATI, SH','Partai Demokrat','TPS 03','Kedungarum','Kuningan','Kuningan',1),
('YETI HERYATI, SH','Partai Demokrat','TPS 04','Kedungarum','Kuningan','Kuningan',1),
('YETI HERYATI, SH','Partai Demokrat','TPS 05','Kedungarum','Kuningan','Kuningan',0),
('YETI HERYATI, SH','Partai Demokrat','TPS 06','Kedungarum','Kuningan','Kuningan',1),
('YETI HERYATI, SH','Partai Demokrat','TPS 07','Kedungarum','Kuningan','Kuningan',0),
('YETI HERYATI, SH','Partai Demokrat','TPS 08','Kedungarum','Kuningan','Kuningan',0),
('DENI DURIYATUL ROMDONAH','Partai Demokrat','TPS 01','Kedungarum','Kuningan','Kuningan',0),
('DENI DURIYATUL ROMDONAH','Partai Demokrat','TPS 02','Kedungarum','Kuningan','Kuningan',0),
('DENI DURIYATUL ROMDONAH','Partai Demokrat','TPS 03','Kedungarum','Kuningan','Kuningan',0),
('DENI DURIYATUL ROMDONAH','Partai Demokrat','TPS 04','Kedungarum','Kuningan','Kuningan',0),
('DENI DURIYATUL ROMDONAH','Partai Demokrat','TPS 05','Kedungarum','Kuningan','Kuningan',0),
('DENI DURIYATUL ROMDONAH','Partai Demokrat','TPS 06','Kedungarum','Kuningan','Kuningan',0),
('DENI DURIYATUL ROMDONAH','Partai Demokrat','TPS 07','Kedungarum','Kuningan','Kuningan',0),
('DENI DURIYATUL ROMDONAH','Partai Demokrat','TPS 08','Kedungarum','Kuningan','Kuningan',2),
('Partai Bulan Bintang','Partai Bulan Bintang','TPS 01','Kedungarum','Kuningan','Kuningan',0),
('Partai Bulan Bintang','Partai Bulan Bintang','TPS 02','Kedungarum','Kuningan','Kuningan',0),
('Partai Bulan Bintang','Partai Bulan Bintang','TPS 03','Kedungarum','Kuningan','Kuningan',1),
('Partai Bulan Bintang','Partai Bulan Bintang','TPS 04','Kedungarum','Kuningan','Kuningan',2),
('Partai Bulan Bintang','Partai Bulan Bintang','TPS 05','Kedungarum','Kuningan','Kuningan',0),
('Partai Bulan Bintang','Partai Bulan Bintang','TPS 06','Kedungarum','Kuningan','Kuningan',2),
('Partai Bulan Bintang','Partai Bulan Bintang','TPS 07','Kedungarum','Kuningan','Kuningan',0),
('Partai Bulan Bintang','Partai Bulan Bintang','TPS 08','Kedungarum','Kuningan','Kuningan',1),
('Dr. Ir. H. AKHMAD BAKHTIAR AMIN, M.Sc., M.Si','Partai Bulan Bintang','TPS 01','Kedungarum','Kuningan','Kuningan',1),
('Dr. Ir. H. AKHMAD BAKHTIAR AMIN, M.Sc., M.Si','Partai Bulan Bintang','TPS 02','Kedungarum','Kuningan','Kuningan',0),
('Dr. Ir. H. AKHMAD BAKHTIAR AMIN, M.Sc., M.Si','Partai Bulan Bintang','TPS 03','Kedungarum','Kuningan','Kuningan',0),
('Dr. Ir. H. AKHMAD BAKHTIAR AMIN, M.Sc., M.Si','Partai Bulan Bintang','TPS 04','Kedungarum','Kuningan','Kuningan',0),
('Dr. Ir. H. AKHMAD BAKHTIAR AMIN, M.Sc., M.Si','Partai Bulan Bintang','TPS 05','Kedungarum','Kuningan','Kuningan',0),
('Dr. Ir. H. AKHMAD BAKHTIAR AMIN, M.Sc., M.Si','Partai Bulan Bintang','TPS 06','Kedungarum','Kuningan','Kuningan',1),
('Dr. Ir. H. AKHMAD BAKHTIAR AMIN, M.Sc., M.Si','Partai Bulan Bintang','TPS 07','Kedungarum','Kuningan','Kuningan',0),
('Dr. Ir. H. AKHMAD BAKHTIAR AMIN, M.Sc., M.Si','Partai Bulan Bintang','TPS 08','Kedungarum','Kuningan','Kuningan',0),
('Ir. YULIASTUTI','Partai Bulan Bintang','TPS 01','Kedungarum','Kuningan','Kuningan',0),
('Ir. YULIASTUTI','Partai Bulan Bintang','TPS 02','Kedungarum','Kuningan','Kuningan',0),
('Ir. YULIASTUTI','Partai Bulan Bintang','TPS 03','Kedungarum','Kuningan','Kuningan',0),
('Ir. YULIASTUTI','Partai Bulan Bintang','TPS 04','Kedungarum','Kuningan','Kuningan',0),
('Ir. YULIASTUTI','Partai Bulan Bintang','TPS 05','Kedungarum','Kuningan','Kuningan',0),
('Ir. YULIASTUTI','Partai Bulan Bintang','TPS 06','Kedungarum','Kuningan','Kuningan',0),
('Ir. YULIASTUTI','Partai Bulan Bintang','TPS 07','Kedungarum','Kuningan','Kuningan',0),
('Ir. YULIASTUTI','Partai Bulan Bintang','TPS 08','Kedungarum','Kuningan','Kuningan',0),
('NUR EFENDI','Partai Bulan Bintang','TPS 01','Kedungarum','Kuningan','Kuningan',0),
('NUR EFENDI','Partai Bulan Bintang','TPS 02','Kedungarum','Kuningan','Kuningan',0),
('NUR EFENDI','Partai Bulan Bintang','TPS 03','Kedungarum','Kuningan','Kuningan',0),
('NUR EFENDI','Partai Bulan Bintang','TPS 04','Kedungarum','Kuningan','Kuningan',0),
('NUR EFENDI','Partai Bulan Bintang','TPS 05','Kedungarum','Kuningan','Kuningan',0),
('NUR EFENDI','Partai Bulan Bintang','TPS 06','Kedungarum','Kuningan','Kuningan',0),
('NUR EFENDI','Partai Bulan Bintang','TPS 07','Kedungarum','Kuningan','Kuningan',0),
('NUR EFENDI','Partai Bulan Bintang','TPS 08','Kedungarum','Kuningan','Kuningan',0),
('DRA. RAHMI YUSUF LUTAN, M.S.','Partai Bulan Bintang','TPS 01','Kedungarum','Kuningan','Kuningan',0),
('DRA. RAHMI YUSUF LUTAN, M.S.','Partai Bulan Bintang','TPS 02','Kedungarum','Kuningan','Kuningan',0),
('DRA. RAHMI YUSUF LUTAN, M.S.','Partai Bulan Bintang','TPS 03','Kedungarum','Kuningan','Kuningan',0),
('DRA. RAHMI YUSUF LUTAN, M.S.','Partai Bulan Bintang','TPS 04','Kedungarum','Kuningan','Kuningan',0),
('DRA. RAHMI YUSUF LUTAN, M.S.','Partai Bulan Bintang','TPS 05','Kedungarum','Kuningan','Kuningan',0),
('DRA. RAHMI YUSUF LUTAN, M.S.','Partai Bulan Bintang','TPS 06','Kedungarum','Kuningan','Kuningan',0),
('DRA. RAHMI YUSUF LUTAN, M.S.','Partai Bulan Bintang','TPS 07','Kedungarum','Kuningan','Kuningan',0),
('DRA. RAHMI YUSUF LUTAN, M.S.','Partai Bulan Bintang','TPS 08','Kedungarum','Kuningan','Kuningan',0),
('ALI NURHAKIM','Partai Bulan Bintang','TPS 01','Kedungarum','Kuningan','Kuningan',1),
('ALI NURHAKIM','Partai Bulan Bintang','TPS 02','Kedungarum','Kuningan','Kuningan',0),
('ALI NURHAKIM','Partai Bulan Bintang','TPS 03','Kedungarum','Kuningan','Kuningan',0),
('ALI NURHAKIM','Partai Bulan Bintang','TPS 04','Kedungarum','Kuningan','Kuningan',0),
('ALI NURHAKIM','Partai Bulan Bintang','TPS 05','Kedungarum','Kuningan','Kuningan',0),
('ALI NURHAKIM','Partai Bulan Bintang','TPS 06','Kedungarum','Kuningan','Kuningan',0),
('ALI NURHAKIM','Partai Bulan Bintang','TPS 07','Kedungarum','Kuningan','Kuningan',0),
('ALI NURHAKIM','Partai Bulan Bintang','TPS 08','Kedungarum','Kuningan','Kuningan',0),
('SALEH HIDAYAT','Partai Bulan Bintang','TPS 01','Kedungarum','Kuningan','Kuningan',0),
('SALEH HIDAYAT','Partai Bulan Bintang','TPS 02','Kedungarum','Kuningan','Kuningan',0),
('SALEH HIDAYAT','Partai Bulan Bintang','TPS 03','Kedungarum','Kuningan','Kuningan',0),
('SALEH HIDAYAT','Partai Bulan Bintang','TPS 04','Kedungarum','Kuningan','Kuningan',0),
('SALEH HIDAYAT','Partai Bulan Bintang','TPS 05','Kedungarum','Kuningan','Kuningan',0),
('SALEH HIDAYAT','Partai Bulan Bintang','TPS 06','Kedungarum','Kuningan','Kuningan',0),
('SALEH HIDAYAT','Partai Bulan Bintang','TPS 07','Kedungarum','Kuningan','Kuningan',0),
('SALEH HIDAYAT','Partai Bulan Bintang','TPS 08','Kedungarum','Kuningan','Kuningan',0),
('Partai Keadilan dan Persatuan Indonesia','Partai Keadilan dan Persatuan Indonesia','TPS 01','Kedungarum','Kuningan','Kuningan',0),
('Partai Keadilan dan Persatuan Indonesia','Partai Keadilan dan Persatuan Indonesia','TPS 02','Kedungarum','Kuningan','Kuningan',0),
('Partai Keadilan dan Persatuan Indonesia','Partai Keadilan dan Persatuan Indonesia','TPS 03','Kedungarum','Kuningan','Kuningan',1),
('Partai Keadilan dan Persatuan Indonesia','Partai Keadilan dan Persatuan Indonesia','TPS 04','Kedungarum','Kuningan','Kuningan',0),
('Partai Keadilan dan Persatuan Indonesia','Partai Keadilan dan Persatuan Indonesia','TPS 05','Kedungarum','Kuningan','Kuningan',0),
('Partai Keadilan dan Persatuan Indonesia','Partai Keadilan dan Persatuan Indonesia','TPS 06','Kedungarum','Kuningan','Kuningan',0),
('Partai Keadilan dan Persatuan Indonesia','Partai Keadilan dan Persatuan Indonesia','TPS 07','Kedungarum','Kuningan','Kuningan',1),
('Partai Keadilan dan Persatuan Indonesia','Partai Keadilan dan Persatuan Indonesia','TPS 08','Kedungarum','Kuningan','Kuningan',0),
('RICO JOHANES HASIBUAN','Partai Keadilan dan Persatuan Indonesia','TPS 01','Kedungarum','Kuningan','Kuningan',0),
('RICO JOHANES HASIBUAN','Partai Keadilan dan Persatuan Indonesia','TPS 02','Kedungarum','Kuningan','Kuningan',0),
('RICO JOHANES HASIBUAN','Partai Keadilan dan Persatuan Indonesia','TPS 03','Kedungarum','Kuningan','Kuningan',0),
('RICO JOHANES HASIBUAN','Partai Keadilan dan Persatuan Indonesia','TPS 04','Kedungarum','Kuningan','Kuningan',0),
('RICO JOHANES HASIBUAN','Partai Keadilan dan Persatuan Indonesia','TPS 05','Kedungarum','Kuningan','Kuningan',0),
('RICO JOHANES HASIBUAN','Partai Keadilan dan Persatuan Indonesia','TPS 06','Kedungarum','Kuningan','Kuningan',0),
('RICO JOHANES HASIBUAN','Partai Keadilan dan Persatuan Indonesia','TPS 07','Kedungarum','Kuningan','Kuningan',0),
('RICO JOHANES HASIBUAN','Partai Keadilan dan Persatuan Indonesia','TPS 08','Kedungarum','Kuningan','Kuningan',0),
('KARINDRA UKAR','Partai Keadilan dan Persatuan Indonesia','TPS 01','Kedungarum','Kuningan','Kuningan',0),
('KARINDRA UKAR','Partai Keadilan dan Persatuan Indonesia','TPS 02','Kedungarum','Kuningan','Kuningan',0),
('KARINDRA UKAR','Partai Keadilan dan Persatuan Indonesia','TPS 03','Kedungarum','Kuningan','Kuningan',0),
('KARINDRA UKAR','Partai Keadilan dan Persatuan Indonesia','TPS 04','Kedungarum','Kuningan','Kuningan',0),
('KARINDRA UKAR','Partai Keadilan dan Persatuan Indonesia','TPS 05','Kedungarum','Kuningan','Kuningan',0),
('KARINDRA UKAR','Partai Keadilan dan Persatuan Indonesia','TPS 06','Kedungarum','Kuningan','Kuningan',0),
('KARINDRA UKAR','Partai Keadilan dan Persatuan Indonesia','TPS 07','Kedungarum','Kuningan','Kuningan',0),
('KARINDRA UKAR','Partai Keadilan dan Persatuan Indonesia','TPS 08','Kedungarum','Kuningan','Kuningan',0),
('VONNY RIDHA','Partai Keadilan dan Persatuan Indonesia','TPS 01','Kedungarum','Kuningan','Kuningan',0),
('VONNY RIDHA','Partai Keadilan dan Persatuan Indonesia','TPS 02','Kedungarum','Kuningan','Kuningan',0),
('VONNY RIDHA','Partai Keadilan dan Persatuan Indonesia','TPS 03','Kedungarum','Kuningan','Kuningan',0),
('VONNY RIDHA','Partai Keadilan dan Persatuan Indonesia','TPS 04','Kedungarum','Kuningan','Kuningan',0),
('VONNY RIDHA','Partai Keadilan dan Persatuan Indonesia','TPS 05','Kedungarum','Kuningan','Kuningan',0),
('VONNY RIDHA','Partai Keadilan dan Persatuan Indonesia','TPS 06','Kedungarum','Kuningan','Kuningan',0),
('VONNY RIDHA','Partai Keadilan dan Persatuan Indonesia','TPS 07','Kedungarum','Kuningan','Kuningan',1),
('VONNY RIDHA','Partai Keadilan dan Persatuan Indonesia','TPS 08','Kedungarum','Kuningan','Kuningan',0);